In [9]:
from pathlib import Path

folder_path = Path(r"C:\Users\Andy\Desktop\Hard study, soft sex\Linguistics\BalticsCorpusStudy")
dataset_path = folder_path / "datasets"
pilsetas_lv_images = dataset_path / "pilsetas_lv_images"
pilsetas_ru_images = dataset_path / "pilsetas_ru_images"
riga_en_images = dataset_path / "riga_en_images"
riga_lv_images = dataset_path / "riga_lv_images"

In [10]:
import pandas as pd

In [11]:
pilsetas_lv = pd.read_csv(dataset_path / "pilsetas_lv.csv", sep="`", index_col="id")
pilsetas_ru = pd.read_csv(dataset_path / "pilsetas_ru.csv", sep="`", index_col="id")
riga_en = pd.read_csv(dataset_path / "riga_en.csv", sep="`", index_col="id")
riga_lv = pd.read_csv(dataset_path / "riga_lv.csv", sep="`", index_col="id")
pilsetas_lv.iloc[:1]

,url,image_url,title,date,author,topics,text,matching_article_id,keywords
id,,,,,,,,,
0,https://pilsetas.lv/notikumi/astro-n-out-preze...,https://pilsetas.lv/pictures/users/uploaded/14...,Astro'n'out prezentē jaunu singlu un izziņo ak...,12:57 21.12.2025,RT Kompānija,"['Izklaide', 'Kultūra']","Краткое описание: Pavasara sezonu ieskandinot,...",NaN,NaN

In [12]:
!pip install nltk --q
import nltk

In [13]:
nltk.download('averaged_perceptron_tagger_rus')
nltk.download('maxent_ne_chunker_tab')

[nltk_data] Downloading package averaged_perceptron_tagger_rus to
[nltk_data]     C:\Users\Andy\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_rus is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package maxent_ne_chunker_tab to
[nltk_data]     C:\Users\Andy\AppData\Roaming\nltk_data...
[nltk_data]   Package maxent_ne_chunker_tab is already up-to-date!

True

In [14]:
# Source - https://stackoverflow.com/a/19495220
# Posted by user278064, modified by community. See post 'Timeline' for change history
# Retrieved 2026-03-07, License - CC BY-SA 3.0

from nltk import pos_tag, ne_chunk
from nltk.tokenize import SpaceTokenizer

tokenizer = SpaceTokenizer()
toks = tokenizer.tokenize(pilsetas_ru.loc[0, "text"])

pos = pos_tag(toks, lang="rus")
chunked_nes = ne_chunk(pos) 

nes = [' '.join(map(lambda x: x[0], ne.leaves())) for ne in chunked_nes if isinstance(ne, nltk.tree.Tree)]
print(len(chunked_nes))
for ne in chunked_nes:
    print(ne)
    if isinstance(ne, nltk.tree.Tree):
        print(ne)

453
('Персональная', 'A=f')
('выставка', 'S')
('Аниты', 'S')
('Паегле', 'S')
('в', 'PR')
('музее', 'S')
('Ояра', 'S')
('Вациетиса.\n\n4', 'S')
('сентября', 'S')
('в', 'PR')
('18:00', 'NUM=ciph')
('в', 'PR')
('музее', 'S')
('Ояра', 'S')
('Вациетиса', 'S')
('по', 'PR')
('адресу', 'S')
('улица', 'S')
('Ояра', 'S')
('Вациетиса', 'S')
('19,', 'NUM=ciph')
('Рига,', 'S')
('состоится', 'V')
('открытие', 'S')
('персональной', 'A=f')
('выставки', 'S')
('художницы', 'S')
('Аниты', 'S')
('Паегле', 'S')
('«Рига.', 'NONLEX')
('Осень.', 'S')
('Звезды.»', 'S')
('На', 'PR')
('выставке', 'S')
('представлены', 'V')
('иллюстрации', 'S')
('к', 'PR')
('книге', 'S')
('Мары', 'S')
('Циелене', 'S')
('«Улыбка', 'S')
('Сфинкса', 'S')
('Альберта»,', 'S')
('книгам', 'S')
('Юриса', 'S')
('Звиргздиня', 'S')
('«Зимняя', 'A=f')
('сказка»', 'S')
('и', 'CONJ')
('«Сказка', 'S')
('о', 'PR')
('сне»,', 'S')
('книге', 'S')
('Инесы', 'S')
('Зандере', 'S')
('«Кот', 'S')
('на', 'PR')
('клавишах»,', 'S')
('а', 'CONJ')
('также', 'ADV')
('важные', 'A=pl')
('и', 'CONJ')
('любимые', 'A=pl')
('вещи', 'S')
('самой', 'A-PRO=f')
('художницы,', 'NONLEX')
('которые', 'A-PRO=pl')
('служили', 'V')
('источником', 'S')
('вдохновения', 'S')
('при', 'PR')
('создании', 'S')
('работ.\n«Выставка', 'S')
('будет', 'V')
('разговором', 'S')
('со', 'PR')
('зрителем', 'S')
('как', 'CONJ')
('в', 'PR')
('мыслях,', 'S')
('так', 'ADV-PRO')
('и', 'CONJ')
('лично.', 'S')
('Она', 'S-PRO')
('подобна', 'A=f')
('прогулке', 'S')
('по', 'PR')
('городу', 'S')
('–', 'NONLEX')
('от', 'PR')
('Зиедоньдарза,', 'S')
('по', 'PR')
('улице', 'S')
('Чака,', 'S')
('мимо', 'PR')
('таинственных', 'A=pl')
('домов', 'S')
('на', 'PR')
('улице', 'S')
('Альберта', 'S')
('к', 'PR')
('тихим', 'A=pl')
('улочкам', 'S')
('Пардогавы.', 'S')
('Первые', 'ANUM=pl')
('звезды', 'S')
('мы', 'S-PRO')
('увидим', 'V')
('как', 'CONJ')
('на', 'PR')
('иллюстрации', 'S')
('с', 'PR')
('прудом', 'S')
('Мары', 'S')
('из', 'PR')
('книги', 'S')
('Юриса', 'S')
('Звиргздиня', 'S')
('«Сказка', 'S')
('о', 'PR')
('сне»,', 'S')
('так', 'ADV-PRO')
('и', 'CONJ')
('на', 'PR')
('иллюстрации', 'S')
('к', 'PR')
('книге', 'S')
('Инесы', 'S')
('Зандере', 'S')
('«Кот', 'S')
('на', 'PR')
('клавишах».', 'S')
('Это', 'S-PRO')
('воспоминания,', 'S')
('приключения,', 'S')
('тоска,', 'S')
('ведь', 'PART')
('в', 'PR')
('иллюстрациях', 'S')
('время', 'S')
('остановилось»,', 'S')
('–', 'S')
('рассказывает', 'V')
('художница.\nАнита', 'S')
('Паегле', 'S')
('–', 'NONLEX')
('классик', 'S')
('латвийской', 'A=f')
('иллюстрации,', 'S')
('близкая', 'A=f')
('и', 'CONJ')
('дорогая', 'A=f')
('не', 'PART')
('одному', 'A-PRO=n')
('поколению', 'S')
('читателей.', 'S')
('Родилась', 'V')
('в', 'PR')
('1956', 'NUM=ciph')
('году', 'S')
('в', 'PR')
('Риге.', 'S')
('Окончила', 'V')
('Рижскую', 'A=f')
('художественную', 'A=f')
('среднюю', 'A=f')
('школу', 'S')
('имени', 'S')
('Яниса', 'S')
('Розентала', 'S')
('и', 'CONJ')
('графический', 'A=m')
('факультет', 'S')
('Латвийской', 'A=f')
('академии', 'S')
('художеств.', 'S')
('С', 'PR')
('1981', 'NUM=ciph')
('года,', 'S')
('когда', 'ADV-PRO')
('началось', 'V')
('сотрудничество', 'S')
('художницы', 'S')
('с', 'PR')
('издательством', 'S')
('«Лиесма»,', 'S')
('а', 'CONJ')
('позже', 'ADV=comp')
('с', 'PR')
('издательствами', 'S')
('«Спридитис»,', 'S')
('«Гара', 'S')
('Пупа»,', 'S')
('«Яня', 'NONLEX')
('Сета»,', 'S')
('Анита', 'S')
('Паегле', 'S')
('последовательно', 'ADV')
('развивает', 'V')
('свой', 'A-PRO=m')
('уникальный', 'A=m')
('и', 'CONJ')
('неповторимый', 'A=m')
('стиль', 'S')
('иллюстрации.', 'S')
('В', 'PR')
('целом', 'S')
('она', 'S-PRO')
('иллюстрировала', 'V')
('более', 'NUM=comp')
('35', 'NUM=ciph')
('книг', 'S')
('как', 'CONJ')
('для', 'PR')
('детей,', 'S')
('так', 'ADV-PRO')
('и', 'CONJ')
('для', 'PR')
('взрослых,', 'S')
('среди', 'PR')
('которых', 'A-PRO=pl')
('значительное', 'A=n')
('место', 'S')
('занимают', 'V')
('оригинальные', 'A=pl')
('произведения', 'S')
('Мары', 'S')
('Циелене', 'S')
('и', 'CONJ')
('Яниса', 'S')
('Балтавилкса.', 'S')
('Анита', 'S')
('Паегле', 'S')
('является', 'V')
('одной', 'A-PRO=f')
('из', 'PR')
('основательниц', 'S')
('премии', 'S')
('Яниса', 'S')
('Балтавилка,', 'S')
('иллюстрировала', 'V')
('любимые', 'A=pl')
('детские', 'A=pl')
('журналы', 'S')
('«Зилите»', 'S')
('и', 'CONJ')
('«Эзис».', 'S')
('Участвовала', 'V')
('в', 'PR')
('III', 'ANUM=ciph')
('и', 'CONJ')
('IV', 'ANUM=ciph')
('Международной', 'A=f')
('триеннале', 'S')
('книжной', 'A=f')
('графики', 'S')
('в', 'PR')
('Вильнюсе,', 'S')
('биенналях', 'S')
('иллюстрации', 'S')
('в', 'PR')
('Братиславе', 'S')
('в', 'PR')
('1999', 'NUM=ciph')
('и', 'CONJ')
('2001', 'NUM=ciph')
('годах,', 'S')
('Европейской', 'A=f')
('биеннале', 'S')
('иллюстрации', 'S')
('в', 'PR')
('Японии', 'S')
('(2001)', 'NONLEX')
('и', 'CONJ')
('I,', 'NONLEX')
('II', 'ANUM=ciph')
('и', 'CONJ')
('III', 'ANUM=ciph')
('Таллинской', 'A=f')
('триеннале', 'S')
('иллюстрации', 'S')
('в', 'PR')
('Эстонии,', 'S')
('где', 'ADV-PRO')
('в', 'PR')
('2003', 'NUM=ciph')
('году', 'S')
('получила', 'V')
('диплом', 'S')
('за', 'PR')
('иллюстрации', 'S')
('к', 'PR')
('книге', 'S')
('М.', 'S')
('Циелене', 'S')
('«Когда', 'CONJ')
('королева', 'S')
('была', 'V')
('в', 'PR')
('Риге».', 'S')
('У', 'PR')
('художницы', 'S')
('были', 'V')
('персональные', 'A=pl')
('выставки', 'S')
('в', 'PR')
('Латвии,', 'S')
('Франции,', 'S')
('Польше,', 'S')
('Италии,', 'S')
('Чехии', 'S')
('и', 'CONJ')
('России.', 'S')
('Анита', 'S')
('Паегле', 'S')
('создала', 'V')
('графический', 'A=m')
('дизайн', 'S')
('для', 'PR')
('двух', 'NUM=f')
('монет,', 'S')
('выпущенных', 'V')
('Банком', 'S')
('Латвии', 'S')
('–', 'S')
('«Монета', 'S')
('люльки»', 'S')
('(Монета', 'NONLEX')
('года', 'S')
('Латвии', 'S')
('2013)', 'NUM=ciph')
('и', 'CONJ')
('«Сказочная', 'A=f')
('монета', 'S')
('I.', 'NONLEX')
('Пять', 'NUM=nom')
('котов»', 'S')
('(Монета', 'NONLEX')
('года', 'S')
('Латвии', 'S')
('2015).\nЗа', 'NUM=ciph')
('свои', 'A-PRO=pl')
('иллюстрации', 'S')
('к', 'PR')
('детским', 'A=pl')
('книгам', 'S')
('Анита', 'S')
('Паегле', 'S')
('получила', 'V')
('множество', 'S')
('признаний', 'S')
('и', 'CONJ')
('наград', 'S')
('–', 'NONLEX')
('Весеннюю', 'A=f')
('премию', 'S')
('и', 'CONJ')
('премию', 'S')
('Пастариньша,', 'S')
('1-ю', 'ANUM=f')
('премию', 'S')
('в', 'PR')
('конкурсе', 'S')
('книжного', 'A=n')
('искусства', 'S')
('«Золотое', 'NONLEX')
('яблоко»', 'S')
('2005', 'NUM=ciph')
('и', 'CONJ')
('премию', 'S')
('Индрика', 'S')
('Зебериня,', 'S')
('награды', 'S')
('в', 'PR')
('конкурсе', 'S')
('«Красивейшие', 'NONLEX')
('книги', 'S')
('Балтии».', 'S')
('В', 'PR')
('2000', 'NUM=ciph')
('году', 'S')
('за', 'PR')
('иллюстрации', 'S')
('к', 'PR')
('книге', 'S')
('Мары', 'S')
('Циелене', 'S')
('«Ночные', 'A=pl')
('ходы', 'S')
('часов»', 'S')
('Анита', 'S')
('Паегле', 'S')
('была', 'V')
('включена', 'V')
('в', 'PR')
('почетный', 'A=m')
('список', 'S')
('иллюстраторов', 'S')
('мира', 'S')
('IBBY.', 'NONLEX')
('За', 'PR')
('вклад', 'S')
('в', 'PR')
('развитие', 'S')
('искусства', 'S')
('детской', 'A=f')
('книги', 'S')
('в', 'PR')
('2005', 'NUM=ciph')
('году', 'S')
('художница', 'S')
('получила', 'V')
('премию', 'S')
('Балтавилкса.', 'S')
('Художница', 'S')
('номинировалась', 'V')
('на', 'PR')
('высшую', 'A=f')
('международную', 'A=f')
('награду', 'S')
('в', 'PR')
('области', 'S')
('детской', 'A=f')
('литературы', 'S')
('и', 'CONJ')
('иллюстрации', 'S')
('–', 'S')
('премию', 'S')
('Ханса', 'S')
('Кристиана', 'S')
('Андерсена', 'S')
('(2012,', 'NONLEX')
('2016)', 'NUM=ciph')
('и', 'CONJ')
('получила', 'V')
('премию', 'S')
('Латвийской', 'A=f')
('академии', 'S')
('художеств', 'S')
('за', 'PR')
('выдающиеся', 'A=pl')
('достижения', 'S')
('(2014).\nВыставка', 'S')
('в', 'PR')
('музее', 'S')
('будет', 'V')
('открыта', 'V')
('с', 'PR')
('4', 'NUM=ciph')
('августа', 'S')
('по', 'PR')
('25', 'NUM=ciph')
('октября.', 'S')

In [15]:
pilsetas_ru.loc[0, "text"]

'Персональная выставка Аниты Паегле в музее Ояра Вациетиса.\n\n4 сентября в 18:00 в музее Ояра Вациетиса по адресу улица Ояра Вациетиса 19, Рига, состоится открытие персональной выставки художницы Аниты Паегле «Рига. Осень. Звезды.» На выставке представлены иллюстрации к книге Мары Циелене «Улыбка Сфинкса Альберта», книгам Юриса Звиргздиня «Зимняя сказка» и «Сказка о сне», книге Инесы Зандере «Кот на клавишах», а также важные и любимые вещи самой художницы, которые служили источником вдохновения при создании работ.\n«Выставка будет разговором со зрителем как в мыслях, так и лично. Она подобна прогулке по городу – от Зиедоньдарза, по улице Чака, мимо таинственных домов на улице Альберта к тихим улочкам Пардогавы. Первые звезды мы увидим как на иллюстрации с прудом Мары из книги Юриса Звиргздиня «Сказка о сне», так и на иллюстрации к книге Инесы Зандере «Кот на клавишах». Это воспоминания, приключения, тоска, ведь в иллюстрациях время остановилось», – рассказывает художница.\nАнита Паегле – классик латвийской иллюстрации, близкая и дорогая не одному поколению читателей. Родилась в 1956 году в Риге. Окончила Рижскую художественную среднюю школу имени Яниса Розентала и графический факультет Латвийской академии художеств. С 1981 года, когда началось сотрудничество художницы с издательством «Лиесма», а позже с издательствами «Спридитис», «Гара Пупа», «Яня Сета», Анита Паегле последовательно развивает свой уникальный и неповторимый стиль иллюстрации. В целом она иллюстрировала более 35 книг как для детей, так и для взрослых, среди которых значительное место занимают оригинальные произведения Мары Циелене и Яниса Балтавилкса. Анита Паегле является одной из основательниц премии Яниса Балтавилка, иллюстрировала любимые детские журналы «Зилите» и «Эзис». Участвовала в III и IV Международной триеннале книжной графики в Вильнюсе, биенналях иллюстрации в Братиславе в 1999 и 2001 годах, Европейской биеннале иллюстрации в Японии (2001) и I, II и III Таллинской триеннале иллюстрации в Эстонии, где в 2003 году получила диплом за иллюстрации к книге М. Циелене «Когда королева была в Риге». У художницы были персональные выставки в Латвии, Франции, Польше, Италии, Чехии и России. Анита Паегле создала графический дизайн для двух монет, выпущенных Банком Латвии – «Монета люльки» (Монета года Латвии 2013) и «Сказочная монета I. Пять котов» (Монета года Латвии 2015).\nЗа свои иллюстрации к детским книгам Анита Паегле получила множество признаний и наград – Весеннюю премию и премию Пастариньша, 1-ю премию в конкурсе книжного искусства «Золотое яблоко» 2005 и премию Индрика Зебериня, награды в конкурсе «Красивейшие книги Балтии». В 2000 году за иллюстрации к книге Мары Циелене «Ночные ходы часов» Анита Паегле была включена в почетный список иллюстраторов мира IBBY. За вклад в развитие искусства детской книги в 2005 году художница получила премию Балтавилкса. Художница номинировалась на высшую международную награду в области детской литературы и иллюстрации – премию Ханса Кристиана Андерсена (2012, 2016) и получила премию Латвийской академии художеств за выдающиеся достижения (2014).\nВыставка в музее будет открыта с 4 августа по 25 октября.'

In [16]:
!pip install spacy --q
import spacy
# Import graphing package
!pip install plotly --q
import plotly.graph_objects as go
import plotly.express as px
# Load spaCy visualizer
from spacy import displacy

In [17]:
# metadata_pilsetas_ru
!python.exe -m spacy download ru_core_news_lg

Collecting ru-core-news-lg==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/ru_core_news_lg-3.8.0/ru_core_news_lg-3.8.0-py3-none-any.whl (513.4 MB)
     ---------------------------------------- 0.0/513.4 MB ? eta -:--:--
     ---------------------------------------- 0.0/513.4 MB ? eta -:--:--
     ---------------------------------------- 0.0/513.4 MB ? eta -:--:--
     ---------------------------------------- 0.3/513.4 MB ? eta -:--:--
     ---------------------------------------- 0.3/513.4 MB ? eta -:--:--
     -------------------------------------- 0.5/513.4 MB 694.3 kB/s eta 0:12:19
     -------------------------------------- 0.8/513.4 MB 858.5 kB/s eta 0:09:58
     -------------------------------------- 0.8/513.4 MB 858.5 kB/s eta 0:09:58
     -------------------------------------- 1.3/513.4 MB 986.6 kB/s eta 0:08:40
     ---------------------------------------- 1.6/513.4 MB 1.1 MB/s eta 0:08:07
     ---------------------------------------- 1.8/513.4 MB 1.1 MB/s eta 0:08:04
     ---------------------------------------- 1.8/513.4 MB 1.1 MB/s eta 0:08:04
     ---------------------------------------- 1.8/513.4 MB 1.1 MB/s eta 0:08:04
     -------------------------------------- 2.4/513.4 MB 977.9 kB/s eta 0:08:43
     ---------------------------------------- 2.6/513.4 MB 1.0 MB/s eta 0:08:21
     ---------------------------------------- 2.9/513.4 MB 1.1 MB/s eta 0:07:57
     ---------------------------------------- 3.1/513.4 MB 1.1 MB/s eta 0:07:41
     ---------------------------------------- 3.4/513.4 MB 1.1 MB/s eta 0:07:42
     ---------------------------------------- 3.4/513.4 MB 1.1 MB/s eta 0:07:42
     ---------------------------------------- 3.7/513.4 MB 1.1 MB/s eta 0:07:59
     ---------------------------------------- 3.9/513.4 MB 1.1 MB/s eta 0:07:56
     ---------------------------------------- 4.2/513.4 MB 1.0 MB/s eta 0:08:10
     ---------------------------------------- 4.2/513.4 MB 1.0 MB/s eta 0:08:10
     ---------------------------------------- 4.5/513.4 MB 1.0 MB/s eta 0:08:12
     ---------------------------------------- 4.5/513.4 MB 1.0 MB/s eta 0:08:12
     ---------------------------------------- 5.0/513.4 MB 1.0 MB/s eta 0:08:15
     ---------------------------------------- 5.2/513.4 MB 1.0 MB/s eta 0:08:08
     ---------------------------------------- 5.5/513.4 MB 1.1 MB/s eta 0:08:01
     ---------------------------------------- 5.5/513.4 MB 1.1 MB/s eta 0:08:01
     ---------------------------------------- 5.5/513.4 MB 1.1 MB/s eta 0:08:01
     ---------------------------------------- 5.5/513.4 MB 1.1 MB/s eta 0:08:01
     ---------------------------------------- 6.3/513.4 MB 1.0 MB/s eta 0:08:17
     ---------------------------------------- 6.3/513.4 MB 1.0 MB/s eta 0:08:17
      --------------------------------------- 6.6/513.4 MB 1.0 MB/s eta 0:08:19
      --------------------------------------- 6.6/513.4 MB 1.0 MB/s eta 0:08:19
      --------------------------------------- 6.6/513.4 MB 1.0 MB/s eta 0:08:19
      --------------------------------------- 6.6/513.4 MB 1.0 MB/s eta 0:08:19
      --------------------------------------- 6.6/513.4 MB 1.0 MB/s eta 0:08:19
      ------------------------------------- 6.8/513.4 MB 909.3 kB/s eta 0:09:18
      ------------------------------------- 6.8/513.4 MB 909.3 kB/s eta 0:09:18
      ------------------------------------- 6.8/513.4 MB 909.3 kB/s eta 0:09:18
      ------------------------------------- 6.8/513.4 MB 909.3 kB/s eta 0:09:18
      ------------------------------------- 6.8/513.4 MB 909.3 kB/s eta 0:09:18
      ------------------------------------- 7.1/513.4 MB 819.9 kB/s eta 0:10:18
      ------------------------------------- 7.1/513.4 MB 819.9 kB/s eta 0:10:18
      ------------------------------------- 7.1/513.4 MB 819.9 kB/s eta 0:10:18
      ------------------------------------- 7.1/513.4 MB 819.9 kB/s eta 0:10:18
      ------------------------------------- 7.1/513.4 MB 819.9 kB/s eta 0:10:18
      ------------------------------------- 7.6/513.4 MB 783.5 kB/s eta 0:10:46
      ------------------------------------- 8.4/513.4 MB 840.5 kB/s eta 0:10:01
      ------------------------------------- 8.7/513.4 MB 856.6 kB/s eta 0:09:50
      ------------------------------------- 9.2/513.4 MB 888.8 kB/s eta 0:09:28
      ------------------------------------- 9.7/513.4 MB 919.7 kB/s eta 0:09:08
      ------------------------------------ 10.0/513.4 MB 924.6 kB/s eta 0:09:05
      ------------------------------------ 10.2/513.4 MB 931.1 kB/s eta 0:09:01
      ------------------------------------ 10.2/513.4 MB 931.1 kB/s eta 0:09:01
      ------------------------------------ 10.2/513.4 MB 931.1 kB/s eta 0:09:01
      ------------------------------------ 10.7/513.4 MB 928.3 kB/s eta 0:09:02
      ------------------------------------ 11.0/513.4 MB 934.1 kB/s eta 0:08:58
      ------------------------------------ 11.3/513.4 MB 946.3 kB/s eta 0:08:51
      ------------------------------------ 11.3/513.4 MB 946.3 kB/s eta 0:08:51
      ------------------------------------ 11.8/513.4 MB 956.8 kB/s eta 0:08:45
      ------------------------------------ 12.1/513.4 MB 952.5 kB/s eta 0:08:47
      ------------------------------------ 12.1/513.4 MB 952.5 kB/s eta 0:08:47
      ------------------------------------ 12.6/513.4 MB 970.6 kB/s eta 0:08:36
      ------------------------------------ 13.1/513.4 MB 985.2 kB/s eta 0:08:28
      ------------------------------------ 13.4/513.4 MB 998.1 kB/s eta 0:08:21
     - ------------------------------------- 13.9/513.4 MB 1.0 MB/s eta 0:08:12
     - ------------------------------------- 14.2/513.4 MB 1.0 MB/s eta 0:08:07
     - ------------------------------------- 14.4/513.4 MB 1.0 MB/s eta 0:08:08
     - ------------------------------------- 14.4/513.4 MB 1.0 MB/s eta 0:08:08
     - ------------------------------------- 14.4/513.4 MB 1.0 MB/s eta 0:08:08
     - ------------------------------------- 14.4/513.4 MB 1.0 MB/s eta 0:08:08
     - ------------------------------------- 15.5/513.4 MB 1.0 MB/s eta 0:08:01
     - ------------------------------------- 15.5/513.4 MB 1.0 MB/s eta 0:08:01
     - ------------------------------------- 15.5/513.4 MB 1.0 MB/s eta 0:08:01
     - ------------------------------------- 15.5/513.4 MB 1.0 MB/s eta 0:08:01
     - ------------------------------------- 15.5/513.4 MB 1.0 MB/s eta 0:08:01
     - ------------------------------------- 16.3/513.4 MB 1.0 MB/s eta 0:08:06
     - ------------------------------------- 16.3/513.4 MB 1.0 MB/s eta 0:08:06
     - ------------------------------------- 16.5/513.4 MB 1.0 MB/s eta 0:08:13
     - ------------------------------------- 16.5/513.4 MB 1.0 MB/s eta 0:08:13
     - ------------------------------------- 16.8/513.4 MB 1.0 MB/s eta 0:08:17
     - ------------------------------------- 16.8/513.4 MB 1.0 MB/s eta 0:08:17
     - ------------------------------------- 16.8/513.4 MB 1.0 MB/s eta 0:08:17
     - ------------------------------------- 16.8/513.4 MB 1.0 MB/s eta 0:08:17
     - ------------------------------------- 16.8/513.4 MB 1.0 MB/s eta 0:08:17
     - ----------------------------------- 17.6/513.4 MB 983.9 kB/s eta 0:08:24
     - ----------------------------------- 17.6/513.4 MB 983.9 kB/s eta 0:08:24
     - ----------------------------------- 17.6/513.4 MB 983.9 kB/s eta 0:08:24
     - ----------------------------------- 17.6/513.4 MB 983.9 kB/s eta 0:08:24
     - ----------------------------------- 17.6/513.4 MB 983.9 kB/s eta 0:08:24
     - ----------------------------------- 18.4/513.4 MB 968.7 kB/s eta 0:08:31
     - ----------------------------------- 18.4/513.4 MB 968.7 kB/s eta 0:08:31
     - ----------------------------------- 18.6/513.4 MB 968.8 kB/s eta 0:08:31
     - ----------------------------------- 18.9/513.4 MB 973.9 kB/s eta 0:08:28
     - ----------------------------------- 19.1/513.4 MB 978.1 kB/s eta 0:08:26
     - ----------------------------------- 19.4/513.4 MB 977.1 kB/s eta 0:08:26
     - ----------------------------------- 19.4/513.4 MB 977.1 kB/s eta 0:08:26
     - ------------------------------------- 20.4/513.4 MB 1.0 MB/s eta 0:08:12
     - ------------------------------------- 20.4/513.4 MB 1.0 MB/s eta 0:08:12
     - ------------------------------------- 20.4/513.4 MB 1.0 MB/s eta 0:08:12
     - ----------------------------------- 20.7/513.4 MB 987.0 kB/s eta 0:08:20
     - ----------------------------------- 21.0/513.4 MB 992.5 kB/s eta 0:08:17
     - ----------------------------------- 21.2/513.4 MB 990.4 kB/s eta 0:08:17
     - ----------------------------------- 21.5/513.4 MB 995.1 kB/s eta 0:08:15
     - ------------------------------------- 21.8/513.4 MB 1.0 MB/s eta 0:08:12
     - ------------------------------------- 21.8/513.4 MB 1.0 MB/s eta 0:08:12
     - ----------------------------------- 22.0/513.4 MB 995.8 kB/s eta 0:08:14
     - ------------------------------------- 22.5/513.4 MB 1.0 MB/s eta 0:08:09
     - ------------------------------------- 23.1/513.4 MB 1.0 MB/s eta 0:08:02
     - ------------------------------------- 23.1/513.4 MB 1.0 MB/s eta 0:08:02
     - ------------------------------------- 23.1/513.4 MB 1.0 MB/s eta 0:08:02
     - ------------------------------------- 24.1/513.4 MB 1.0 MB/s eta 0:07:54
     - ------------------------------------- 24.4/513.4 MB 1.0 MB/s eta 0:07:51
     - ------------------------------------- 24.9/513.4 MB 1.1 MB/s eta 0:07:45
     - ------------------------------------- 25.2/513.4 MB 1.1 MB/s eta 0:07:44
     - ------------------------------------- 25.7/513.4 MB 1.1 MB/s eta 0:07:38
     - ------------------------------------- 26.0/513.4 MB 1.1 MB/s eta 0:07:37
     -- ------------------------------------ 26.5/513.4 MB 1.1 MB/s eta 0:07:32
     -- ------------------------------------ 27.0/513.4 MB 1.1 MB/s eta 0:07:26
     -- ------------------------------------ 27.5/513.4 MB 1.1 MB/s eta 0:07:22
     -- ------------------------------------ 28.0/513.4 MB 1.1 MB/s eta 0:07:17
     -- ------------------------------------ 28.0/513.4 MB 1.1 MB/s eta 0:07:17
     -- ------------------------------------ 28.6/513.4 MB 1.1 MB/s eta 0:07:14
     -- ------------------------------------ 29.1/513.4 MB 1.1 MB/s eta 0:07:09
     -- ------------------------------------ 29.6/513.4 MB 1.1 MB/s eta 0:07:04
     -- ------------------------------------ 30.4/513.4 MB 1.2 MB/s eta 0:06:58
     -- ------------------------------------ 30.7/513.4 MB 1.2 MB/s eta 0:06:55
     -- ------------------------------------ 31.5/513.4 MB 1.2 MB/s eta 0:06:49
     -- ------------------------------------ 31.7/513.4 MB 1.2 MB/s eta 0:06:47
     -- ------------------------------------ 32.8/513.4 MB 1.2 MB/s eta 0:06:38
     -- ------------------------------------ 33.3/513.4 MB 1.2 MB/s eta 0:06:33
     -- ------------------------------------ 33.8/513.4 MB 1.2 MB/s eta 0:06:29
     -- ------------------------------------ 33.8/513.4 MB 1.2 MB/s eta 0:06:29
     -- ------------------------------------ 34.9/513.4 MB 1.2 MB/s eta 0:06:23
     -- ------------------------------------ 35.4/513.4 MB 1.3 MB/s eta 0:06:21
     -- ------------------------------------ 35.7/513.4 MB 1.3 MB/s eta 0:06:19
     -- ------------------------------------ 35.7/513.4 MB 1.3 MB/s eta 0:06:19
     -- ------------------------------------ 35.7/513.4 MB 1.3 MB/s eta 0:06:19
     -- ------------------------------------ 36.7/513.4 MB 1.3 MB/s eta 0:06:15
     -- ------------------------------------ 37.0/513.4 MB 1.3 MB/s eta 0:06:14
     -- ------------------------------------ 37.7/513.4 MB 1.3 MB/s eta 0:06:10
     -- ------------------------------------ 38.5/513.4 MB 1.3 MB/s eta 0:06:05
     -- ------------------------------------ 39.1/513.4 MB 1.3 MB/s eta 0:06:02
     -- ------------------------------------ 39.1/513.4 MB 1.3 MB/s eta 0:06:02
     --- ----------------------------------- 39.8/513.4 MB 1.3 MB/s eta 0:05:58
     --- ----------------------------------- 40.1/513.4 MB 1.3 MB/s eta 0:05:56
     --- ----------------------------------- 40.9/513.4 MB 1.3 MB/s eta 0:05:52
     --- ----------------------------------- 41.4/513.4 MB 1.4 MB/s eta 0:05:49
     --- ----------------------------------- 41.9/513.4 MB 1.4 MB/s eta 0:05:46
     --- ----------------------------------- 42.2/513.4 MB 1.4 MB/s eta 0:05:45
     --- ----------------------------------- 43.3/513.4 MB 1.4 MB/s eta 0:05:38
     --- ----------------------------------- 44.0/513.4 MB 1.4 MB/s eta 0:05:30
     --- ----------------------------------- 44.6/513.4 MB 1.4 MB/s eta 0:05:26
     --- ----------------------------------- 44.6/513.4 MB 1.4 MB/s eta 0:05:26
     --- ----------------------------------- 45.4/513.4 MB 1.4 MB/s eta 0:05:26
     --- ----------------------------------- 46.4/513.4 MB 1.5 MB/s eta 0:05:21
     --- ----------------------------------- 46.7/513.4 MB 1.5 MB/s eta 0:05:20
     --- ----------------------------------- 47.4/513.4 MB 1.5 MB/s eta 0:05:17
     --- ----------------------------------- 48.0/513.4 MB 1.5 MB/s eta 0:05:13
     --- ----------------------------------- 48.5/513.4 MB 1.5 MB/s eta 0:05:11
     --- ----------------------------------- 49.3/513.4 MB 1.5 MB/s eta 0:05:07
     --- ----------------------------------- 49.8/513.4 MB 1.5 MB/s eta 0:05:02
     --- ----------------------------------- 50.9/513.4 MB 1.6 MB/s eta 0:04:57
     --- ----------------------------------- 51.1/513.4 MB 1.6 MB/s eta 0:04:56
     --- ----------------------------------- 52.2/513.4 MB 1.6 MB/s eta 0:04:48
     --- ----------------------------------- 52.2/513.4 MB 1.6 MB/s eta 0:04:48
     ---- ---------------------------------- 53.5/513.4 MB 1.6 MB/s eta 0:04:43
     ---- ---------------------------------- 54.3/513.4 MB 1.6 MB/s eta 0:04:42
     ---- ---------------------------------- 54.5/513.4 MB 1.6 MB/s eta 0:04:41
     ---- ---------------------------------- 55.6/513.4 MB 1.7 MB/s eta 0:04:32
     ---- ---------------------------------- 55.8/513.4 MB 1.7 MB/s eta 0:04:31
     ---- ---------------------------------- 57.1/513.4 MB 1.7 MB/s eta 0:04:26
     ---- ---------------------------------- 57.7/513.4 MB 1.7 MB/s eta 0:04:26
     ---- ---------------------------------- 58.2/513.4 MB 1.7 MB/s eta 0:04:24
     ---- ---------------------------------- 58.2/513.4 MB 1.7 MB/s eta 0:04:24
     ---- ---------------------------------- 59.0/513.4 MB 1.8 MB/s eta 0:04:16
     ---- ---------------------------------- 59.8/513.4 MB 1.8 MB/s eta 0:04:14
     ---- ---------------------------------- 60.0/513.4 MB 1.8 MB/s eta 0:04:14
     ---- ---------------------------------- 60.0/513.4 MB 1.8 MB/s eta 0:04:14
     ---- ---------------------------------- 60.0/513.4 MB 1.8 MB/s eta 0:04:14
     ---- ---------------------------------- 61.6/513.4 MB 1.9 MB/s eta 0:04:03
     ---- ---------------------------------- 62.4/513.4 MB 1.9 MB/s eta 0:04:01
     ---- ---------------------------------- 62.9/513.4 MB 1.9 MB/s eta 0:04:00
     ---- ---------------------------------- 64.0/513.4 MB 1.9 MB/s eta 0:03:57
     ---- ---------------------------------- 64.0/513.4 MB 1.9 MB/s eta 0:03:57
     ---- ---------------------------------- 65.5/513.4 MB 2.0 MB/s eta 0:03:46
     ---- ---------------------------------- 65.5/513.4 MB 2.0 MB/s eta 0:03:46
     ---- ---------------------------------- 65.5/513.4 MB 2.0 MB/s eta 0:03:46
     ----- --------------------------------- 66.8/513.4 MB 2.0 MB/s eta 0:03:45
     ----- --------------------------------- 67.4/513.4 MB 2.0 MB/s eta 0:03:44
     ----- --------------------------------- 67.4/513.4 MB 2.0 MB/s eta 0:03:44
     ----- --------------------------------- 67.4/513.4 MB 2.0 MB/s eta 0:03:44
     ----- --------------------------------- 68.9/513.4 MB 2.0 MB/s eta 0:03:45
     ----- --------------------------------- 69.2/513.4 MB 2.0 MB/s eta 0:03:44
     ----- --------------------------------- 69.7/513.4 MB 2.0 MB/s eta 0:03:43
     ----- --------------------------------- 70.5/513.4 MB 2.0 MB/s eta 0:03:38
     ----- --------------------------------- 71.3/513.4 MB 2.0 MB/s eta 0:03:36
     ----- --------------------------------- 72.1/513.4 MB 2.1 MB/s eta 0:03:34
     ----- --------------------------------- 72.1/513.4 MB 2.1 MB/s eta 0:03:34
     ----- --------------------------------- 72.1/513.4 MB 2.1 MB/s eta 0:03:34
     ----- --------------------------------- 72.1/513.4 MB 2.1 MB/s eta 0:03:34
     ----- --------------------------------- 72.1/513.4 MB 2.1 MB/s eta 0:03:34
     ----- --------------------------------- 72.1/513.4 MB 2.1 MB/s eta 0:03:34
     ----- --------------------------------- 74.7/513.4 MB 2.1 MB/s eta 0:03:30
     ----- --------------------------------- 75.2/513.4 MB 2.1 MB/s eta 0:03:29
     ----- --------------------------------- 75.5/513.4 MB 2.1 MB/s eta 0:03:30
     ----- --------------------------------- 75.5/513.4 MB 2.1 MB/s eta 0:03:30
     ----- --------------------------------- 75.5/513.4 MB 2.1 MB/s eta 0:03:30
     ----- --------------------------------- 76.8/513.4 MB 2.1 MB/s eta 0:03:29
     ----- --------------------------------- 77.3/513.4 MB 2.1 MB/s eta 0:03:28
     ----- --------------------------------- 77.3/513.4 MB 2.1 MB/s eta 0:03:28
     ----- --------------------------------- 77.3/513.4 MB 2.1 MB/s eta 0:03:28
     ----- --------------------------------- 77.3/513.4 MB 2.1 MB/s eta 0:03:28
     ----- --------------------------------- 77.9/513.4 MB 2.1 MB/s eta 0:03:27
     ----- --------------------------------- 78.9/513.4 MB 2.1 MB/s eta 0:03:23
     ----- --------------------------------- 78.9/513.4 MB 2.1 MB/s eta 0:03:23
     ----- --------------------------------- 78.9/513.4 MB 2.1 MB/s eta 0:03:23
     ----- --------------------------------- 78.9/513.4 MB 2.1 MB/s eta 0:03:23
     ------ -------------------------------- 79.7/513.4 MB 2.1 MB/s eta 0:03:23
     ------ -------------------------------- 79.7/513.4 MB 2.1 MB/s eta 0:03:23
     ------ -------------------------------- 82.1/513.4 MB 2.2 MB/s eta 0:03:18
     ------ -------------------------------- 82.3/513.4 MB 2.2 MB/s eta 0:03:16
     ------ -------------------------------- 82.8/513.4 MB 2.2 MB/s eta 0:03:16
     ------ -------------------------------- 83.4/513.4 MB 2.3 MB/s eta 0:03:09
     ------ -------------------------------- 83.6/513.4 MB 2.3 MB/s eta 0:03:09
     ------ -------------------------------- 83.6/513.4 MB 2.3 MB/s eta 0:03:09
     ------ -------------------------------- 84.1/513.4 MB 2.3 MB/s eta 0:03:10
     ------ -------------------------------- 84.7/513.4 MB 2.3 MB/s eta 0:03:10
     ------ -------------------------------- 85.2/513.4 MB 2.3 MB/s eta 0:03:05
     ------ -------------------------------- 85.5/513.4 MB 2.3 MB/s eta 0:03:05
     ------ -------------------------------- 86.5/513.4 MB 2.3 MB/s eta 0:03:04
     ------ -------------------------------- 86.8/513.4 MB 2.3 MB/s eta 0:03:04
     ------ -------------------------------- 86.8/513.4 MB 2.3 MB/s eta 0:03:04
     ------ -------------------------------- 86.8/513.4 MB 2.3 MB/s eta 0:03:04
     ------ -------------------------------- 87.8/513.4 MB 2.3 MB/s eta 0:03:05
     ------ -------------------------------- 88.1/513.4 MB 2.3 MB/s eta 0:03:05
     ------ -------------------------------- 88.1/513.4 MB 2.3 MB/s eta 0:03:05
     ------ -------------------------------- 88.3/513.4 MB 2.3 MB/s eta 0:03:05
     ------ -------------------------------- 88.9/513.4 MB 2.3 MB/s eta 0:03:03
     ------ -------------------------------- 89.1/513.4 MB 2.3 MB/s eta 0:03:03
     ------ -------------------------------- 89.9/513.4 MB 2.3 MB/s eta 0:03:01
     ------ -------------------------------- 89.9/513.4 MB 2.3 MB/s eta 0:03:01
     ------ -------------------------------- 91.2/513.4 MB 2.4 MB/s eta 0:03:00
     ------ -------------------------------- 91.5/513.4 MB 2.4 MB/s eta 0:02:59
     ------- ------------------------------- 92.8/513.4 MB 2.4 MB/s eta 0:02:56
     ------- ------------------------------- 93.1/513.4 MB 2.4 MB/s eta 0:02:56

In [18]:
nlp_ru = spacy.load('ru_core_news_lg')

print(nlp_ru.pipe_names)

['tok2vec', 'morphologizer', 'parser', 'attribute_ruler', 'lemmatizer', 'ner']

In [19]:
!python.exe -m spacy info

============================== Info about spaCy ==============================

spaCy version    3.8.11
Location         c:\Users\Andy\AndysProjects\Programming\2024_2025\2024-2-level-ctlr-admin\.venv\Lib\site-packages\spacy
Platform         Windows-11-10.0.26200-SP0
Python version   3.13.11
Pipelines        en_core_web_lg (3.8.0), ru_core_news_lg (3.8.0)

In [20]:
doc = nlp_ru(pilsetas_ru.loc[0, "text"])
for token in doc:
    print(token.text, token.pos_, token.ent_type_)

Персональная ADJ
выставка NOUN
Аниты PROPN PER
Паегле PROPN PER
в ADP
музее NOUN
Ояра PROPN PER
Вациетиса PROPN PER
. PUNCT


 SPACE
4 ADJ
сентября NOUN
в ADP
18:00 NUM
в ADP
музее NOUN
Ояра PROPN PER
Вациетиса PROPN PER
по ADP
адресу NOUN
улица NOUN
Ояра PROPN LOC
Вациетиса PROPN LOC
19 NUM
, PUNCT
Рига PROPN LOC
, PUNCT
состоится VERB
открытие NOUN
персональной ADJ
выставки NOUN
художницы NOUN
Аниты PROPN PER
Паегле PROPN PER
« PUNCT
Рига NOUN
. PUNCT
Осень NOUN
. PUNCT
Звезды NOUN
. PUNCT
» PUNCT
На ADP
выставке NOUN
представлены VERB
иллюстрации NOUN
к ADP
книге NOUN
Мары PROPN PER
Циелене PROPN PER
« PUNCT
Улыбка NOUN
Сфинкса PROPN
Альберта PROPN
» PUNCT
, PUNCT
книгам NOUN
Юриса PROPN PER
Звиргздиня PROPN PER
« PUNCT
Зимняя ADJ
сказка NOUN
» PUNCT
и CCONJ
« PUNCT
Сказка NOUN
о ADP
сне NOUN
» PUNCT
, PUNCT
книге NOUN
Инесы PROPN PER
Зандере PROPN PER
« PUNCT
Кот NOUN
на ADP
клавишах NOUN
» PUNCT
, PUNCT
а CCONJ
также ADV
важные ADJ
и CCONJ
любимые ADJ
вещи NOUN
самой ADJ
художницы NOUN
, PUNCT
которые PRON
служили VERB
источником NOUN
вдохновения NOUN
при ADP
создании NOUN
работ NOUN
. PUNCT

 SPACE
« PUNCT
Выставка NOUN
будет AUX
разговором NOUN
со ADP
зрителем NOUN
как SCONJ
в ADP
мыслях NOUN
, PUNCT
так ADV
и PART
лично ADV
. PUNCT
Она PRON
подобна ADJ
прогулке NOUN
по ADP
городу NOUN
– PUNCT
от ADP
Зиедоньдарза PROPN LOC
, PUNCT
по ADP
улице NOUN
Чака PROPN LOC
, PUNCT
мимо ADP
таинственных ADJ
домов NOUN
на ADP
улице NOUN
Альберта PROPN LOC
к ADP
тихим ADJ
улочкам NOUN
Пардогавы PROPN LOC
. PUNCT
Первые ADJ
звезды NOUN
мы PRON
увидим VERB
как SCONJ
на ADP
иллюстрации NOUN
с ADP
прудом NOUN
Мары PROPN LOC
из ADP
книги NOUN
Юриса PROPN PER
Звиргздиня PROPN PER
« PUNCT
Сказка NOUN
о ADP
сне NOUN
» PUNCT
, PUNCT
так ADV
и PART
на ADP
иллюстрации NOUN
к ADP
книге NOUN
Инесы PROPN PER
Зандере PROPN PER
« PUNCT
Кот NOUN
на ADP
клавишах NOUN
» PUNCT
. PUNCT
Это PRON
воспоминания NOUN
, PUNCT
приключения NOUN
, PUNCT
тоска NOUN
, PUNCT
ведь SCONJ
в ADP
иллюстрациях NOUN
время NOUN
остановилось VERB
» PUNCT
, PUNCT
– PUNCT
рассказывает VERB
художница NOUN
. PUNCT

 SPACE
Анита PROPN PER
Паегле PROPN PER
– PUNCT
классик NOUN
латвийской ADJ
иллюстрации NOUN
, PUNCT
близкая ADJ
и CCONJ
дорогая ADJ
не PART
одному NUM
поколению NOUN
читателей NOUN
. PUNCT
Родилась VERB
в ADP
1956 ADJ
году NOUN
в ADP
Риге PROPN LOC
. PUNCT
Окончила VERB
Рижскую ADJ ORG
художественную ADJ ORG
среднюю ADJ ORG
школу NOUN ORG
имени NOUN ORG
Яниса PROPN ORG
Розентала PROPN ORG
и CCONJ
графический ADJ
факультет NOUN
Латвийской ADJ ORG
академии NOUN ORG
художеств NOUN ORG
. PUNCT
С ADP
1981 ADJ
года NOUN
, PUNCT
когда ADV
началось VERB
сотрудничество NOUN
художницы NOUN
с ADP
издательством NOUN
« PUNCT
Лиесма PROPN ORG
» PUNCT
, PUNCT
а CCONJ
позже ADV
с ADP
издательствами NOUN
« PUNCT
Спридитис PROPN ORG
» PUNCT
, PUNCT
« PUNCT
Гара NOUN ORG
Пупа PROPN ORG
» PUNCT
, PUNCT
« PUNCT
Яня PROPN ORG
Сета PROPN ORG
» PUNCT
, PUNCT
Анита PROPN PER
Паегле PROPN PER
последовательно ADV
развивает VERB
свой DET
уникальный ADJ
и CCONJ
неповторимый ADJ
стиль NOUN
иллюстрации NOUN
. PUNCT
В ADP
целом NOUN
она PRON
иллюстрировала VERB
более ADV
35 NUM
книг NOUN
как SCONJ
для ADP
детей NOUN
, PUNCT
так ADV
и PART
для ADP
взрослых NOUN
, PUNCT
среди ADP
которых PRON
значительное ADJ
место NOUN
занимают VERB
оригинальные ADJ
произведения NOUN
Мары PROPN PER
Циелене PROPN PER
и CCONJ
Яниса PROPN PER
Балтавилкса PROPN PER
. PUNCT
Анита PROPN PER
Паегле PROPN PER
является VERB
одной NUM
из ADP
основательниц NOUN
премии NOUN
Яниса PROPN PER
Балтавилка PROPN PER
, PUNCT
иллюстрировала VERB
любимые ADJ
детские ADJ
журналы NOUN
« PUNCT
Зилите VERB ORG
» PUNCT
и CCONJ
« PUNCT
Эзис PROPN ORG
» PUNCT
. PUNCT
Участвовала VERB
в ADP
III ADJ
и CCONJ
IV ADJ
Международной ADJ
триеннале NOUN
книжной ADJ
графики NOUN
в ADP
Вильнюсе PROPN LOC
, PUNCT
биенналях NOUN
иллюстрации NOUN
в ADP
Братиславе PROPN LOC
в ADP
1999 ADJ
и CCONJ
2001 ADJ
годах NOUN
, PUNCT
Европейской ADJ
биеннале NOUN
иллюстрации NOUN
в ADP
Японии PROPN LOC
( PUNCT
2001 ADJ
) PUNCT
и CCONJ
I ADJ
, PUNCT
II ADJ
и CCONJ
III ADJ
Таллинской ADJ
триеннале NOUN
иллюстрации NOUN
в ADP
Эстонии PROPN LOC
, PUNCT
где ADV
в ADP
2003 ADJ
году NOUN
получила VERB
диплом NOUN
за ADP
иллюстрации NOUN
к ADP
книге NOUN
М. PROPN PER
Циелене PROPN PER
« PUNCT
Когда SCONJ
королева NOUN
была AUX
в ADP
Риге PROPN LOC
» PUNCT
. PUNCT
У ADP
художницы NOUN
были VERB
персональные ADJ
выставки NOUN
в ADP
Латвии PROPN LOC
, PUNCT
Франции PROPN LOC
, PUNCT
Польше PROPN LOC
, PUNCT
Италии PROPN LOC
, PUNCT
Чехии PROPN LOC
и CCONJ
России PROPN LOC
. PUNCT
Анита PROPN PER
Паегле PROPN PER
создала VERB
графический ADJ
дизайн NOUN
для ADP
двух NUM
монет NOUN
, PUNCT
выпущенных VERB
Банком PROPN ORG
Латвии PROPN ORG
– PUNCT
« PUNCT
Монета NOUN ORG
люльки NOUN ORG
» PUNCT
( PUNCT
Монета PROPN
года NOUN
Латвии PROPN LOC
2013 NUM
) PUNCT
и CCONJ
« PUNCT
Сказочная ADJ ORG
монета NOUN ORG
I. PUNCT ORG
Пять NUM ORG
котов NOUN ORG
» PUNCT ORG
( PUNCT
Монета PROPN
года NOUN
Латвии PROPN LOC
2015 ADJ
) PUNCT
. PUNCT

 SPACE
За ADP
свои DET
иллюстрации NOUN
к ADP
детским ADJ
книгам NOUN
Анита PROPN PER
Паегле PROPN PER
получила VERB
множество NOUN
признаний NOUN
и CCONJ
наград NOUN
– PUNCT
Весеннюю ADJ
премию NOUN
и CCONJ
премию NOUN
Пастариньша PROPN PER
, PUNCT
1-ю ADJ
премию NOUN
в ADP
конкурсе NOUN
книжного ADJ
искусства NOUN
« PUNCT
Золотое ADJ
яблоко NOUN
» PUNCT
2005 NUM
и CCONJ
премию NOUN
Индрика PROPN PER
Зебериня PROPN PER
, PUNCT
награды NOUN
в ADP
конкурсе NOUN
« PUNCT
Красивейшие VERB
книги NOUN
Балтии PROPN LOC
» PUNCT
. PUNCT
В ADP
2000 ADJ
году NOUN
за ADP
иллюстрации NOUN
к ADP
книге NOUN
Мары PROPN PER
Циелене PROPN PER
« PUNCT
Ночные ADJ
ходы NOUN
часов NOUN
» PUNCT
Анита PROPN PER
Паегле PROPN PER
была AUX
включена VERB
в ADP
почетный ADJ
список NOUN
иллюстраторов NOUN
мира NOUN
IBBY PROPN ORG
. PUNCT
За ADP
вклад NOUN
в ADP
развитие NOUN
искусства NOUN
детской ADJ
книги NOUN
в ADP
2005 ADJ
году NOUN
художница NOUN
получила VERB
премию NOUN
Балтавилкса PROPN PER
. PUNCT
Художница NOUN
номинировалась VERB
на ADP
высшую ADJ
международную ADJ
награду NOUN
в ADP
области NOUN
детской ADJ
литературы NOUN
и CCONJ
иллюстрации NOUN
– PUNCT
премию NOUN
Ханса PROPN PER
Кристиана PROPN PER
Андерсена PROPN PER
( PUNCT
2012 ADJ
, ADJ
2016 NUM
) PUNCT
и CCONJ
получила VERB
премию NOUN
Латвийской ADJ ORG
академии NOUN ORG
художеств NOUN ORG
за ADP
выдающиеся ADJ
достижения NOUN
( PUNCT
2014 ADJ
) PUNCT
. PUNCT

 SPACE
Выставка NOUN
в ADP
музее NOUN
будет AUX
открыта VERB
с ADP
4 ADJ
августа NOUN
по ADP
25 ADJ
октября NOUN
. PUNCT

In [21]:
def process_ru(text):
    return nlp_ru(text)

In [22]:
def get_token(doc):
    return [(token.text) for token in doc]

In [96]:
labels_ru = nlp_ru.get_pipe("ner").labels

for label in labels_ru:
    print(label + ' : ' + spacy.explain(label))

def extract_named_entities_labels(doc):
    return [ent.label_ for ent in doc.ents]

LOC : Non-GPE locations, mountain ranges, bodies of water
ORG : Companies, agencies, institutions, etc.
PER : Named person or family.

In [ ]:
df_ru = pd.DataFrame({
        "text": pilsetas_ru.text
    })
df_ru

LOC : Non-GPE locations, mountain ranges, bodies of water
ORG : Companies, agencies, institutions, etc.
PER : Named person or family.

                                                 text
id
0   Персональная выставка Аниты Паегле в музее Ояр...
1   Экскурсии, дегустации и различные мероприятия ...
2   Познавательная выставка об истории борьбы с бр...
3   Персональная выставка Аниты Савицки в музее Ра...
4   Выставка в замке Яунмоку 2025.\n\nВыставка был...
5   Продукты из конопли, их производство и музей в...
6   Выставка современного балтийского дизайна в ко...
7   Выставка в музее Райниса «Ясмуйжа»\n\nС 4 июля...
8   Экскурсии и дегустации – от вин до варенья.\n\...
9   Выставка в Балвском центре культуры и отдыха\n...
10  Экскурсия и дегустации в семейной винодельне в...
11  Выставка будет доступна для просмотра с 8 авгу...
12  Выставка в Талси, в кинотеатре «Аусеклис».\n\n...
13  В Талси желающих по городу катает поезд по име...
14  Возможность посетить место проведения мероприя...
15  Изменчивое лицо Добеле: новая выставка раскрыв...
16  Выставка в мемориальном музее Андрея Упита 202...
17  Персональная выставка Скуя Брейден в Рижском м...
18  ООО Meduspils – возможность посетить производс...
19  Отдых у моря, экскурсия и дегустация различных...
20  Дегустация пива в Латвии – возможность отправи...
21  Выставка в доме Райниса и Аспазии, Рига, 2025\...
22  Сидроварня в Латвии, куда можно съездить на эк...
23  Место для дегустаций, которое можно посетить в...
24  Пабы и пивоварни, предлагаемые маленькими латв...
25  Куда отправиться, чтобы попробовать кофе разны...
26  Мероприятие в рамках цикла "Международный день...
27  Выставка в Народном доме Салгале 2025\n\nХудож...
28  Дегустации вин, экскурсии и приятное времяпреп...
29  Выставка картин Гриеты Брамане и Марии Тимофее...
30  Вкусные дегустации и секреты производства моро...
31  Узнайте, как Латвия принимает цифровые развлеч...
32  Серия мероприятий к 90-летнему юбилею Людмилы ...
33  Фотовыставка карикатуриста Гатиса Шлюки в музе...
34  Выставка картин Майи Буяки в Народном доме Ста...
35  Возможность сфотографироваться на позолоченной...
36  10 км поход по волости Букайши.\n\nДаже зимой ...
37  Персональная выставка Марты Готлиб в Доме реме...
38  Выставки в 2025 году\n\nПриглашаем ознакомитьс...
39  Поймите основные правовые различия между спорт...
40  Игра в онлайн-казино – это развлечение, но все...
41  Экскурсия и дегустации для всей семьи\n\nЭкску...
42  Вечер, когда магия и тайны становятся реальнос...
43  Организация легальных азартных игр в Латвии ст...
44  Узнайте, как индустрия азартных игр в Латвии р...
45  Мини-гольф в помещении для теплой и холодной п...
46  Зима в Северной Латгалии\n\n22 февраля туристи...
47  Пять уникальных сюрпризов на День святого Вале...
48  Идеи эмоциональных подарков на День святого Ва...
49  Вдохновляющие идеи подарков на День святого Ва...
50  Good Wine – это интернет-магазин премиум-класс...
51  Узнайте, как онлайн-казино способствуют развит...
52  Игра в онлайн-казино способна не только достав...

In [24]:
df_ru.text = df_ru.text.apply(lambda x: x.replace("Краткое описание: ", ""))
df_ru.head()

                                                 text
id
0   Персональная выставка Аниты Паегле в музее Ояр...
1   Экскурсии, дегустации и различные мероприятия ...
2   Познавательная выставка об истории борьбы с бр...
3   Персональная выставка Аниты Савицки в музее Ра...
4   Выставка в замке Яунмоку 2025.\n\nВыставка был...

In [25]:
df_ru["doc"] = df_ru.text.apply(process_ru)

In [26]:
df_ru["tokens"] = df_ru.doc.apply(get_token)

In [27]:
df_ru.head()

,text,doc,tokens
id,,,
0,Персональная выставка Аниты Паегле в музее Ояр...,"(Персональная, выставка, Аниты, Паегле, в, муз...","[Персональная, выставка, Аниты, Паегле, в, муз..."
1,"Экскурсии, дегустации и различные мероприятия ...","(Экскурсии, ,, дегустации, и, различные, мероп...","[Экскурсии, ,, дегустации, и, различные, мероп..."
2,Познавательная выставка об истории борьбы с бр...,"(Познавательная, выставка, об, истории, борьбы...","[Познавательная, выставка, об, истории, борьбы..."
3,Персональная выставка Аниты Савицки в музее Ра...,"(Персональная, выставка, Аниты, Савицки, в, му...","[Персональная, выставка, Аниты, Савицки, в, му..."
4,Выставка в замке Яунмоку 2025.\n\nВыставка был...,"(Выставка, в, замке, Яунмоку, 2025, ., \n\n, В...","[Выставка, в, замке, Яунмоку, 2025, ., \n\n, В..."

In [28]:
def get_lemma(doc):
    return [(token.lemma_) for token in doc]

df_ru["lemmas"] = df_ru.doc.apply(get_lemma)

In [29]:
def get_pos(doc):
    return [(token.pos_, token.tag_) for token in doc]

df_ru["pos"] = df_ru.doc.apply(get_pos)

In [30]:
def extract_proper_nouns(doc):
    return [token.text for token in doc if token.pos_ == 'PROPN']

df_ru["proper_nouns"] = df_ru.doc.apply(extract_proper_nouns)

In [31]:
def extract_stopwords(doc):
    return [token.text for token in doc if token.text not in nlp_ru.Defaults.stop_words]


df_ru['Tokens_NoStops'] = df_ru.doc.apply(extract_stopwords)

df_ru['Text_NoStops'] = [' '.join(map(str, l)) for l in df_ru['Tokens_NoStops']]

df_ru['Doc_NoStops'] = df_ru['Text_NoStops'].apply(process_ru)

In [32]:

doc = df_ru['Doc_NoStops'][0]
sentences = list(doc.sents)
sentence = sentences[0]

displacy.render(sentence, style='dep', jupyter=True)

In [33]:
def extract_noun_phrases(doc):
    return [chunk.text for chunk in doc.noun_chunks]

# df_ru['Noun_Phrases'] = df_ru.doc.apply(extract_noun_phrases)
 # not implemented in ru :<

In [ ]:
df_ru["named_entities"] = df_ru.doc.apply(extract_named_entities_labels, labels_ru)

In [35]:
def extract_named_entities(doc):
    return [ent for ent in doc.ents]

df_ru['NE_Words'] = df_ru['doc'].apply(extract_named_entities)
df_ru['NE_Words']

id
0     [(Аниты, Паегле), (Ояра, Вациетиса), (Ояра, Ва...
1     [(Зилвер), (Возможны), (Зилвер), (Facebook), (...
2     [(Сигулде), (Гауи), (Национальном, парке), (Га...
3     [(Аниты, Савицки), (Райниса, «, Ясмужа, »), (Р...
4     [(Яунмоку), (Яунмоку), (Яунмоку), (Визуальной,...
5     [(Резекненском, крае), (Obelisk, Farm), (Obeli...
6     [(Большой, янтарь), (Civita, Nova), (Civita, N...
7     [(Райниса, «, Ясмуйжа), (Райниса, «, Ясмуйжа, ...
8                                            [(Латвии)]
9     [(Балвском, центре, культуры, и, отдыха), (Бал...
10    [(Добельском, крае), (Тервете), (Сандрис, Лайз...
11    [(Огрском, музее, истории, и, искусства), (Огр...
12    [(Талси), (Аусеклис), (Марите, Пипите), (Кулди...
13    [(Талси), (Фрицис), (Талси), (Фрицис), (Талси)...
14    [(Резекне), (Латгальский, центр, культуры), (G...
15    [(Добеле), (Добеле), (Добеле), (Добеле), (Добе...
16    [(Андрея, Упита), (Латвийской, академии, искус...
17    [(Скуя, Брейден), (Рижском, музее), (Рижском, ...
18    [(ООО, Meduspils), (Салдусском, крае), (Латвии...
19    [(Денины), (Энгуре), (Энгуре), (Рижского, зали...
20    [(Латвии), (Ужавас), (Латвии), (Ужавас), (Авст...
21    [(Райниса), (Аспазии), (Рига), (Райниса), (Асп...
22    [(Латвии), (Плуме), (Господине, Плуме), (Сидро...
23                               [(Готиня), (Скривери)]
24    [(Латвии), (Valmiermuižas), (Риге), (Северной,...
25    [(KUUP), (KUUP), (Резекненском, крае), (Вирауд...
26    [(Риге), (Райниса), (Аспазии), (Александра, Ча...
27    [(Народном, доме, Салгале), (Сандра, Делгалве)...
28    [(Сабиле), (Абавы), (Спару), (Абавы), (Сабиле)...
29    [(Гриеты, Брамане), (Марии, Тимофеевой), (Райн...
30    [(Латвии), (Руйиене), (Упес), (Латвии), (Руйие...
31             [(Латвия), (Латвии), (Латвия), (Латвии)]
32    [(Людмилы, Азаровой), (Людмилы, Азаровой), (Оя...
33    [(Гатиса, Шлюки), (Кекавы), (Гатиса, Шлюки), (...
34    [(Майи, Буяки), (Народном, доме), (Ване), (Тук...
35    [(Йоханнеса, Ангебауэра), (Стамериена), (Стаме...
36    [(Букайши), (Букайши), (Х.,  , Цукура), (Лидон...
37    [(Марты, Готлиб), (Доме, ремесел), (Доме, реме...
38    [(Южнокурземском, крае), (Айзпуте), (Бунка), (...
39    [(Латвии), (Латвии), (Инспекции, по, надзору, ...
40                                  [(Excel), (Google)]
41                                        [(Экскурсия)]
42             [(Иллюзионист, Эджус), (Латвии), (Риге)]
43    [(Латвии), (Латвии), (Латвии), (Кабинета, Мини...
44    [(Латвии), (Латвии), (Laimz, casino), (Латвии)...
45    [(Гольфиньш), (Риге), (Кр), (Кришьяня, Барона)...
46    [(Северной, Латгалии), (Лудзского, края), (Нум...
47                                                   []
48                                  [(Fotostudijas.lv)]
49                                                   []
50    [(Good, Wine), (Good, Wine), (изысканныевина),...
51    [(Онлайн, -, казино), (Казино), (Помимо, созда...
52                                               [(NV)]
Name: NE_Words, dtype: object

In [36]:
displacy.render(df_ru.doc[0], style="ent", jupyter=True)

In [37]:
df_ru.loc[0]

text              Персональная выставка Аниты Паегле в музее Ояр...
doc               (Персональная, выставка, Аниты, Паегле, в, муз...
tokens            [Персональная, выставка, Аниты, Паегле, в, муз...
lemmas            [персональный, выставка, аниты, паегле, в, муз...
pos               [(ADJ, ADJ), (NOUN, NOUN), (PROPN, PROPN), (PR...
proper_nouns      [Аниты, Паегле, Ояра, Вациетиса, Ояра, Вациети...
Tokens_NoStops    [Персональная, выставка, Аниты, Паегле, музее,...
Text_NoStops      Персональная выставка Аниты Паегле музее Ояра ...
Doc_NoStops       (Персональная, выставка, Аниты, Паегле, музее,...
named_entities    [PER, PER, PER, LOC, LOC, PER, PER, PER, PER, ...
NE_Words          [(Аниты, Паегле), (Ояра, Вациетиса), (Ояра, Ва...
Name: 0, dtype: object

In [ ]:
from nltk.tokenize import word_tokenize

nltk.download('punkt') # For tokenizer
nltk.download('punkt_tab')
# This downloads the pre-trained Russian tagger data
nltk.download('tagsets') 
nltk.download('averaged_perceptron_tagger_rus') 

def extract_russian_noun_phrases(text):
    # Tokenize and POS tag the Russian text using NLTK's built-in tagger
    tokens = word_tokenize(text, language='russian')
    tagged_tokens = nltk.pos_tag(tokens, lang='rus')

    # Define a simple grammar for noun phrases (e.g., Adjective(s) + Noun(s))
    # 'A' is the RNC tag for Adjective, 'S' for Noun
    grammar = r"""
      NP: {<A>*<S>+}   # Chunk sequences of Adjectives followed by Nouns
    """
    cp = nltk.RegexpParser(grammar)
    tree = cp.parse(tagged_tokens)

    noun_phrases = []
    for subtree in tree.subtrees():
        if subtree.label() == 'NP':
            # Reconstruct the noun phrase from the words in the subtree
            phrase = " ".join([word for word, tag in subtree.leaves()])
            noun_phrases.append(phrase)
    return noun_phrases

# Example text: "у меня было красивое и нежное лицо" (I had a beautiful and delicate face)

df_ru["chunks"] = df_ru.text.apply(extract_russian_noun_phrases)
# Expected output might be: ['красивое и нежное лицо']
df_ru.chunks[0]

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Andy\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Andy\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package tagsets to
[nltk_data]     C:\Users\Andy\AppData\Roaming\nltk_data...
[nltk_data]   Package tagsets is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger_rus to
[nltk_data]     C:\Users\Andy\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_rus is already up-to-
[nltk_data]       date!

['выставка Аниты Паегле',
 'музее Ояра Вациетиса',
 'сентября',
 'музее Ояра Вациетиса',
 'адресу улица Ояра Вациетиса',
 'Рига',
 'открытие',
 'выставки художницы Аниты Паегле',
 'Рига',
 'Осень',
 'Звезды.',
 'выставке',
 'иллюстрации',
 'книге Мары Циелене',
 'Улыбка Сфинкса Альберта',
 'книгам Юриса Звиргздиня',
 'сказка',
 'Сказка',
 'сне',
 'книге Инесы Зандере',
 'Кот',
 'клавишах',
 'вещи',
 'художницы',
 'источником вдохновения',
 'создании работ',
 'Выставка',
 'разговором',
 'зрителем',
 'мыслях',
 'прогулке',
 'городу',
 'Зиедоньдарза',
 'улице Чака',
 'домов',
 'улице Альберта',
 'улочкам Пардогавы',
 'звезды',
 'иллюстрации',
 'прудом Мары',
 'книги Юриса Звиргздиня',
 'Сказка',
 'сне',
 'иллюстрации',
 'книге Инесы Зандере',
 'Кот',
 'клавишах',
 'воспоминания',
 'приключения',
 'тоска',
 'иллюстрациях время',
 'художница',
 'Анита Паегле',
 'классик',
 'иллюстрации',
 'поколению читателей',
 'году',
 'Риге',
 'школу имени Яниса Розентала',
 'факультет',
 'академии художеств',
 'года',
 'сотрудничество художницы',
 'издательством',
 'Лиесма',
 'издательствами',
 'Спридитис',
 'Гара Пупа',
 'Яня Сета',
 'Анита Паегле',
 'стиль иллюстрации',
 'целом',
 'книг',
 'детей',
 'взрослых',
 'место',
 'произведения Мары Циелене',
 'Яниса Балтавилкса',
 'Анита Паегле',
 'основательниц премии Яниса Балтавилка',
 'журналы',
 'Эзис',
 'триеннале',
 'графики',
 'Вильнюсе',
 'биенналях иллюстрации',
 'Братиславе',
 'годах',
 'биеннале иллюстрации',
 'Японии',
 'триеннале иллюстрации',
 'Эстонии',
 'году',
 'диплом',
 'иллюстрации',
 'книге М. Циелене',
 'королева',
 'Риге',
 'художницы',
 'выставки',
 'Латвии',
 'Франции',
 'Польше',
 'Италии',
 'Чехии',
 'России',
 'Анита Паегле',
 'дизайн',
 'монет',
 'Банком Латвии',
 'Монета люльки',
 'Монета года Латвии',
 'монета',
 'котов',
 'Монета года Латвии',
 'иллюстрации',
 'книгам Анита Паегле',
 'множество признаний',
 'наград',
 'премию',
 'премию Пастариньша',
 'премию',
 'конкурсе',
 'искусства',
 'яблоко',
 'премию Индрика Зебериня',
 'награды',
 'конкурсе',
 'книги Балтии',
 'году',
 'иллюстрации',
 'книге Мары Циелене',
 'ходы часов',
 'Анита Паегле',
 'список иллюстраторов мира',
 'вклад',
 'развитие искусства',
 'книги',
 'году художница',
 'премию Балтавилкса',
 'Художница',
 'награду',
 'области',
 'литературы',
 'иллюстрации – премию Ханса Кристиана Андерсена',
 'премию',
 'академии художеств',
 'достижения',
 'Выставка',
 'музее',
 'августа',
 'октября']

In [39]:
doc = pd.Series(df_ru.chunks[0]).apply(process_ru)
doc

0             (выставка, Аниты, Паегле)
1              (музее, Ояра, Вациетиса)
2                            (сентября)
3              (музее, Ояра, Вациетиса)
4      (адресу, улица, Ояра, Вациетиса)
                     ...
147                        (достижения)
148                          (Выставка)
149                             (музее)
150                           (августа)
151                           (октября)
Length: 152, dtype: object

In [40]:
doc.apply(get_lemma).value_counts()

[иллюстрация]                                         7
[анита, паегле]                                       5
[год]                                                 5
[выставка]                                            4
[художница]                                           4
                                                     ..
[иллюстрация, –, премия, ханс, кристиан, андерсен]    1
[достижение]                                          1
[музей]                                               1
[август]                                              1
[октябрь]                                             1
Name: count, Length: 111, dtype: int64

In [41]:
df_ru.loc[0]

text              Персональная выставка Аниты Паегле в музее Ояр...
doc               (Персональная, выставка, Аниты, Паегле, в, муз...
tokens            [Персональная, выставка, Аниты, Паегле, в, муз...
lemmas            [персональный, выставка, аниты, паегле, в, муз...
pos               [(ADJ, ADJ), (NOUN, NOUN), (PROPN, PROPN), (PR...
proper_nouns      [Аниты, Паегле, Ояра, Вациетиса, Ояра, Вациети...
Tokens_NoStops    [Персональная, выставка, Аниты, Паегле, музее,...
Text_NoStops      Персональная выставка Аниты Паегле музее Ояра ...
Doc_NoStops       (Персональная, выставка, Аниты, Паегле, музее,...
named_entities    [PER, PER, PER, LOC, LOC, PER, PER, PER, PER, ...
NE_Words          [(Аниты, Паегле), (Ояра, Вациетиса), (Ояра, Ва...
chunks            [выставка Аниты Паегле, музее Ояра Вациетиса, ...
Name: 0, dtype: object

In [42]:
vals = doc.apply(get_lemma).value_counts()
{
    tuple(k): v
    for k, v in 
    zip(vals.keys().to_list(), vals.to_list())
}

{('иллюстрация',): 7,
 ('анита', 'паегле'): 5,
 ('год',): 5,
 ('выставка',): 4,
 ('художница',): 4,
 ('сказка',): 3,
 ('кот',): 3,
 ('награда',): 3,
 ('премия',): 3,
 ('музей', 'ояра', 'вациетиса'): 2,
 ('рига',): 2,
 ('книга', 'мара', 'циелене'): 2,
 ('книга', 'юрис', 'звиргздиня'): 2,
 ('сон',): 2,
 ('книга', 'инеса', 'зандере'): 2,
 ('клавиша',): 2,
 ('риге',): 2,
 ('академия', 'художество'): 2,
 ('книга',): 2,
 ('монета',): 2,
 ('монета', 'год', 'латвия'): 2,
 ('конкурс',): 2,
 ('выставка', 'аниты', 'паегле'): 1,
 ('сентябрь',): 1,
 ('адрес', 'улица', 'ояра', 'вациетиса'): 1,
 ('открытие',): 1,
 ('выставка', 'художница', 'анита', 'паегле'): 1,
 ('осень',): 1,
 ('звезда', '.'): 1,
 ('улыбка', 'сфинкс', 'альберт'): 1,
 ('вещь',): 1,
 ('источник', 'вдохновение'): 1,
 ('создание', 'работа'): 1,
 ('разговор',): 1,
 ('зритель',): 1,
 ('мысль',): 1,
 ('прогулка',): 1,
 ('город',): 1,
 ('зиедоньдарза',): 1,
 ('улица', 'чак'): 1,
 ('дом',): 1,
 ('улица', 'альберт'): 1,
 ('улочка', 'пардогавы'): 1,
 ('звезда',): 1,
 ('пруд', 'мара'): 1,
 ('воспоминание',): 1,
 ('приключение',): 1,
 ('тоска',): 1,
 ('иллюстрация', 'время'): 1,
 ('классик',): 1,
 ('поколение', 'читатель'): 1,
 ('школа', 'имя', 'янис', 'розентала'): 1,
 ('факультет',): 1,
 ('сотрудничество', 'художница'): 1,
 ('издательство',): 1,
 ('лиесма',): 1,
 ('издательствами',): 1,
 ('спридитис',): 1,
 ('гара', 'пуп'): 1,
 ('яня', 'сет'): 1,
 ('стиль', 'иллюстрация'): 1,
 ('целое',): 1,
 ('ребёнок',): 1,
 ('взрослый',): 1,
 ('место',): 1,
 ('произведение', 'мара', 'циелене'): 1,
 ('янис', 'балтавилкса'): 1,
 ('основательница', 'премия', 'янис', 'балтавилка'): 1,
 ('журнал',): 1,
 ('эзис',): 1,
 ('триеннале',): 1,
 ('график',): 1,
 ('вильнюс',): 1,
 ('биенналях', 'иллюстрация'): 1,
 ('братиславе',): 1,
 ('биеннале', 'иллюстрация'): 1,
 ('япония',): 1,
 ('триеннале', 'иллюстрация'): 1,
 ('эстония',): 1,
 ('диплом',): 1,
 ('книга', 'м.', 'циелене'): 1,
 ('королева',): 1,
 ('латвия',): 1,
 ('франция',): 1,
 ('польша',): 1,
 ('италия',): 1,
 ('чехия',): 1,
 ('россия',): 1,
 ('дизайн',): 1,
 ('банк', 'латвия'): 1,
 ('монета', 'люлька'): 1,
 ('книга', 'анит', 'паегле'): 1,
 ('множество', 'признание'): 1,
 ('премия', 'пастариньша'): 1,
 ('искусство',): 1,
 ('яблоко',): 1,
 ('премия', 'индрика', 'зебериня'): 1,
 ('книга', 'балтия'): 1,
 ('ход', 'час'): 1,
 ('список', 'иллюстратор', 'мир'): 1,
 ('вклад',): 1,
 ('развитие', 'искусство'): 1,
 ('год', 'художница'): 1,
 ('премия', 'балтавилкса'): 1,
 ('область',): 1,
 ('литература',): 1,
 ('иллюстрация', '–', 'премия', 'ханс', 'кристиан', 'андерсен'): 1,
 ('достижение',): 1,
 ('музей',): 1,
 ('август',): 1,
 ('октябрь',): 1}

In [43]:
pilsetas_ru["named_entities_type"] = df_ru.named_entities
pilsetas_ru["named_entities"] = df_ru.NE_Words
pilsetas_ru["noun_phrases"] = df_ru.chunks
# pilsetas_ru["noun_phrases_counts"] = {
#     tuple(k): v
#     for k, v in 
#     zip(vals.keys().to_list(), vals.to_list())
# }
pilsetas_ru.loc[0]

url                    https://pilsetas.lv/ru/novosti/izstades-riga-r...
image_url              https://pilsetas.lv/pictures/users/uploaded/2/...
title                           Открытие выставки «Рига. Осень. Звезды.»
date                                                    13:03 29.08.2025
author                                                      RT Kompānija
topics                           ['Развлечения', 'Культура', 'Oбщество']
text                   Персональная выставка Аниты Паегле в музее Ояр...
matching_article_id                                                  3.0
named_entities_type    [PER, PER, PER, LOC, LOC, PER, PER, PER, PER, ...
named_entities         [(Аниты, Паегле), (Ояра, Вациетиса), (Ояра, Ва...
noun_phrases           [выставка Аниты Паегле, музее Ояра Вациетиса, ...
adjectives             ['персональный', '4', 'персональный', 'зимний'...
Name: 0, dtype: object

In [44]:
df_ru.loc[0]

text              Персональная выставка Аниты Паегле в музее Ояр...
doc               (Персональная, выставка, Аниты, Паегле, в, муз...
tokens            [Персональная, выставка, Аниты, Паегле, в, муз...
lemmas            [персональный, выставка, аниты, паегле, в, муз...
pos               [(ADJ, ADJ), (NOUN, NOUN), (PROPN, PROPN), (PR...
proper_nouns      [Аниты, Паегле, Ояра, Вациетиса, Ояра, Вациети...
Tokens_NoStops    [Персональная, выставка, Аниты, Паегле, музее,...
Text_NoStops      Персональная выставка Аниты Паегле музее Ояра ...
Doc_NoStops       (Персональная, выставка, Аниты, Паегле, музее,...
named_entities    [PER, PER, PER, LOC, LOC, PER, PER, PER, PER, ...
NE_Words          [(Аниты, Паегле), (Ояра, Вациетиса), (Ояра, Ва...
chunks            [выставка Аниты Паегле, музее Ояра Вациетиса, ...
Name: 0, dtype: object

In [45]:
def extract_adjs(doc):
    return [token.lemma_ for token in doc if token.pos_ == 'ADJ']

df_ru.doc.apply(extract_adjs)
pilsetas_ru["adjectives"] = df_ru.doc.apply(extract_adjs)

In [46]:
pilsetas_ru.loc[0]

url                    https://pilsetas.lv/ru/novosti/izstades-riga-r...
image_url              https://pilsetas.lv/pictures/users/uploaded/2/...
title                           Открытие выставки «Рига. Осень. Звезды.»
date                                                    13:03 29.08.2025
author                                                      RT Kompānija
topics                           ['Развлечения', 'Культура', 'Oбщество']
text                   Персональная выставка Аниты Паегле в музее Ояр...
matching_article_id                                                  3.0
named_entities_type    [PER, PER, PER, LOC, LOC, PER, PER, PER, PER, ...
named_entities         [(Аниты, Паегле), (Ояра, Вациетиса), (Ояра, Ва...
noun_phrases           [выставка Аниты Паегле, музее Ояра Вациетиса, ...
adjectives             [персональный, 4, персональный, зимний, важный...
Name: 0, dtype: object

In [47]:
pilsetas_ru.text = df_ru.text

In [48]:
pilsetas_ru.to_csv(dataset_path / "pilsetas_ru.csv", sep="`", index_label="id")

,text,doc,tokens,lemmas,pos,proper_nouns,Tokens_NoStops,Text_NoStops,Doc_NoStops,named_entities,NE_Words,chunks
count,53,53,53,53,53,53,53,53,53,53,53,53
unique,53,53,53,53,53,53,53,53,53,51,52,53
top,Персональная выставка Аниты Паегле в музее Ояр...,"(Персональная, выставка, Аниты, Паегле, в, муз...","[Персональная, выставка, Аниты, Паегле, в, муз...","[персональный, выставка, аниты, паегле, в, муз...","[(ADJ, ADJ), (NOUN, NOUN), (PROPN, PROPN), (PR...","[Аниты, Паегле, Ояра, Вациетиса, Ояра, Вациети...","[Персональная, выставка, Аниты, Паегле, музее,...",Персональная выставка Аниты Паегле музее Ояра ...,"(Персональная, выставка, Аниты, Паегле, музее,...",[],[],"[выставка Аниты Паегле, музее Ояра Вациетиса, ..."
freq,1,1,1,1,1,1,1,1,1,2,2,1

In [49]:
!python.exe -m spacy download en_core_web_lg --q

^C

In [50]:
nlp_eng = spacy.load('en_core_web_lg')

print(nlp_eng.pipe_names)

def process_en(text):
    return nlp_eng(text)

['tok2vec', 'tagger', 'parser', 'attribute_ruler', 'lemmatizer', 'ner']

In [54]:
pilsetas_ru["event", 0] = "выставка"

In [55]:
pilsetas_ru["event"] = df_ru.lemmas.apply(lambda x: "выставка" if "выставка" in x else False)

In [56]:
pilsetas_ru.loc[pilsetas_ru.event == False].index + 1

Index([ 2,  9, 11, 14, 15, 19, 20, 21, 23, 24, 25, 26, 29, 31, 36, 37, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53],
      dtype='int64', name='id')

In [ ]:
# экскурсии: 1, 5, 8, 10, 14, 18, 19, 20, 22, 23, 25, 26, 28, 30, 41
# дегустация: 1, 5, 8, 10, 18, 19, 20, 22, 23, 24, 25, 28, 30, 41
# поездки/прогулки - 13
# тур - 24
# мастер-класс - 26
# мероприятие/перформанс - 35
# поход - 36, 46
# шоу - 42
# отдых - 45
# игры - 45
# площадки для мероприятий - 45
# перечисление - 24, 25, 45

# нет: 31, 39, 40, 43, 44, 47, 48, 49, 50, 51, 52

In [59]:
# pilsetas_ru[["title", "text", "event"]]
# pilsetas_ru.loc[1, "event"] = "экскурсии"
pilsetas_ru.drop(index=[31, 39, 40, 43, 44, 47, 48, 49, 50, 51, 52], inplace=True)

In [60]:
for i in [1, 5, 8, 10, 18, 19, 20, 22, 23, 25, 26, 28, 30, 41]:
    pilsetas_ru.loc[i, "event"] = "экскурсия, дегустация"
pilsetas_ru.loc[14, "event"] = "экскурсия"
pilsetas_ru.loc[24, "event"] = "тур, дегустация"
pilsetas_ru.loc[13, "event"] = "поездки/прогулки"
pilsetas_ru.loc[26, "event"] = "дегустация, мастер-класс"
pilsetas_ru.loc[35, "event"] = "перформанс"
pilsetas_ru.loc[36, "event"] = "поход"
pilsetas_ru.loc[46, "event"] = "поход"
pilsetas_ru.loc[42, "event"] = "шоу"
pilsetas_ru.loc[45, "event"] = "игровой отдых"

In [61]:
pilsetas_ru.event.value_counts()

event
выставка                    20
экскурсия, дегустация       13
поход                        2
поездки/прогулки             1
экскурсия                    1
тур, дегустация              1
дегустация, мастер-класс     1
перформанс                   1
шоу                          1
игровой отдых                1
Name: count, dtype: int64

In [62]:
pilsetas_ru.info()

<class 'pandas.DataFrame'>
Index: 42 entries, 0 to 46
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   url                  42 non-null     str
 1   image_url            42 non-null     str
 2   title                42 non-null     str
 3   date                 42 non-null     str
 4   author               42 non-null     str
 5   topics               42 non-null     str
 6   text                 42 non-null     str
 7   matching_article_id  42 non-null     float64
 8   named_entities_type  42 non-null     object
 9   named_entities       42 non-null     object
 10  noun_phrases         42 non-null     object
 11  adjectives           42 non-null     object
 12  (event, 0)           42 non-null     str
 13  event                42 non-null     object
dtypes: float64(1), object(5), str(8)
memory usage: 6.0+ KB

In [76]:
names = pilsetas_ru.named_entities.explode().tolist()

sum_ent = 0
entities = {}
for n in set(names):
    if n.text not in entities:
        entities[n.text] = 1
        sum_ent += 1
    else:
        entities[n.text] += 1
        sum_ent += 1
sum_ent

727

In [ ]:
sorted(entities.items(), key=lambda x: x[1], reverse=True)

[('Латвии', 36),
 ('Риге', 12),
 ('Аспазии', 11),
 ('Ояра Вациетиса', 11),
 ('Райниса', 10),
 ('Добеле', 9),
 ('Фрицис', 9),
 ('Скуя Брейден', 8),
 ('Париже', 6),
 ('Талси', 6),
 ('США', 6),
 ('Огре', 6),
 ('Анита Паегле', 6),
 ('Большой янтарь', 6),
 ('Абавы', 5),
 ('Мария', 4),
 ('Марии', 4),
 ('Вильнюсе', 4),
 ('Франции', 4),
 ('М.Готлиб', 4),
 ('ООО Meduspils', 4),
 ('Анита Савицка', 4),
 ('Людмилы Азаровой', 4),
 ('Tactile Baltics', 3),
 ('Яунмоку', 3),
 ('Романа Суты', 3),
 ('StaroJums', 3),
 ('Кулдиге', 3),
 ('Майя', 3),
 ('Андрея Упита', 3),
 ('Ояр Вациетис', 3),
 ('Мары Циелене', 3),
 ('Рижском музее', 3),
 ('Curonia Coffee', 3),
 ('Civita Nova', 3),
 ('Obelisk Farm', 3),
 ('Рига', 3),
 ('Букайши', 3),
 ('KUUP', 3),
 ('Балвского края', 3),
 ('Зилвер', 3),
 ('Александры Бельцовой', 3),
 ('Энгуре', 3),
 ('Резекне', 3),
 ('GORS', 3),
 ('Александра Чака', 3),
 ('Италия', 3),
 ('Италии', 3),
 ('Латвию', 2),
 ('Балтии', 2),
 ('Гриеты Брамане', 2),
 ('Гатиса Шлюки', 2),
 ('Латвийской академии искусств', 2),
 ('Латгалии', 2),
 ('Марии Тимофеевой', 2),
 ('Рижской группы художников', 2),
 ('Яниса Акурейтера', 2),
 ('MoscaPartners', 2),
 ('Гатис Шлюка', 2),
 ('Марты Готлиб', 2),
 ('Юриса Звиргздиня', 2),
 ('Дита Даноса', 2),
 ('Сабиле', 2),
 ('Доме ремесел', 2),
 ('Индра Кэйша', 2),
 ('Дзирциемсе', 2),
 ('Ужавас', 2),
 ('Шотландии', 2),
 ('Барты', 2),
 ('Марты Андерсоне', 2),
 ('Эстонии', 2),
 ('Милане', 2),
 ('Нумернес Валнис', 2),
 ('Лиепае', 2),
 ('Павилосты', 2),
 ('Национальном парке', 2),
 ('Приекуле', 2),
 ('Литвы', 2),
 ('Балтийском регионе', 2),
 ('Аниты Савицки', 2),
 ('Кекавы', 2),
 ('Саулкрасты', 2),
 ('Rocket Bean Roastery', 2),
 ('Резекненском крае', 2),
 ('Гатис', 2),
 ('Йоханнеса Ангебауэра', 2),
 ('Северной Латгалии', 2),
 ('Базницас', 2),
 ('Чака', 2),
 ('Тервете', 2),
 ('Ундине Крузе', 2),
 ('Латвийской академии художеств', 2),
 ('Нью-Йорк', 2),
 ('Фриды Кало', 2),
 ('Огрском музее истории и искусства', 2),
 ('Аниты Паегле', 2),
 ('Милан', 2),
 ('Ирены Штейнберги', 2),
 ('Стамериена', 2),
 ('Прейльский край', 2),
 ('Народном доме Салгале', 2),
 ('Ояра', 2),
 ('Инесы Зандере', 2),
 ('Рейнхольда Каспарсона', 2),
 ('Сигне Краукле', 2),
 ('Айзкалне', 2),
 ('NID', 2),
 ('Айзпуте', 2),
 ('Гауя', 2),
 ('Балвском центре культуры и отдыха', 2),
 ('Kolumbejis flirts', 1),
 ('Аусеклис', 1),
 ('Лачплеша', 1),
 ('Капрезе Микеланджело', 1),
 ('Ленджском волости', 1),
 ('Милде Гринфелде', 1),
 ('Лита', 1),
 ('Фриде Кало', 1),
 ('AIJA', 1),
 ('Мелисы Скуя-Брейдены', 1),
 ('Фрида Кало', 1),
 ('Огрское общество развития', 1),
 ('Скуя Брейден - "Уги', 1),
 ('Рижскую школу дизайна и искусства', 1),
 ('Экскурсия', 1),
 ('Райниса «Ясмуйжа', 1),
 ('JCK Las Vegas', 1),
 ('Labietis', 1),
 ('Акурейтера', 1),
 ('М. Циелене', 1),
 ('Эрмини', 1),
 ('Оскар Сидельникс', 1),
 ('Пост-мистики', 1),
 ('Гвидо Кайонс', 1),
 ('Рыбацкий двор', 1),
 ('Чак', 1),
 ('Ирены', 1),
 ('Металлического дизайна', 1),
 ('Марта Андерсоне', 1),
 ('Риги', 1),
 ('Сийм Карро (Siim Karro)', 1),
 ('Агрит Ванаг', 1),
 ('Яня Сета', 1),
 ('Ингуна', 1),
 ('Торнякалнс', 1),
 ('А. Бриана', 1),
 ('Ассоциации драматургов', 1),
 ('Лиепа Градаускайте (Liepa Gradauskaitė)', 1),
 ('Литовским форумом дизайна и дизайнерским агентством "', 1),
 ('Х.\xa0Цукура', 1),
 ('Рижскую художественную среднюю школу имени Яниса Розентала', 1),
 ('Господине Плуме', 1),
 ('Залите', 1),
 ('Национальной Ассоциацией музеев личностей Италии "Дома памяти', 1),
 ('Арнис Стасаитис', 1),
 ('Латвия', 1),
 ('Ганзейского союза', 1),
 ('Латвийского центра дизайна', 1),
 ('Cupping', 1),
 ('Стрекозе', 1),
 ('Людмила', 1),
 ('Р. Сута', 1),
 ('Айзпутском краеведческом музее выставка рукоделий Яны Лиепиня-Пиккена', 1),
 ('Гунтарс Андерсонс\nВыставка', 1),
 ('Балвском крае', 1),
 ('Плуме', 1),
 ('Вирджинии Контареллы', 1),
 ('Кришьяня Барона', 1),
 ('Яниса Балтавилка', 1),
 ('Нилс Микельсонс', 1),
 ('Б. Зуйане', 1),
 ('Гробине', 1),
 ('Марите', 1),
 ('Facebook', 1),
 ('Айзпутского краеведческого музея “Украшено.', 1),
 ('Аспазии Маргариты Розенберги', 1),
 ('Мантас Лесаускас (Mantas Lesauskas)', 1),
 ('Милде', 1),
 ('Boterra', 1),
 ('Скотный двор', 1),
 ('Елизавета Гроце', 1),
 ('Ирины Риежниеце', 1),
 ('Мелиса', 1),
 ('Каково', 1),
 ('Марии Лейн (Marie Lein)', 1),
 ('Гинта Гринберга', 1),
 ('Тимур Томсон', 1),
 ('Лиепаи', 1),
 ('Берзпилской основной школы', 1),
 ('Пастариньша', 1),
 ('Алдис Войтс', 1),
 ('Огрским музеем истории и искусства', 1),
 ('Ясмуйже', 1),
 ('Лиго', 1),
 ('Бостон', 1),
 ('Лиепайской академии', 1),
 ('Международным комитетом музеев литературы и композиторов', 1),
 ('Марис Гросбахс', 1),
 ('Сказочная монета I. Пять котов»', 1),
 ('Визуальной коммуникации', 1),
 ('Valmiermuižasрасположено', 1),
 ('Вираудас', 1),
 ('Культурном дворце', 1),
 ('Европейской конференции музеев личностей', 1),
 ('Павилостской школы музыки и искусства', 1),
 ('Янис Зиньгитис', 1),
 ('Anita Sondore', 1),
 ('Артис Ниманис', 1),
 ('Арта Роланда Лайцане', 1),
 ('Пардогавы', 1),
 ('Valmiermuižasв Риге', 1),
 ('Якоба', 1),
 ('Сандры', 1),
 ('Иллюзионист Эджус', 1),
 ('Возможны', 1),
 ('Калькю', 1),
 ('Денины', 1),
 ('Сандрис Лайзанс', 1),
 ('Виктории Рено (Viktoria Renaux)', 1),
 ('Рижском музее фарфора', 1),
 ('Зигмарс Яуя', 1),
 ('ВЫСТАВКА ТВОРЧЕСКИХ РАБОТ', 1),
 ('Илзе Стагите', 1),
 ('Valmiermuižas', 1),
 ('Спридитис', 1),
 ('Люция Костива (Liucija Kostiva)', 1),
 ('Международным комитетом', 1),
 ('Алисе Крокфорда', 1),
 ('ĒTER', 1),
 ('Мартин Пукс', 1),
 ('Айя Принце', 1),
 ('Лива Индрике', 1),
 ('Тукумского края', 1),
 ('Venice Design Week', 1),
 ('ICOM (', 1),
 ('Гауи', 1),
 ('Янис Акурейтер', 1),
 ('Зилите', 1),
 ('Циниш', 1),
 ('Ояре Вациетисе', 1),
 ('Международным советом музеев', 1),
 ('Зельда Виктория Янсоне', 1),
 ('Аудроне Друнгилайте', 1),
 ('Даце Суна', 1),
 ('Бригита Була', 1),
 ('Бунка', 1),
 ('Лиене Лауриновича', 1),
 ('Нумернес', 1),
 ('Лига Тумина', 1),
 ('Братиславе', 1),
 ('Сандре', 1),
 ('Булдурского садоводческого техникума', 1),
 ('Палете', 1),
 ('Скривери', 1),
 ('Павилостском краеведческом музее выставка', 1),
 ('Банком Латвии', 1),
 ('Риме', 1),
 ('Илзе Пукье', 1),
 ('Кр', 1),
 ('Латвийской Академии Искусств', 1),
 ('О. Вациетиса', 1),
 ('Артис Тауриньш / Formup', 1),
 ('Сандры Делгалве', 1),
 ('Эзис', 1),
 ('Латгальским центром культуры', 1),
 ('Гольфиньш', 1),
 ('Йоланта Дундене', 1),
 ('Фрициса', 1),
 ('фон Стрика', 1),
 ('Талсинских холмов', 1),
 ('Улдис Апинис\nХудожники', 1),
 ('Солженицын', 1),
 ('Бривибас', 1),
 ('Латгальском музее культурной истории', 1),
 ('Таллине', 1),
 ('Лудзского края', 1),
 ('Марите Пипите', 1),
 ('Бруниниеку', 1),
 ('Вильхельм Бандерс', 1),
 ('Паулина Василяускайте (Paulina Vasiliauskaitė)', 1),
 ('Рижского музея фарфора', 1),
 ('Элина Церпа', 1),
 ('Интарс Сниедзе', 1),
 ('SIA «Parrot Telpa', 1),
 ('Brazilejis nakts', 1),
 ('Барканами', 1),
 ('Irena Gasha embroideries', 1),
 ('Лиепая', 1),
 ('Андрисом', 1),
 ('Валдемара', 1),
 ('Зенты Маурини', 1),
 ('Южнокурземском крае', 1),
 ('Лаура Зунда-Поча\nИзмерения', 1),
 ('SIA «MT Sēta', 1),
 ('Мария Лейн', 1),
 ('Сидроварня', 1),
 ('Яниса Балтавилкса', 1),
 ('Аннике Лайго', 1),
 ('Элизабетес', 1),
 ('Кирилл Кирасиров', 1),
 ('Доступен', 1),
 ('Добельском крае', 1),
 ('Эмма София', 1),
 ('Кримунском волосте', 1),
 ('иторговцы', 1),
 ('Европейского союза', 1),
 ('Райниса «Ясмужа» (', 1),
 ('Спару', 1),
 ('Суну', 1),
 ('Даугавгривас', 1),
 ('Алдиса Клявиньша', 1),
 ('Токио', 1),
 ('Эглайнской основной школы - Тина Леоне', 1),
 ('Ясмуже', 1),
 ('Готиня', 1),
 ('Руйиены', 1),
 ('Рича', 1),
 ('Азии', 1),
 ('Валерия Сосова', 1),
 ('Антропоцена', 1),
 ('Государственного фонда культурного капитала', 1),
 ('A’Design', 1),
 ('Салдусского края', 1),
 ('Скуи Брейден', 1),
 ('Имей', 1),
 ('Лидони', 1),
 ('Тереза', 1),
 ('МИТРАЙС', 1),
 ('Марья Маеметс (Maarja Mäemets)', 1),
 ('Эдите Калнине', 1),
 ('Блиденской волости', 1),
 ('Nurme', 1),
 ('ICOM ICLCM', 1),
 ('Зигмарс Яуя\nИсторическое', 1),
 ('Людмила Азарова', 1),
 ('Огрского общества развития', 1),
 ('Латвийское Солнце', 1),
 ('Даце Мицане-Залите', 1),
 ('Андрей Упит', 1),
 ('Ассоциации инвалидов', 1),
 ('Лиесма', 1),
 ('Марису Митревицу', 1),
 ('Венеции', 1),
 ('Л. Азаровой', 1),
 ('Огрского муниципалитета', 1),
 ('Балтинавской средней школы', 1),
 ('Юрмале', 1),
 ('Зиедоньдарза', 1),
 ('Центре Paris Anim’ René Goscinny', 1),
 ('Валдиса Лицитиса', 1),
 ('Яниса Пликшана', 1),
 ('Blacklight MINIGOLFS', 1),
 ('Kuntzendorff', 1),
 ('Гадзюсами', 1),
 ('Альберта', 1),
 ('Лендже', 1),
 ('Юта Лембер (Juta Lember)', 1),
 ('Информационном центре', 1),
 ('Балвский край', 1),
 ('Керту Лийса Лепик (Kertu Liisa Lepik)', 1),
 ('Народном доме', 1),
 ('École Lesage', 1),
 ('Большой залы', 1),
 ('Упес', 1),
 ('Сложную Простоту', 1),
 ('Сандра Делгалве', 1),
 ('Швейцария', 1),
 ('Гара Пупа', 1),
 ('Эстония', 1),
 ('Эгия Львова', 1),
 ('Чехии', 1),
 ('Rocket Bean', 1),
 ('Северной Европы', 1),
 ('Рижский пивной квартал', 1),
 ('SIA «SND»', 1),
 ('Венеция', 1),
 ('Ханса Кристиана Андерсена', 1),
 ('Балвской начальной школы', 1),
 ('Райниса «Ясмужа»', 1),
 ('Базель', 1),
 ('Салдусском крае', 1),
 ('СССР', 1),
 ('Антра Кикусте', 1),
 ('Лаура Зунда-Поча', 1),
 ('Иветы Бренце', 1),
 ('Людмилы', 1),
 ('Стефы Булавкиной', 1),
 ('Красовскими', 1),
 ('Латвийской Академии художеств', 1),
 ('Walters & Grapaпредлагает', 1),
 ('Сигулде', 1),
 ('Hotel Pacai', 1),
 ('ICOM DEMHIST', 1),
 ('Польше', 1),
 ('Ояр', 1),
 ('Визме Белшевиче', 1),
 ('Курсас Земес', 1),
 ('Ингуны Скуя-Брейдены', 1),
 ('Ирины Богдане', 1),
 ('Йоханнеса', 1),
 ('России', 1),
 ('Огрского музея истории и искусства', 1),
 ('Литва', 1),
 ('РТУ', 1),
 ('Яниса Делгалвиса', 1),
 ('Флоренции', 1),
 ('Монета люльки', 1),
 ('Руйиене', 1),
 ('Райниса «Ясмуйжа» (', 1),
 ('СПУТНИКИ', 1),
 ('Билеты', 1),
 ('Зане Калниня\nРисунки', 1),
 ('Pacai', 1),
 ('Даце', 1),
 ('Музыкальной школы им. Эмила Дарзиня', 1),
 ('JD ART', 1),
 ('Artistar Jewels', 1),
 ('Яниса Райниса', 1),
 ('Виктория Мадерниеце', 1),
 ('Сложность', 1),
 ('Meduspils', 1),
 ('IBBY', 1),
 ('Gateris Works', 1),
 ('Латвийским центром дизайна', 1),
 ('Латгальский центр культуры', 1),
 ('Балтавилкса', 1),
 ('Ване', 1),
 ('Марта', 1),
 ('Илзе Мекша', 1),
 ('Лоте Анна Стрике', 1),
 ('Людмилы Вациетис', 1),
 ('Кулдигой', 1),
 ('Янису Балодису', 1),
 ('РА', 1),
 ('Петерис Зилбертс', 1),
 ('Карина Кеберга\nГрафическая', 1),
 ('Вилюс Дрингелис (Vilius Dringelis)', 1),
 ('Майле Гринберга (Maile Grünberg)', 1),
 ('Индрика Зебериня', 1),
 ('Херберта Эрба', 1),
 ('Арта Виксна', 1),
 ('О. Вациетис', 1),
 ('А. Бельцову', 1),
 ('C. L.Kymmel', 1),
 ('Мария Пуипайте (Marija Puipaitė)', 1),
 ('Майи Буяки', 1),
 ('Австрии', 1),
 ('Рижского залива', 1),
 ('Мары', 1),
 ('Японии', 1),
 ('Малый', 1),
 ('Янис Вайновскис', 1),
 ('Р. Суту', 1),
 ('М. Лейн', 1),
 ('Лаура Туча', 1),
 ('Знамя', 1),
 ('Гунты Крастиня', 1),
 ('Variations', 1),
 ('ТАНЦА', 1)]

✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_lg')

  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1032)'))': /github-production-release-asset/84940268/db25d0e5-cf69-4845-af7a-dd70029cc794?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-31T19%3A11%3A00Z&rscd=attachment%3B+filename%3Den_core_web_lg-3.8.0-py3-none-any.whl&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-31T18%3A10%3A55Z&ske=2026-03-31T19%3A11%3A00Z&sks=b&skv=2018-11-09&sig=uROZkAmaXAm8Rok0uqjHrTsoEhhzYohtDu11EXm8CU8%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3NDk4NTA2NywibmJmIjoxNzc0OTgxNDY3LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.NwSPLheYAfRswDPFx_gK4jexNsh4Cmgn82pKZphVsaM&response-content-disposition=attachment%3B%20filename%3Den_core_web_lg-3.8.0-py3-none-any.whl&response-content-type=application%2Foctet-stream
  WARNING: Attempting to resume incomplete download (11.1 MB/400.7 MB, attempt 1)
  WARNING: Attempting to resume incomplete download (110.5 MB/400.7 MB, attempt 2)
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))': /explosion/spacy-models/releases/download/en_core_web_lg-3.8.0/en_core_web_lg-3.8.0-py3-none-any.whl
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1032)'))': /explosion/spacy-models/releases/download/en_core_web_lg-3.8.0/en_core_web_lg-3.8.0-py3-none-any.whl
  WARNING: Attempting to resume incomplete download (186.6 MB/400.7 MB, attempt 3)
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1032)'))': /explosion/spacy-models/releases/download/en_core_web_lg-3.8.0/en_core_web_lg-3.8.0-py3-none-any.whl
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1032)'))': /explosion/spacy-models/releases/download/en_core_web_lg-3.8.0/en_core_web_lg-3.8.0-py3-none-any.whl
  WARNING: Attempting to resume incomplete download (190.9 MB/400.7 MB, attempt 4)
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', ConnectionAbortedError(10053, 'Программа на вашем хост-компьютере разорвала установленное подключение', None, 10053, None))': /explosion/spacy-models/releases/download/en_core_web_lg-3.8.0/en_core_web_lg-3.8.0-py3-none-any.whl
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001D651769450>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))': /explosion/spacy-models/releases/download/en_core_web_lg-3.8.0/en_core_web_lg-3.8.0-py3-none-any.whl
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001D651769090>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))': /explosion/spacy-models/releases/download/en_core_web_lg-3.8.0/en_core_web_lg-3.8.0-py3-none-any.whl
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001D651769BD0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))': /explosion/spacy-models/releases/download/en_core_web_lg-3.8.0/en_core_web_lg-3.8.0-py3-none-any.whl
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001D651769D10>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))': /explosion/spacy-models/releases/download/en_core_web_lg-3.8.0/en_core_web_lg-3.8.0-py3-none-any.whl
  WARNING: Attempting to resume incomplete download (190.9 MB/400.7 MB, attempt 5)

In [64]:
from collections import Counter

<class 'pandas.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   text            53 non-null     str
 1   doc             53 non-null     object
 2   tokens          53 non-null     object
 3   lemmas          53 non-null     object
 4   pos             53 non-null     object
 5   proper_nouns    53 non-null     object
 6   Tokens_NoStops  53 non-null     object
 7   Text_NoStops    53 non-null     str
 8   Doc_NoStops     53 non-null     object
 9   named_entities  53 non-null     object
 10  NE_Words        53 non-null     object
 11  chunks          53 non-null     object
dtypes: object(10), str(2)
memory usage: 5.1+ KB

In [84]:
df_ru.drop(index=[31, 39, 40, 43, 44, 47, 48, 49, 50, 51, 52], inplace=True)

In [88]:
ru_chunks_counted = dict(Counter(df_ru.chunks.explode().tolist()))

big_chunks_ru = {}
for k, v in ru_chunks_counted.items():
    if " " in k:
        if k not in big_chunks_ru:
            big_chunks_ru[k] = 0
        big_chunks_ru[k] += v

sorted(big_chunks_ru.items(), key=lambda item: item[1], reverse=True)

[('музее Ояра Вациетиса', 5),
 ('Анита Паегле', 5),
 ('доме Райниса', 5),
 ('музее Райниса', 4),
 ('Открытие выставки', 4),
 ('музее фарфора', 4),
 ('Продолжительность визита', 3),
 ('истории борьбы', 3),
 ('время экскурсии', 3),
 ('неделе дизайна', 3),
 ('выставка Скуя Брейден', 3),
 ('книге Мары Циелене', 2),
 ('книге Инесы Зандере', 2),
 ('источником вдохновения', 2),
 ('создании работ', 2),
 ('академии художеств', 2),
 ('Монета года Латвии', 2),
 ('парке Гауя', 2),
 ('охране природы', 2),
 ('посещение школы конопли', 2),
 ('посещение музея конопли', 2),
 ('посещение магазина конопли', 2),
 ('Балтийском регионе', 2),
 ('открытие выставки', 2),
 ('Дита Даноса', 2),
 ('студия ``', 2),
 ('центре культуры', 2),
 ('Терветес вина', 2),
 ('музее истории', 2),
 ('столбы заборов', 2),
 ('Зигмарс Яуя', 2),
 ('Сигне Краукле', 2),
 ('академии искусств', 2),
 ('Ночь музеев', 2),
 ('Скуя Брейден', 2),
 ('местах Латвии', 2),
 ("представления ''", 2),
 ('массой марципана', 2),
 ('дегустации сладостей', 2),
 ('день музеев личностей', 2),
 ("дар ''", 2),
 ('группы художников', 2),
 ('улица Ояра Вациетиса', 2),
 ('Ояр Вациетис', 2),
 ('доме Салгале', 2),
 ('художницы Фриды Кало', 2),
 ('технике масла', 2),
 ('музее краеведения Кекавы', 2),
 ('Гатис Шлюка', 2),
 ('художника Йоханнеса Ангебауэра', 2),
 ('замке Стамериена', 2),
 ('Иллюзионист Эджус', 2),
 ('ворота противника', 2),
 ('Цель игры', 2),
 ('Нумернес Валнис', 2),
 ('выставка Аниты Паегле', 1),
 ('адресу улица Ояра Вациетиса', 1),
 ('выставки художницы Аниты Паегле', 1),
 ('Улыбка Сфинкса Альберта', 1),
 ('книгам Юриса Звиргздиня', 1),
 ('улице Чака', 1),
 ('улице Альберта', 1),
 ('улочкам Пардогавы', 1),
 ('прудом Мары', 1),
 ('книги Юриса Звиргздиня', 1),
 ('иллюстрациях время', 1),
 ('поколению читателей', 1),
 ('школу имени Яниса Розентала', 1),
 ('сотрудничество художницы', 1),
 ('Гара Пупа', 1),
 ('Яня Сета', 1),
 ('стиль иллюстрации', 1),
 ('произведения Мары Циелене', 1),
 ('Яниса Балтавилкса', 1),
 ('основательниц премии Яниса Балтавилка', 1),
 ('биенналях иллюстрации', 1),
 ('биеннале иллюстрации', 1),
 ('триеннале иллюстрации', 1),
 ('книге М. Циелене', 1),
 ('Банком Латвии', 1),
 ('Монета люльки', 1),
 ('книгам Анита Паегле', 1),
 ('множество признаний', 1),
 ('премию Пастариньша', 1),
 ('премию Индрика Зебериня', 1),
 ('книги Балтии', 1),
 ('ходы часов', 1),
 ('список иллюстраторов мира', 1),
 ('развитие искусства', 1),
 ('году художница', 1),
 ('премию Балтавилкса', 1),
 ('иллюстрации – премию Ханса Кристиана Андерсена', 1),
 ('мероприятия —', 1),
 ('посетители винодельни', 1),
 ('время дегустаций', 1),
 ('продукты винодельни', 1),
 ('видов вина', 1),
 ('интереса посетителей', 1),
 ('территории хозяйства', 1),
 ('ростом яблока', 1),
 ('конца мая', 1),
 ('праздника Лиго —', 1),
 ('приключение посетители', 1),
 ('берегу Гауи', 1),
 ('Музей жуликов', 1),
 ('Историю плотника Гауи', 1),
 ('посетителям возможность', 1),
 ('истории Латвии', 1),
 ('работу инспекторов', 1),
 ('методами работы инспекторов', 1),
 ('охраной природы', 1),
 ('инспектору Марису Митревицу', 1),
 ('выставка Аниты Савицки', 1),
 ('выставки художника', 1),
 ('украшениям Аниты Савицки', 1),
 ('основательницы бренда', 1),
 ('посвящение художницы', 1),
 ('мировоззрением Райниса', 1),
 ('Ясмуже Анита Савицка', 1),
 ('произведения Яниса Райниса', 1),
 ('поиску красоты', 1),
 ('света человека', 1),
 ('процессе создания', 1),
 ('пейзажи Латгалии –', 1),
 ('отражения света', 1),
 ('диалог текстур', 1),
 ('украшений – кольца', 1),
 ('разнообразие почерка художницы', 1),
 ('работах Анита Савицка', 1),
 ('металлы – серебро', 1),
 ('игру материалов', 1),
 ('Анита Савицка начала', 1),
 ('дизайном украшений', 1),
 ('Анита Савицка', 1),
 ('магистратуру отделения', 1),
 ('Академии художеств', 1),
 ('искусство украшений', 1),
 ('студии семьи Эрмини', 1),
 ('членом жюри', 1),
 ('замке Яунмоку', 1),
 ('празднике замка Яунмоку', 1),
 ('недель взволнованности', 1),
 ('видео проекциями', 1),
 ('Часть студентов', 1),
 ('истории призрака', 1),
 ('окрестностях замка Яунмоку', 1),
 ('Дух легенды', 1),
 ('работа —', 1),
 ('Академии Искусств', 1),
 ('рамках изучения радости', 1),
 ('крае Продолжительность', 1),
 ('бронирования экскурсии', 1),
 ('практике выращивания конопли', 1),
 ('полям конопли', 1),
 ('преимуществах конопли', 1),
 ('школе конопли', 1),
 ('музее конопли', 1),
 ('Музей конопли', 1),
 ('символом наследия', 1),
 ('применений конопли', 1),
 ('музей конопли', 1),
 ('роль конопли', 1),
 ('мир конопли', 1),
 ('гидом Андрисом', 1),
 ('происхождение конопли', 1),
 ('историю конопли', 1),
 ('применения конопли', 1),
 ('преимущества выращивания конопли', 1),
 ('роли конопли', 1),
 ('восстановлении почвы', 1),
 ('поглощении углерода', 1),
 ('программу кураторов', 1),
 ('зал ``', 1),
 ('демонстрации креативности', 1),
 ("дизайнеров ''", 1),
 ('председатель правления', 1),
 ('Тимур Томсон', 1),
 ('чувствительность дизайнеров региона', 1),
 ('взаимодействию материалов', 1),
 ('области дизайна мебели', 1),
 ('языком дизайна', 1),
 ('чувствительности материала', 1),
 ('поколение дизайнеров', 1),
 ('темы идентичности', 1),
 ('руководитель проекта выставки', 1),
 ('центра дизайна', 1),
 ('концепция выставки', 1),
 ('отбор работ', 1),
 ("янтарь ''", 1),
 ('Авторы выставки', 1),
 ('Артис Ниманис', 1),
 ('Эмма София', 1),
 ('Даце Суна', 1),
 ('Мантас Лесаускас', 1),
 ('Вилюс Дрингелис', 1),
 ('Люция Костива', 1),
 ('Сийм Карро', 1),
 ('Тереза РА', 1),
 ('Аннике Лайго', 1),
 ('Керту Лийса Лепик', 1),
 ('Майле Гринберга', 1),
 ('Юта Лембер', 1),
 ('Марья Маеметс', 1),
 ('Кураторы выставки', 1),
 ('агентство ``', 1),
 ('Сценографию экспозиции', 1),
 ('Бригита Була', 1),
 ('Кирилл Кирасиров', 1),
 ('центром дизайна', 1),
 ('форумом дизайна', 1),
 ('агентством ``', 1),
 ('момента создания платформа', 1),
 ('фестивале дизайна', 1),
 ('замке Лита', 1),
 ('Вильнюсе выставка', 1),
 ('гостей Лиепаи', 1),
 ('выставка украшений', 1),
 ('вышивок художницы Ирены Штейнберги', 1),
 ('название бренда', 1),
 ('художницы Ирены Штейнберги', 1),
 ('время обучения', 1),
 ('Париже –', 1),
 ('почерк Ирены', 1),
 ('столицы моды', 1),
 ('частью ее', 1),
 ('Ее работы', 1),
 ('коллекции художницы', 1),
 ('дегустации –', 1),
 ('продукции предприятия', 1),
 ('вкус фруктов', 1),
 ('методом нагрева', 1),
 ('6-7 видов вин', 1),
 ('ВЫСТАВКА ТВОРЧЕСКИХ РАБОТ УЧАЩИХСЯ', 1),
 ('края ПОСВЯЩЕНИЕ', 1),
 ('ПРАЗДНИКУ ПЕСНИ', 1),
 ('ТАНЦА ШКОЛЬНОЙ МОЛОДЕЖИ', 1),
 ('работ учащихся', 1),
 ('Послание выставки', 1),
 ('области культуры', 1),
 ('Индра Кэйша', 1),
 ('Праздника песни', 1),
 ('деятельности детей', 1),
 ('процессе Праздника песни', 1),
 ('школ края', 1),
 ('сияние ”', 1),
 ('Оценщики работ', 1),
 ('качества работ', 1),
 ('креативности учащихся', 1),
 ('туре конкурса', 1),
 ('Мартин Пукс', 1),
 ('учитель Алдис Войтс', 1),
 ('Эгия Львова', 1),
 ('Арта Виксна', 1),
 ('учитель Индра Кэйша', 1),
 ('Тина Леоне', 1),
 ('Лига Тумина', 1),
 ('Оскар Сидельникс', 1),
 ('учитель Антра Кикусте', 1),
 ('Виктория Мадерниеце', 1),
 ('учитель Йоланта Дундене', 1),
 ('дворце ВЭФ', 1),
 ('фруктов — винограда', 1),
 ('гостям вино', 1),
 ('Винодел Сандрис Лайзанс', 1),
 ('дегустации вина', 1),
 ('берегах реки Тервете', 1),
 ('Хозяйка Даце', 1),
 ('мероприятий —', 1),
 ('владельцы винодельни', 1),
 ('среды города –', 1),
 ('столбам заборов', 1),
 ('развитие Огре', 1),
 ('строительство дач', 1),
 ('фактором формирования', 1),
 ('местах города –', 1),
 ('границ собственности', 1),
 ('вкуса владельцев', 1),
 ('общество развития', 1),
 ('дачи Огре', 1),
 ('столбах заборов', 1),
 ('истоки города Огре', 1),
 ('территории Огре', 1),
 ('технологии изготовления', 1),
 ('Цель выставки', 1),
 ('идею сохранения', 1),
 ('восстановления заборов', 1),
 ('среды Огре', 1),
 ('день открытия –', 1),
 ('участия просьба', 1),
 ('Автор идеи', 1),
 ('куратор выставки', 1),
 ('Зигмарс Яуя Руководитель проекта', 1),
 ('Автор фотографий', 1),
 ('Улдис Апинис Художники', 1),
 ('части выставки', 1),
 ('Карина Кеберга', 1),
 ('реклама выставки', 1),
 ('Зане Калниня Рисунки', 1),
 ('Мунде Автор видеорассказа', 1),
 ('Петерис Зилбертс Описание технологии изготовления', 1),
 ('Лаура Зунда-Поча Измерения', 1),
 ('Лаура Зунда-Поча', 1),
 ('Илзе Мекша', 1),
 ('Интарс Сниедзе', 1),
 ('музея истории', 1),
 ('Янис Зиньгитис', 1),
 ('Элина Церпа', 1),
 ('Лаура Туча', 1),
 ('Марис Гросбахс', 1),
 ('Нилс Микельсонс', 1),
 ('Гунтарс Андерсонс Выставка', 1),
 ('музеем истории', 1),
 ('семьям рода Циниш', 1),
 ('Янису Балодису', 1),
 ('общества развития', 1),
 ('членам семей', 1),
 ('создании выставки', 1),
 ('руки кисть…', 1),
 ('учительницы Иветы Бренце', 1),
 ('студию Валдиса Лицитиса', 1),
 ('работами художников', 1),
 ('взгляд Марите', 1),
 ('теплотой души', 1),
 ('Талси желающих', 1),
 ('имени Фрицис', 1),
 ('поезд Фрицис', 1),
 ('даритель улыбок', 1),
 ('Часы работы', 1),
 ('набережной озера Талси –', 1),
 ('Солнце ”', 1),
 ('водителя Фрициса –', 1),
 ('Услуги гида', 1),
 ('место проведения мероприятий', 1),
 ('центр культуры', 1),
 ('зал репетиций оркестра', 1),
 ('центром культуры', 1),
 ('центре посетителей', 1),
 ('лицо Добеле', 1),
 ('истории улиц', 1),
 ('зданий города', 1),
 ('преобразованиям города', 1),
 ('историям улиц', 1),
 ('картами Добеле', 1),
 ('названия улиц', 1),
 ('функции зданий', 1),
 ('облик города', 1),
 ('Добеле десятилетия', 1),
 ('зданий –', 1),
 ('истории Добеле', 1),
 ('автор содержания выставки Ундине Крузе', 1),
 ('время постройки', 1),
 ('месте сада', 1),
 ('Лиене Лауриновича', 1),
 ('Ундине Крузе', 1),
 ('музее Андрея Упита', 1),
 ('года кафедра графики', 1),
 ('музеем Андрея Упита', 1),
 ('адресу улица Бривибас', 1),
 ('Графики деревни Суну', 1),
 ('темой акции', 1),
 ('года –', 1),
 ('Мальчишки деревни Суну', 1),
 ('Андрей Упит', 1),
 ('временем ценности глазами', 1),
 ('Медведь счастья живет', 1),
 ('деревне Суну', 1),
 ('Медведь счастья –', 1),
 ('описании выставки', 1),
 ('преподаватели кафедры графики', 1),
 ('музея Андрея Упита', 1),
 ('руководитель музея Илзе Пукье', 1),
 ('Гостей мероприятия', 1),
 ('квартета отделения', 1),
 ('школы им. Эмила Дарзиня', 1),
 ('Алисе Крокфорда', 1),
 ('Арта Роланда Лайцане', 1),
 ('Валерия Сосова', 1),
 ('Агрит Ванаг', 1),
 ('Вильхельм Бандерс', 1),
 ('Зельда Виктория Янсоне', 1),
 ('Лоте Анна Стрике', 1),
 ('перерыва Скуя Брейден', 1),
 ('этаже музея', 1),
 ('частях экспозиции', 1),
 ('музея фарфора –', 1),
 ('– работы Скуя Брейден', 1),
 ('кулаками ”', 1),
 ('идентичность художниц Ингуны Скуя-Брейдены', 1),
 ('Мелисы Скуя-Брейдены', 1),
 ('доску доказательств', 1),
 ('роща одета', 1),
 ('двор ”', 1),
 ('улучшения Антропоцена', 1),
 ('выставка –', 1),
 ('Скуи Брейден', 1),
 ('экспозицией “', 1),
 ('реки ”', 1),
 ('Латвии керамисток', 1),
 ('Мелиса зрелы', 1),
 ('медиумом керамики', 1),
 ('наследие Скуя Брейден', 1),
 ('траектории новаторства', 1),
 ('поиски формообразования', 1),
 ('Работы выставки', 1),
 ('каналах музея', 1),
 ('Плакат выставки', 1),
 ('Автор концепции дизайна Артис Тауриньш', 1),
 ('автор оформления плаката Арнис Стасаитис', 1),
 ('работами Скуя Брейден', 1),
 ('Автор фото Гвидо Кайонс', 1),
 ('гордость Латвии', 1),
 ('Владелец ООО', 1),
 ('пчеловод Янис Вайновскис', 1),
 ('гордостью ООО', 1),
 ('продукт – мед', 1),
 ('Длительность экскурсии', 1),
 ('размера группы', 1),
 ('разнообразием меда', 1),
 ('сезон возможность', 1),
 ('откачке меда', 1),
 ('костюмы пчеловодов', 1),
 ('развести костёр', 1),
 ('период производство', 1),
 ('изготовлением свечей', 1),
 ('волости Энгуре', 1),
 ('гостям отдых', 1),
 ('дегустацию рыбы', 1),
 ('курляндском диалекте', 1),
 ('юбилярам –', 1),
 ('временам года', 1),
 ('летом –', 1),
 ('развлечений –', 1),
 ('обработке рыбы', 1),
 ('блюда –', 1),
 ('десерт Горячие', 1),
 ('копчения налимов', 1),
 ('ночь –', 1),
 ('озере Энгуре', 1),
 ('хозяев рыбу', 1),
 ('Дегустация пива', 1),
 ('начала пивоварня Ужавас', 1),
 ('условий Латвии', 1),
 ('варки пива', 1),
 ('соображений доступности', 1),
 ('вода –', 1),
 ('скважин глубиной', 1),
 ('часы зимой', 1),
 ('сайте пивоварни', 1),
 ('принципах компании', 1),
 ('л кружке', 1),
 ('дегустация пива', 1),
 ('этаже пивоварни', 1),
 ('виды пива', 1),
 ('улице Базницас', 1),
 ('открытие выставки картин художницы Марии Лейн', 1),
 ('время живет', 1),
 ('работа М. Лейн', 1),
 ('художницы Виктории Рено', 1),
 ('время Мария', 1),
 ('Ассоциации инвалидов', 1),
 ('выставке Марии', 1),
 ('искусствовед Елизавета Гроце', 1),
 ('Картины Марии —', 1),
 ('ее работы', 1),
 ('года ее работы', 1),
 ('Картины Марии', 1),
 ('сборники пьес Ассоциации драматургов', 1),
 ('обложку рассказа Б. Зуйане', 1),
 ('ее выставки', 1),
 ('выставку Мария Лейн', 1),
 ('Господин Плуме', 1),
 ('сады сидроварни', 1),
 ('Господине Плуме', 1),
 ('сидр дома', 1),
 ('договоренности сидровар', 1),
 ('аудитория —', 1),
 ('клиентом месте', 1),
 ('душе конфеты', 1),
 ('экскурсию –', 1),
 ('сопровождении гида', 1),
 ('игру чувств', 1),
 ('перетягивание мяча', 1),
 ('праздников – свадеб', 1),
 ('дней рождения', 1),
 ('мероприятий –', 1),
 ('упаковки сладостей', 1),
 ('Сладости Скривери', 1),
 ('гостей –', 1),
 ('встречаястолетие Латвии', 1),
 ('Риге славу', 1),
 ('цитадели пивоварения', 1),
 ('объединившисьв Рижский пивной квартал', 1),
 ('центре города', 1),
 ('улице А. Бриана', 1),
 ('здания пивоварни', 1),
 ('углу улиц Бруниниеку', 1),
 ('здания пивоварниGust', 1),
 ('пивоварня посольство', 1),
 ('пивовары иторговцы', 1),
 ('Любители пива', 1),
 ('Пивоварни квартала', 1),
 ('мероприятиями иконцертами', 1),
 ('пивоварня фон Стрика', 1),
 ('разнообразием сортов пива', 1),
 ('знатоки фольклора', 1),
 ('пивоварен Литвы', 1),
 ('пивоварней Латвии', 1),
 ('сортов пива', 1),
 ('дегустацией кофе', 1),
 ('любители кофе', 1),
 ('улице Вираудас', 1),
 ('Ленджском волости', 1),
 ('обжаркой кофе', 1),
 ('виды кофе', 1),
 ('процессе обжарки', 1),
 ('росте обжарки', 1),
 ('демонстрацию процесса обжарки кофе', 1),
 ('Посещения обжарки', 1),
 ('наслаждения кофе –', 1),
 ('Продолжительность посещения обжарки', 1),
 ('улице Калькю', 1),
 ('времен герцога Якоба', 1),
 ('торговля кофе', 1),
 ('чашечку кофе', 1),
 ('площади города', 1),
 ('Курсас Земес', 1),
 ('обжарок кофе', 1),
 ('дегустация кофе', 1),
 ('основе производства кофе', 1),
 ('рецептуру обжарки', 1),
 ('гамму вкусов', 1),
 ('ароматов кофе', 1),
 ('время дегустации', 1),
 ('полках магазинов', 1),
 ('нюансами вкуса', 1),
 ('аромата кофе', 1),
 ('завариванию кофе', 1),
 ('руководством бариста', 1),
 ('способами приготовления кофе', 1),
 ('ценителям кофе', 1),
 ('вовлечении Латвии', 1),
 ('мир кофе', 1),
 ('чашечкой кофе', 1),
 ('рамках цикла ``', 1),
 ("день музеев личностей ''", 1),
 ('дом Райниса', 1),
 ('музей Александра Чака', 1),
 ('музей Романа Суты', 1),
 ('Александры Бельцовой', 1),
 ('музей Ояра Вациетиса', 1),
 ('музей Яниса Акурейтера –', 1),
 ('Начало путешествия', 1),
 ('улица Базницас', 1),
 ("фотография матери Аспазии ''", 1),
 ('экспозиции дома Райниса', 1),
 ('фотография матери Аспазии Маргариты Розенберги', 1),
 ('отношениях Аспазии', 1),
 ('экспозиции музея', 1),
 ('музее Александра Чака', 1),
 ('улица Лачплеша', 1),
 ('сборнике стихов Чака', 1),
 ('сборник стихов Александра Чака', 1),
 ('Милде Гринфелде', 1),
 ('Милде стихи', 1),
 ('течение жизни Чака сборник', 1),
 ('время войны', 1),
 ('Сборник стихов ``', 1),
 ('музее Романа Суты', 1),
 ('улица Элизабетес 57а-26', 1),
 ('Провокация модернистам', 1),
 ("названием `` каспарсонсиада ''", 1),
 ('выставка модернистов', 1),
 ('Р. Суту', 1),
 ('А. Бельцову', 1),
 ('жизни общества', 1),
 ('конфликт мнений поколений', 1),
 ('провокация молодым', 1),
 ('художника Рейнхольда Каспарсона', 1),
 ('плакат выставки', 1),
 ('Р. Сута', 1),
 ('выставки Рейнхольда Каспарсона', 1),
 ('посещения музея Романа Суты', 1),
 ('рассказ ``', 1),
 ('Ояре Вациетисе', 1),
 ("углу ''", 1),
 ('года Солженицын', 1),
 ('письмо делегатам', 1),
 ('съезда писателей СССР', 1),
 ('отмены цензуры', 1),
 ('`` Частушки', 1),
 ('полях журнала', 1),
 ('Визме Белшевиче', 1),
 ('время Ояр Вациетис', 1),
 ('Жена Ояра Вациетиса Людмила Азарова', 1),
 ('О. Вациетис', 1),
 ('Л. Азаровой', 1),
 ('черновик объяснения О. Вациетиса', 1),
 ('Завершение путешествия', 1),
 ('рассказом ``', 1),
 ('дневник Акурейтера', 1),
 ('музее Яниса Акурейтера', 1),
 ('времени Янис Акурейтер', 1),
 ('названием ``', 1),
 ('славе вождизма', 1),
 ('Цель Дня музеев личностей', 1),
 ('внимание общества', 1),
 ('музеям личностей', 1),
 ('хранилищам знаний', 1),
 ('вкладе личностей', 1),
 ('образе жизни', 1),
 ('Капрезе Микеланджело', 1),
 ('конференции музеев личностей', 1),
 ('дня музеев личностей', 1),
 ('субботу апреля', 1),
 ('музеи личностей', 1),
 ('Ассоциацией музеев личностей Италии', 1),
 ("Дома памяти ''", 1),
 ('советом музеев', 1),
 ('комитетом музеев литературы', 1),
 ('Цена билета', 1),
 ('популяризации музеев', 1),
 ('Художница Сандра Делгалве живет', 1),
 ('художника Яниса Делгалвиса', 1),
 ('поклонницей творчества', 1),
 ('этаже студии', 1),
 ('руки Сандры', 1),
 ('глазах Сандры Делгалве Фрида Кало', 1),
 ('образцом женственности', 1),
 ('Фриде Кало', 1),
 ('будние дни', 1),
 ('Дегустации вин', 1),
 ('виды напитков', 1),
 ('берегах реки Абавы', 1),
 ('возможность проведения семинаров', 1),
 ('обрядов венчания', 1),
 ('винодельня Абавы', 1),
 ('символом стрекозу', 1),
 ('долине Абавы', 1),
 ('даров долины Абавы', 1),
 ('дизайн этикетки', 1),
 ('Выставка картин Гриеты Брамане', 1),
 ('Марии Тимофеевой', 1),
 ('резиденции Райниса', 1),
 ('резиденция Райниса', 1),
 ('улица Яниса Пликшана', 1),
 ('открытие выставки картин Гриеты Брамане', 1),
 ('группа поэтесс', 1),
 ('памяти женщин', 1),
 ('гамма эмоций', 1),
 ('поисках идентичности', 1),
 ('отражение опыта', 1),
 ('открытии выставки', 1),
 ('необъяснимости мира', 1),
 ('непостижимость мира', 1),
 ('осмотр выставки', 1),
 ('секреты производства мороженого', 1),
 ('временем ценностей', 1),
 ('фабрика мороженого', 1),
 ('улице Упес', 1),
 ('производству мороженого', 1),
 ('продукты мороженого', 1),
 ('количество посетителей', 1),
 ('группы участие', 1),
 ('Серия мероприятий', 1),
 ('юбилею Людмилы Азаровой Начав серию мероприятий', 1),
 ('юбилею поэтессы', 1),
 ('переводчицы Людмилы Азаровой', 1),
 ('Внучка Людмилы Азаровой', 1),
 ('Ояра Вациетиса', 1),
 ('художница Марта Андерсоне', 1),
 ('коллекцию рисунков', 1),
 ('Выставка Марты Андерсоне', 1),
 ('рода дневник', 1),
 ('решения –', 1),
 ('образы людей', 1),
 ('время минимализм', 1),
 ('визуализация мысли', 1),
 ('посетителя выставки', 1),
 ('призму юмора', 1),
 ('куратор выставки Даце Мицане-Залите', 1),
 ('тон поэзии бабушек Людмилы', 1),
 ('порядок мира', 1),
 ('почерке внучки', 1),
 ('дом бабушек', 1),
 ('дедушек Ояра', 1),
 ('Людмилы Вациетис', 1),
 ('Марты Андерсоне музею', 1),
 ('юбилею Людмилы Азаровой', 1),
 ('выставка скульптур металлиста Гинта Гринберга', 1),
 ('Фотовыставка карикатуриста Гатиса Шлюки', 1),
 ('марта фотовыставка Гатиса Шлюки', 1),
 ('время прогулок', 1),
 ('улицам Риги', 1),
 ('рода охота', 1),
 ('рода рисованием', 1),
 ("фотография ''", 1),
 ("рисунок светом ''", 1),
 ('точек зрения', 1),
 ('Выставка картин Майи Буяки', 1),
 ('доме Сталгены', 1),
 ('место Майи', 1),
 ('деревня Ване', 1),
 ('образование Майя', 1),
 ('Кримунском волосте', 1),
 ('искусству Айя Принце', 1),
 ('художницы Вирджинии Контареллы', 1),
 ('адрес Йоханнеса', 1),
 ('сайте проекта', 1),
 ('км поход', 1),
 ('волости Букайши', 1),
 ('друзьямии семьей', 1),
 ('территории волости Букайши Добельского', 1),
 ('летчика Х. Цукура', 1),
 ('Протяженность маршрута', 1),
 ('истории Букайши', 1),
 ('местев Букайши', 1),
 ('выставка Марты Готлиб', 1),
 ('выставка художницы Марты Готлиб', 1),
 ('манере реализма', 1),
 ('принципам живописи', 1),
 ('гармонию тона', 1),
 ('школу дизайна', 1),
 ('Интерес художницы', 1),
 ('использованием техники', 1),
 ('живописи маслом', 1),
 ('Стиль М.Готлиб', 1),
 ('иллюстрациях птиц', 1),
 ('технику художница', 1),
 ('маслом М.Готлиб', 1),
 ('художников Латвии', 1),
 ('источник вдохновения', 1),
 ('искусстве М.Готлиб', 1),

In [ ]:
def clean_ru(row):
    new_list = []
    for word in row:
        if word in nlp_ru.Defaults.stop_words:
            continue
        if word in '!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~–—“”·':
            continue
        if word in ["\n", "\n\n", "\r", "\r\n", "\xa0", "\n\xa0", "\n\xa0\n", "\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0"]:
            continue
        new_list.append(word)
    return new_list
clean_lemmas = df_ru.lemmas.apply(clean_ru)
# df_ru.lemmas[0]

In [ ]:
Counter(clean_lemmas.explode().tolist())

Counter({'выставка': 145,
         'музей': 78,
         'год': 72,
         'время': 51,
         'экскурсия': 49,
         'дегустация': 43,
         'работа': 42,
         'латвия': 41,
         'место': 37,
         'история': 36,
         'возможность': 32,
         'семья': 31,
         'различный': 30,
         'художница': 29,
         'дизайн': 28,
         'конопля': 28,
         'кофе': 28,
         'улица': 26,
         'предлагать': 26,
         'игра': 25,
         'представить': 24,
         'город': 24,
         'искусство': 24,
         'дом': 23,
         'латвийский': 23,
         'мероприятие': 23,
         'посетитель': 23,
         'создать': 22,
         'друг': 22,
         'являться': 21,
         'международный': 21,
         'рига': 19,
         '2025': 19,
         'край': 19,
         'иллюстрация': 18,
         'винодельня': 18,
         'новый': 18,
         'местный': 18,
         'пиво': 18,
         'гольф': 18,
         'персональный': 17,
         'получить': 17,
         'час': 17,
         'гость': 17,
         'современный': 17,
         'группа': 17,
         'первый': 16,
         'мир': 16,
         'райнис': 16,
         'мини': 16,
         'вино': 15,
         'приглашать': 15,
         'узнать': 15,
         'Для': 15,
         'творческий': 15,
         'посещение': 15,
         'доступный': 15,
         'книга': 14,
         'рижский': 14,
         'школа': 14,
         'картина': 14,
         'мария': 14,
         'личность': 14,
         'пивоварня': 14,
         'ояра': 13,
         'открытие': 13,
         'участвовать': 13,
         'попробовать': 13,
         'художник': 13,
         'человек': 13,
         'зал': 13,
         'фотография': 13,
         'февраль': 13,
         'вациетиса': 12,
         'анита': 12,
         'художественный': 12,
         'янис': 12,
         'продукт': 12,
         'напиток': 12,
         '1': 12,
         'познакомиться': 12,
         'культурный': 12,
         'среда': 12,
         'интересный': 12,
         'центр': 12,
         'исторический': 12,
         'день': 12,
         'аспазия': 12,
         'ребёнок': 11,
         'детский': 11,
         'открыть': 11,
         'насладиться': 11,
         'особый': 11,
         'название': 11,
         'визуальный': 11,
         'найти': 11,
         'балтийский': 11,
         'путешествие': 11,
         'добеле': 11,
         'скуя': 11,
         'вместе': 10,
         'природа': 10,
         'цель': 10,
         'большой': 10,
         'экспозиция': 10,
         'вкус': 10,
         'фрицис': 10,
         'брейден': 10,
         'март': 10,
         'премия': 9,
         'конкурс': 9,
         'август': 9,
         '10': 9,
         'вид': 9,
         'май': 9,
         'украшение': 9,
         'июль': 9,
         'производство': 9,
         'пространство': 9,
         'автор': 9,
         'отправиться': 9,
         'жизнь': 9,
         'рассказ': 9,
         'двор': 9,
         'рыбацкий': 9,
         'рыба': 9,
         'живопись': 9,
         'обжарка': 9,
         'паегле': 8,
         'два': 8,
         'награда': 8,
         'возможный': 8,
         'апрель': 8,
         'говорить': 8,
         'материал': 8,
         'студия': 8,
         'часть': 8,
         'приобрести': 8,
         'желать': 8,
         'житель': 8,
         'ждать': 8,
         'отдых': 8,
         'хороший': 8,
         'столб': 8,
         'посетить': 8,
         'написать': 8,
         'фарфор': 8,
         'вкусный': 8,
         'людмила': 8,
         '4': 7,
         'прогулка': 7,
         'чак': 7,
         'рассказывать': 7,
         'академия': 7,
         'сотрудничество': 7,
         'уникальный': 7,
         'италия': 7,
         'яблоко': 7,
         'включить': 7,
         'ягода': 7,
         'продолжительность': 7,
         'смочь': 7,
         '2': 7,
         'праздник': 7,
         'познавательный': 7,
         'взгляд': 7,
         'опыт': 7,
         'раскрывать': 7,
         'свет': 7,
         'создавать': 7,
         'начать': 7,
         '12': 7,
         '31': 7,
         'летний': 7,
         'предварительный': 7,
         'подходить': 7,
         'концертный': 7,
         '3': 7,
         'tactile': 7,
         'baltics': 7,
         'впервые': 7,
         '8': 7,
         '5': 7,
         'собственный': 7,
         'наслаждаться': 7,
         'провести': 7,
         'забор': 7,
         'городской': 7,
         'старый': 7,
         'здание': 7,
         'ценность': 7,
         'разный': 7,
         'важный': 6,
         'создание': 6,
         'увидеть': 6,
         'взрослый': 6,
         'разнообразный': 6,
         'визит': 6,
         'хозяйство': 6,
         'больший': 6,
         'компания': 6,
         'известный': 6,
         'форма': 6,
         'сша': 6,
         'использовать': 6,
         'париж': 6,
         'замок': 6,
         'После': 6,
         'поле': 6,
         'наследие': 6,
         'янтарь': 6,
         'участие': 6,
         'общий': 6,
         'выбрать': 6,
         'технология': 6,
         'душа': 6,
         'проект': 6,
         'представлять': 6,
         'излучать': 6,
         'учитель': 6,
         'молодой': 6,
         'огре': 6,
         'бетонный': 6,
         'талси': 6,
         'вверх': 6,
         'встречаться': 6,
         'meduspils': 6,
         'мёд': 6,
         'зима': 6,
         'сладость': 6,
         'мяч': 6,
         'азаров': 6,
         'мороженое': 6,
         'филиальный': 6,
         'библиотека': 6,
         'бильярд': 6,
         'игрок': 6,
         'сентябрь': 5,
         'состояться': 5,
         'поколение': 5,
         'поздний': 5,
         'монета': 5,
         'пять': 5,
         'развитие': 5,
         'высокий': 5,
         'производить': 5,
         'создаваться': 5,
         'сезон': 5,
         'небольшой': 5,
         'раз': 5,
         'маленький': 5,
         'эмоция': 5,
         'браконьерство': 5,
         'посвятить': 5,
         'внимание': 5,
         'идея': 5,
         'престижный': 5,
         'разнообразие': 5,
         'заниматься': 5,
         'солнце': 5,
         'радость': 5,
         'требоваться': 5,
         'магазин': 5,
         'увлекательный': 5,
         'гид': 5,
         '17': 5,
         'приглашаться': 5,
         'дизайнерский': 5,
         'традиционный': 5,
         'три': 5,
         'мастерство': 5,
         'индивидуальный': 5,
         'коллекция': 5,
         'вина': 5,
         'культура': 5,
         'школьный': 5,
         'тёплый': 5,
         'любовь': 5,
         'деревня': 5,
         'жить': 5,
         'организовать': 5,
         'рисунок': 5,
         'примерно': 5,
         'общество': 5,
         'маршрут': 5,
         'актуальный': 5,
         'бесплатный': 5,
         'рабочий': 5,
         'род': 5,
         'кулдига': 5,
         '30': 5,
         'eur': 5,
         'латгальский': 5,
         'помещение': 5,
         'комната': 5,
         'сад': 5,
         'этаж': 5,
         'работать': 5,
         'плакат': 5,
         'волость': 5,
         'отличный': 5,
         'старинный': 5,
         'слово': 5,
         '18': 5,
         'сорт': 5,
         'сборник': 5,
         'сидр': 5,
         'фабрика': 5,
         'угол': 5,
         'предмет': 5,
         'вациетис': 5,
         'фрида': 5,
         'кало': 5,
         'техника': 5,
         'масло': 5,
         'абавы': 5,
         'стол': 5,
         'майя': 5,
         'поход': 5,
         'птица': 5,
         '19': 4,
         'мара': 4,
         'циелене': 4,
         'приключение': 4,
         'окончить': 4,
         'графический': 4,
         'вильнюс': 4,
         'европейский': 4,
         'франция': 4,
         'золотой': 4,
         '2014': 4,
         '25': 4,
         'зилвер': 4,
         'предложить': 4,
         '1,5': 4,
         'зависимость': 4,
         'территория': 4,
         'охота': 4,
         'отправляться': 4,
         '7': 4,
         'фото': 4,
         'борьба': 4,
         'берег': 4,
         'парк': 4,
         'инспектор': 4,
         'повседневный': 4,
         '6': 4,
         'бренд': 4,
         'диалог': 4,
         'савицка': 4,
         'поиск': 4,
         'процесс': 4,
         'латгалии': 4,
         '20': 4,
         'отделение': 4,
         'милан': 4,
         'неделя': 4,
         'тема': 4,
         'атмосфера': 4,
         'изображение': 4,
         'добро': 4,
         'пожаловать': 4,
         'выращивание': 4,
         'использование': 4,
         'регион': 4,
         'роль': 4,
         'исследовать': 4,
         'куратор': 4,
         'дизайнер': 4,
         'идентичность': 4,
         'интимный': 4,
         'июнь': 4,
         'проводиться': 4,
         'бесплатно': 4,
         'качество': 4,
         'частный': 4,
         'семейный': 4,
         'предлагаться': 4,
         'пройти': 4,
         'страна': 4,
         'тур': 4,
         'основный': 4,
         'юбилей': 4,
         'длиться': 4,
         'век': 4,
         'sia': 4,
         'рука': 4,
         'знание': 4,
         'яркий': 4,
         'образ': 4,
         'поездка': 4,
         'начало': 4,
         'условие': 4,
         'gors': 4,
         'карта': 4,
         'мемориальный': 4,
         'андрей': 4,
         'акция': 4,
         'вода': 4,
         'ооо': 4,
         'медовый': 4,
         'приятный': 4,
         'конфета': 4,
         'море': 4,
         'хозяин': 4,
         'развлечение': 4,
         'лето': 4,
         'музыка': 4,
         'мечта': 4,
         'пивной': 4,
         'квартал': 4,
         'любитель': 4,
         'проходить': 4,
         'творчество': 4,
         'стих': 4,
         'дар': 4,
         'опубликовать': 4,
         'письмо': 4,
         'ояр': 4,
         'марта': 4,
         'рисовать': 4,
         'гатис': 4,
         'букайши': 4,
         'м.готлиб': 4,
         'площадка': 4,
         '18:00': 3,
         'адрес': 3,
         'улыбка': 3,
         'зимний': 3,
         'сказка': 3,
         'кот': 3,
         'вещь': 3,
         'источник': 3,
         'вдохновение': 3,
         'мысль': 3,
         'лично': 3,
         'близкий': 3,
         'родиться': 3,
         'имя': 3,
         'художество': 3,
         'произведение': 3,
         'графика': 3,
         'эстония': 3,
         '2013': 3,
         'признание': 3,
         '1-й': 3,
         'область': 3,
         'выдающийся': 3,
         'октябрь': 3,
         'фрукт': 3,
         'яблочный': 3,
         'закусками': 3,
         'интерес': 3,
         'дегустировать': 3,
         'бренди': 3,
         'отметить': 3,
         'рост': 3,
         'национальный': 3,
         'охрана': 3,
         'метод': 3,
         'период': 3,
         'популярный': 3,
         'Её': 3,
         'поэзия': 3,
         'пейзаж': 3,
         'почерк': 3,
         'мастер': 3,
         'класс': 3,
         'член': 3,
         'яунмоку': 3,
         'прошлое': 3,
         'сто': 3,
         'поэтический': 3,
         'кофейный': 3,
         'движение': 3,
         'рамка': 3,
         'необходимый': 3,
         'возраст': 3,
         'прогуляться': 3,
         'применение': 3,
         'включать': 3,
         'интерактивный': 3,
         'obelisk': 3,
         'farm': 3,
         'символ': 3,
         'богатый': 3,
         'единственный': 3,
         'гордость': 3,
         'необычный': 3,
         'устойчивый': 3,
         'помощь': 3,
         'программа': 3,
         'древний': 3,
         'исток': 3,
         'изучить': 3,
         'текстиль': 3,
         'способствовать': 3,
         'климатический': 3,
         'изменение': 3,
         'civita': 3,
         'nova': 3,
         'миланский': 3,
         'литва': 3,
         'платформа': 3,
         'подчёркивать': 3,
         'освещать': 3,
         'инновационный': 3,
         'эмоциональный': 3,
         'заглянуть': 3,
         'встреча': 3,
         'язык': 3,
         'руководитель': 3,
         'решение': 3,
         'даце': 3,
         'представление': 3,
         'момент': 3,
         'событие': 3,
         '2021': 3,
         'крупный': 3,
         'широкий': 3,
         'технический': 3,
         'личный': 3,
         'салат': 3,
         'ягодный': 3,
         'фруктовый': 3,
         'продукция': 3,
         'предприятие': 3,
         'приготовить': 3,
         'круглый': 3,
         'групповой': 3,
         'просьба': 3,
         'заранее': 3,
         'договориться': 3,
         'сюда': 3,
         'приехать': 3,
         'балвском': 3,
         '27': 3,
         'учащихся': 3,
         'балвского': 3,
         'песня': 3,
         'пластический': 3,
         'starojums': 3,
         'послание': 3,
         'гордиться': 3,
         'молодёжь': 3,
         'дерево': 3,
         'резекне': 3,
         'виктория': 3,
         'виноград': 3,
         'туристический': 3,
         'домашний': 3,
         'река': 3,
         'девичник': 3,
         'свадьба': 3,
         'владелец': 3,
         'запись': 3,
         'предусмотреть': 3,
         'приходить': 3,
         'просмотр': 3,
         'огрское': 3,
         'элемент': 3,
         'свидетельство': 3,
         'граница': 3,
         'малый': 3,
         'посмотреть': 3,
         'вопрос': 3,
         'сегодня': 3,
         'изготовление': 3,
         'зигмарс': 3,
         'яуя': 3,
         'илзе': 3,
         'лаура': 3,
         'огрского': 3,
         'поддержка': 3,
         'цвет': 3,
         'поезд': 3,
         'знать': 3,
         'становиться': 3,
         'погодный': 3,
         'вечер': 3,
         'лицо': 3,
         'раскрываться': 3,
         'упита': 3,
         'суну': 3,
         'ночь': 3,
         'глаз': 3,
         'размышление': 3,
         'музыкальный': 3,
         '11': 3,
         'привлечь': 3,
         'свеча': 3,
         'специальный': 3,
         'аромат': 3,
         'входить': 3,
         'дружба': 3,
         'осмотр': 3,
         'энгуре': 3,
         'курляндский': 3,
         'диалект': 3,
         'впечатление': 3,
         'сайт': 3,
         'предложение': 3,
         'горячий': 3,
         'интернет': 3,
         'приглашаются': 3,
         'тёмный': 3,
         'активный': 3,
         'лейн': 3,
         'ассоциация': 3,
         'выступать': 3,
         'январь': 3,
         'прозвучать': 3,
         'понравиться': 3,
         'незабываемый': 3,
         'марципан': 3,
         'ирис': 3,
         'фильм': 3,
         'готиня': 3,
         'особенный': 3,
         'воздух': 3,
         'корпоративный': 3,
         'заказать': 3,
         'северный': 3,
         'посольство': 3,
         '\xa0 ': 3,
         'kuup': 3,
         'curonia': 3,
         'coffee': 3,
         'rocket': 3,
         'bean': 3,
         'александр': 3,
         'роман': 3,
         'суты': 3,
         'александра': 3,
         'бельцовой': 3,
         'акурейтера': 3,
         'открытый': 3,
         'мать': 3,
         'женщина': 3,
         'продолжиться': 3,
         'небесный': 3,
         'рукопись': 3,
         'передать': 3,
         'дневник': 3,
         'icom': 3,
         'народный': 3,
         'сандра': 3,
         'портрет': 3,
         'попасть': 3,
         'женственность': 3,
         '22': 3,
         'природный': 3,
         '90-летнему': 3,
         'андерсоне': 3,
         '366': 3,
         'фотовыставка': 3,
         '13': 3,
         'рисование': 3,
         'сфотографироваться': 3,
         'пластина': 3,
         'йоханнес': 3,
         'км': 3,
         'краеведческий': 3,
         'ирина': 3,
         '15': 3,
         'украсить': 3,
         'развлечься': 3,
         'играть': 3,
         '€': 3,
         'противник': 3,
         'настольный': 3,
         'футбольный': 3,
         'blacklight': 3,
         'аниты': 2,
         'звезда': 2,
         'альберт': 2,
         'юрис': 2,
         'звиргздиня': 2,
         'сон': 2,
         'инеса': 2,
         'зандере': 2,
         'клавиша': 2,
         'любимый': 2,
         'служить': 2,
         'разговор': 2,
         'зритель': 2,
         'тихий': 2,
         'пруд': 2,
         'воспоминание': 2,
         'средний': 2,
         'начаться': 2,
         'спридитис': 2,
         'неповторимый': 2,
         'стиль': 2,
         'иллюстрировать': 2,
         'значительный': 2,
         'оригинальный': 2,
         'балтавилкса': 2,
         'основательница': 2,
         'журнал': 2,
         'iii': 2,
         'iv': 2,
         'триеннале': 2,
         'книжный': 2,
         '2001': 2,
         'биеннале': 2,
         'м.': 2,
         '2015': 2,
         '2005': 2,
         'балтия': 2,
         '2000': 2,
         'вклад': 2,
         'литература': 2,
         'сок': 2,
         'водитель': 2,
         'самые': 2,
         'гостеприимно': 2,
         'крепкий': 2,
         'разместить': 2,
         'автобус': 2,
         'рекомендоваться': 2,
         'нравиться': 2,
         'пленник': 2,
         'закуска': 2,
         'поймать': 2,
         'бутылка': 2,
         'следить': 2,
         'страница': 2,
         'конец': 2,
         'лиго': 2,
         'счастливый': 2,
         'гауи': 2,
         'гауя': 2,
         'дополнять': 2,
         'предоставлять': 2,
         'ловушка': 2,
         'вызов': 2,
         'связать': 2,
         'уделить': 2,
         'савицки': 2,
         'ясмужа': 2,
         'айзкалне': 2,
         'прейльский': 2,
         'серебристый': 2,
         'посвящение': 2,
         'родный': 2,
         'символический': 2,
         'мировоззрение': 2,
         'серебряный': 2,
         'призывать': 2,
         'красота': 2,
         'отражение': 2,
         'a’design': 2,
         'awards': 2,
         'драгоценный': 2,
         'металл': 2,
         'великолепный': 2,
         'камень': 2,
         'характер': 2,
         'нью': 2,
         'йорк': 2,
         'венеция': 2,
         '2019': 2,
         'начинать': 2,
         'студент': 2,
         'окрестность': 2,
         'дух': 2,
         'отражаться': 2,
         'чашка': 2,
         'лес': 2,
         'войти': 2,
         'лишний': 2,
         'услышать': 2,
         'заметить': 2,
         'смотровой': 2,
         'башня': 2,
         'точка': 2,
         'попытка': 2,
         'понять': 2,
         'ощутить': 2,
         'отдел': 2,
         'практика': 2,
         'изучение': 2,
         'резекненском': 2,
         'бронирование': 2,
         'минимум': 2,
         'узнавать': 2,
         'преимущество': 2,
         'презентация': 2,
         'произвести': 2,
         'исследование': 2,
         'формирование': 2,
         'образовательный': 2,
         'захватывать': 2,
         'откройте': 2,
         'происхождение': 2,
         'здоровье': 2,
         'продолжать': 2,
         'узнайте': 2,
         'восстановление': 2,
         'сохранение': 2,
         'признать': 2,
         '16': 2,
         '17:00': 2,
         'успешный': 2,
         'moscapartners': 2,
         'лиепае': 2,
         'оценить': 2,
         'архитектура': 2,
         'демонстрация': 2,
         'креативность': 2,
         'чувствительность': 2,
         'функция': 2,
         'укоренить': 2,
         'объект': 2,
         'керамика': 2,
         'присутствие': 2,
         'позволять': 2,
         'глубоко': 2,
         'дита': 2,
         'даноса': 2,
         'концепция': 2,
         'сохранять': 2,
         'адаптировать': 2,
         'артис': 2,
         'керамический': 2,
         'архитектурный': 2,
         'гринберг': 2,
         'агентство': 2,
         'nid': 2,
         'кураторский': 2,
         '2020': 2,
         'популяризация': 2,
         'реализовать': 2,
         'pacai': 2,
         'привлекать': 2,
         'аудитория': 2,
         'ясмуйжа': 2,
         'вышивка': 2,
         'ирена': 2,
         'штейнберги': 2,
         'широко': 2,
         'irena': 2,
         'gasha': 2,
         'embroideries': 2,
         'деятельность': 2,
         'выполнить': 2,
         'значимый': 2,
         'мода': 2,
         'варение': 2,
         'вырастить': 2,
         'делать': 2,
         'ликёр': 2,

In [ ]:
personal_names = []
for typ, name in zip(pilsetas_ru.named_entities_type.explode(), pilsetas_ru.named_entities.explode()):
    if typ == "PER":
        personal_names.append(name.text)

Counter(personal_names)
# Counter(.apply(lambda x: x.text))

Counter({'Ояра Вациетиса': 8,
         'Фрицис': 8,
         'Скуя Брейден': 8,
         'Добеле': 7,
         'Анита Паегле': 6,
         'Анита Савицка': 4,
         'Мария': 4,
         'Марии': 4,
         'Людмилы Азаровой': 4,
         'М.Готлиб': 4,
         'Мары Циелене': 3,
         'Райниса': 3,
         'Андрея Упита': 3,
         'Александра Чака': 3,
         'Романа Суты': 3,
         'Александры Бельцовой': 3,
         'Ояр Вациетис': 3,
         'Майя': 3,
         'Аниты Паегле': 2,
         'Юриса Звиргздиня': 2,
         'Инесы Зандере': 2,
         'Аниты Савицки': 2,
         'Дита Даноса': 2,
         'Ирены Штейнберги': 2,
         'Индра Кэйша': 2,
         'Огре': 2,
         'Сигне Краукле': 2,
         'Ундине Крузе': 2,
         'Яниса Акурейтера': 2,
         'Рейнхольда Каспарсона': 2,
         'Фриды Кало': 2,
         'Гриеты Брамане': 2,
         'Марии Тимофеевой': 2,
         'Марты Андерсоне': 2,
         'Гатиса Шлюки': 2,
         'Гатис Шлюка': 2,
         'Гатис': 2,
         'Йоханнеса Ангебауэра': 2,
         'Стамериена': 2,
         'Марты Готлиб': 2,
         'Яниса Балтавилкса': 1,
         'Яниса Балтавилка': 1,
         'М. Циелене': 1,
         'Пастариньша': 1,
         'Индрика Зебериня': 1,
         'Балтавилкса': 1,
         'Ханса Кристиана Андерсена': 1,
         'Возможны': 1,
         'Лиго': 1,
         'Марису Митревицу': 1,
         'Яниса Райниса': 1,
         'Латгалии': 1,
         'Эрмини': 1,
         'Андрисом': 1,
         'Тимур Томсон': 1,
         'Артис Ниманис': 1,
         'Эмма София': 1,
         'Даце Суна': 1,
         'Мантас Лесаускас (Mantas Lesauskas)': 1,
         'Вилюс Дрингелис (Vilius Dringelis)': 1,
         'Мария Пуипайте (Marija Puipaitė)': 1,
         'Лиепа Градаускайте (Liepa Gradauskaitė)': 1,
         'Паулина Василяускайте (Paulina Vasiliauskaitė)': 1,
         'Люция Костива (Liucija Kostiva)': 1,
         'Сийм Карро (Siim Karro)': 1,
         'Аннике Лайго': 1,
         'Керту Лийса Лепик (Kertu Liisa Lepik)': 1,
         'Майле Гринберга (Maile Grünberg)': 1,
         'Юта Лембер (Juta Lember)': 1,
         'Марья Маеметс (Maarja Mäemets)': 1,
         'Аудроне Друнгилайте': 1,
         'Бригита Була': 1,
         'Кирилл Кирасиров': 1,
         'Лиепаи': 1,
         'Райниса «Ясмуйжа': 1,
         'Райниса «Ясмуйжа» (': 1,
         'Ирены': 1,
         'Мартин Пукс': 1,
         'Алдис Войтс': 1,
         'Эгия Львова': 1,
         'Арта Виксна': 1,
         'Лига Тумина': 1,
         'Оскар Сидельникс': 1,
         'Антра Кикусте': 1,
         'Виктория Мадерниеце': 1,
         'Йоланта Дундене': 1,
         'Сандрис Лайзанс': 1,
         'Даце': 1,
         'Илзе Стагите': 1,
         'Зигмарс Яуя\nИсторическое': 1,
         'Зигмарс Яуя': 1,
         'Улдис Апинис\nХудожники': 1,
         'Карина Кеберга\nГрафическая': 1,
         'Зане Калниня\nРисунки': 1,
         'Петерис Зилбертс': 1,
         'Лаура Зунда-Поча\nИзмерения': 1,
         'Лаура Зунда-Поча': 1,
         'Илзе Мекша': 1,
         'Интарс Сниедзе': 1,
         'Янис Зиньгитис': 1,
         'Элина Церпа': 1,
         'Лаура Туча': 1,
         'Марис Гросбахс': 1,
         'Нилс Микельсонс': 1,
         'Гунтарс Андерсонс\nВыставка': 1,
         'Циниш': 1,
         'Янису Балодису': 1,
         'Эдите Калнине': 1,
         'Марите Пипите': 1,
         'Иветы Бренце': 1,
         'Валдиса Лицитиса': 1,
         'Марите': 1,
         'Талси': 1,
         'Имей': 1,
         'Билеты': 1,
         'Фрициса': 1,
         'Лиене Лауриновича': 1,
         'Андрей Упит': 1,
         'Илзе Пукье': 1,
         'Лива Индрике': 1,
         'Алисе Крокфорда': 1,
         'Арта Роланда Лайцане': 1,
         'Валерия Сосова': 1,
         'Агрит Ванаг': 1,
         'Вильхельм Бандерс': 1,
         'Зельда Виктория Янсоне': 1,
         'Лоте Анна Стрике': 1,
         'Ингуны Скуя-Брейдены': 1,
         'Мелисы Скуя-Брейдены': 1,
         'Антропоцена': 1,
         'Скуи Брейден': 1,
         'Ингуна': 1,
         'Артис Тауриньш / Formup': 1,
         'Арнис Стасаитис': 1,
         'Скуя Брейден - "Уги': 1,
         'Гвидо Кайонс': 1,
         'Янис Вайновскис': 1,
         'Ужавас': 1,
         'Марии Лейн (Marie Lein)': 1,
         'М. Лейн': 1,
         'Виктории Рено (Viktoria Renaux)': 1,
         'Елизавета Гроце': 1,
         'Б. Зуйане': 1,
         'Мария Лейн': 1,
         'Плуме': 1,
         'Господине Плуме': 1,
         'Сидроварня': 1,
         'Скривери': 1,
         'иторговцы': 1,
         'фон Стрика': 1,
         'Якоба': 1,
         'Аспазии': 1,
         'Аспазии Маргариты Розенберги': 1,
         'Чака': 1,
         'Милде Гринфелде': 1,
         'Чак': 1,
         'Милде': 1,
         'Р. Суту': 1,
         'А. Бельцову': 1,
         'Р. Сута': 1,
         'Ояре Вациетисе': 1,
         'Солженицын': 1,
         'Визме Белшевиче': 1,
         'Ояр': 1,
         'Людмила Азарова': 1,
         'О. Вациетис': 1,
         'Л. Азаровой': 1,
         'О. Вациетиса': 1,
         'Акурейтера': 1,
         'Янис Акурейтер': 1,
         'Сандра Делгалве': 1,
         'Яниса Делгалвиса': 1,
         'Сандры': 1,
         'Сандры Делгалве': 1,
         'Фрида Кало': 1,
         'Фриде Кало': 1,
         'Сандре': 1,
         'Стрекозе': 1,
         'Марта Андерсоне': 1,
         'Марта': 1,
         'Даце Мицане-Залите': 1,
         'Людмилы': 1,
         'Залите': 1,
         'Ояра': 1,
         'Людмилы Вациетис': 1,
         'Людмила': 1,
         'Гинта Гринберга': 1,
         'Майи Буяки': 1,
         'Айя Принце': 1,
         'Вирджинии Контареллы': 1,
         'Йоханнеса': 1,
         'Х.\xa0Цукура': 1,
         'Букайши': 1,
         'Ирины Риежниеце': 1,
         'Ирины Богдане': 1,
         'Зенты Маурини': 1,
         'Гунты Крастиня': 1,
         'Алдиса Клявиньша': 1,
         'Херберта Эрба': 1,
         'Стефы Булавкиной': 1,
         'Экскурсия': 1,
         'Иллюзионист Эджус': 1,
         'Доступен': 1,
         'Нумернес': 1})

In [ ]:
pilsetas_ru[["named_entities_type", "named_entities"]]

,named_entities_type,named_entities
id,,
0,"[PER, PER, PER, LOC, LOC, PER, PER, PER, PER, ...","[(Аниты, Паегле), (Ояра, Вациетиса), (Ояра, Ва..."
1,"[ORG, PER, ORG, ORG, PER, LOC, ORG]","[(Зилвер), (Возможны), (Зилвер), (Facebook), (..."
2,"[LOC, LOC, ORG, LOC, LOC, ORG, LOC, PER, ORG]","[(Сигулде), (Гауи), (Национальном, парке), (Га..."
3,"[PER, ORG, ORG, LOC, LOC, PER, ORG, PER, LOC, ...","[(Аниты, Савицки), (Райниса, «, Ясмужа, »), (Р..."
4,"[LOC, LOC, LOC, ORG, ORG]","[(Яунмоку), (Яунмоку), (Яунмоку), (Визуальной,..."
5,"[LOC, ORG, ORG, ORG, LOC, LOC, PER]","[(Резекненском, крае), (Obelisk, Farm), (Obeli..."
6,"[ORG, ORG, ORG, ORG, ORG, ORG, LOC, LOC, LOC, ...","[(Большой, янтарь), (Civita, Nova), (Civita, N..."
7,"[PER, PER, LOC, LOC, PER, ORG, PER, ORG, LOC, ...","[(Райниса, «, Ясмуйжа), (Райниса, «, Ясмуйжа, ..."
8,[LOC],[(Латвии)]
9,"[ORG, ORG, ORG, LOC, ORG, LOC, ORG, LOC, LOC, ...","[(Балвском, центре, культуры, и, отдыха), (Бал..."
10,"[LOC, LOC, PER, LOC, PER]","[(Добельском, крае), (Тервете), (Сандрис, Лайз..."
11,"[ORG, ORG, LOC, PER, ORG, PER, LOC, LOC, LOC, ...","[(Огрском, музее, истории, и, искусства), (Огр..."
12,"[LOC, ORG, PER, LOC, ORG, PER, PER, PER]","[(Талси), (Аусеклис), (Марите, Пипите), (Кулди..."
13,"[LOC, PER, LOC, LOC, PER, LOC, PER, PER, PER, ...","[(Талси), (Фрицис), (Талси), (Фрицис), (Талси)..."
14,"[ORG, ORG, ORG, ORG, LOC, ORG, ORG, ORG, ORG]","[(Резекне), (Латгальский, центр, культуры), (G..."
15,"[PER, LOC, PER, PER, PER, PER, PER, LOC, PER, ...","[(Добеле), (Добеле), (Добеле), (Добеле), (Добе..."
16,"[PER, ORG, PER, LOC, LOC, PER, LOC, ORG, PER, ...","[(Андрея, Упита), (Латвийской, академии, искус..."
17,"[PER, ORG, ORG, PER, ORG, PER, PER, PER, PER, ...","[(Скуя, Брейден), (Рижском, музее), (Рижском, ..."
18,"[ORG, LOC, LOC, ORG, LOC, LOC, ORG, PER, ORG, ...","[(ООО, Meduspils), (Салдусском, крае), (Латвии..."
19,"[ORG, LOC, LOC, LOC, ORG, LOC]","[(Денины), (Энгуре), (Энгуре), (Рижского, зали..."
20,"[LOC, PER, LOC, LOC, LOC]","[(Латвии), (Ужавас), (Латвии), (Ужавас), (Авст..."
21,"[LOC, LOC, LOC, LOC, LOC, LOC, LOC, PER, LOC, ...","[(Райниса), (Аспазии), (Рига), (Райниса), (Асп..."
22,"[LOC, PER, PER, PER]","[(Латвии), (Плуме), (Господине, Плуме), (Сидро..."
23,"[ORG, PER]","[(Готиня), (Скривери)]"
24,"[LOC, ORG, LOC, LOC, ORG, LOC, ORG, LOC, LOC, ...","[(Латвии), (Valmiermuižas), (Риге), (Северной,..."
25,"[ORG, ORG, LOC, LOC, LOC, LOC, LOC, ORG, ORG, ...","[(KUUP), (KUUP), (Резекненском, крае), (Вирауд..."
26,"[LOC, LOC, LOC, PER, PER, PER, PER, PER, LOC, ...","[(Риге), (Райниса), (Аспазии), (Александра, Ча..."
27,"[ORG, PER, LOC, PER, PER, ORG, LOC, PER, PER, ...","[(Народном, доме, Салгале), (Сандра, Делгалве)..."
28,"[LOC, LOC, LOC, LOC, LOC, LOC, LOC, LOC, LOC, ...","[(Сабиле), (Абавы), (Спару), (Абавы), (Сабиле)..."
29,"[PER, PER, LOC, LOC, LOC, LOC, LOC, LOC, PER, ...","[(Гриеты, Брамане), (Марии, Тимофеевой), (Райн..."
30,"[LOC, LOC, LOC, LOC, LOC]","[(Латвии), (Руйиене), (Упес), (Латвии), (Руйие..."
32,"[PER, PER, PER, PER, PER, PER, LOC, PER, PER, ...","[(Людмилы, Азаровой), (Людмилы, Азаровой), (Оя..."
33,"[PER, LOC, PER, LOC, PER, LOC, LOC, LOC, PER, ...","[(Гатиса, Шлюки), (Кекавы), (Гатиса, Шлюки), (..."
34,"[PER, ORG, LOC, LOC, PER, ORG, PER, ORG, PER, ...","[(Майи, Буяки), (Народном, доме), (Ване), (Тук..."
35,"[PER, PER, PER, PER, PER]","[(Йоханнеса, Ангебауэра), (Стамериена), (Стаме..."
36,"[LOC, LOC, PER, ORG, PER]","[(Букайши), (Букайши), (Х., , Цукура), (Лидон..."
37,"[PER, ORG, ORG, PER, PER, ORG, LOC, PER, ORG, ...","[(Марты, Готлиб), (Доме, ремесел), (Доме, реме..."
38,"[LOC, LOC, ORG, ORG, PER, LOC, PER, PER, LOC, ...","[(Южнокурземском, крае), (Айзпуте), (Бунка), (..."
41,[PER],[(Экскурсия)]
42,"[PER, LOC, LOC]","[(Иллюзионист, Эджус), (Латвии), (Риге)]"
45,"[ORG, LOC, LOC, LOC, PER, LOC, LOC, LOC, ORG]","[(Гольфиньш), (Риге), (Кр), (Кришьяня, Барона)..."
46,"[LOC, LOC, LOC, PER, LOC, LOC]","[(Северной, Латгалии), (Лудзского, края), (Нум..."

RIGA EN

In [89]:
df_en = pd.DataFrame({
    "text": riga_en.text
})
df_en.loc[:2]

                                                 text
id
0   Residents and visitors of the capital are invi...
1   During the fourth week of Advent city’s inhabi...
2   During the third week of Advent, Riga will hos...

In [93]:
labels_en = nlp_eng.get_pipe("ner").labels

for label in labels_en:
    print(label + ' : ' + spacy.explain(label))

CARDINAL : Numerals that do not fall under another type
DATE : Absolute or relative dates or periods
EVENT : Named hurricanes, battles, wars, sports events, etc.
FAC : Buildings, airports, highways, bridges, etc.
GPE : Countries, cities, states
LANGUAGE : Any named language
LAW : Named documents made into laws.
LOC : Non-GPE locations, mountain ranges, bodies of water
MONEY : Monetary values, including unit
NORP : Nationalities or religious or political groups
ORDINAL : "first", "second", etc.
ORG : Companies, agencies, institutions, etc.
PERCENT : Percentage, including "%"
PERSON : People, including fictional
PRODUCT : Objects, vehicles, foods, etc. (not services)
QUANTITY : Measurements, as of weight or distance
TIME : Times smaller than a day
WORK_OF_ART : Titles of books, songs, etc.

In [ ]:
df_en["doc"] = df_en.text.apply(process_en)
df_en["tokens"] = df_en.doc.apply(get_token)
df_en["lemmas"] = df_en.doc.apply(get_lemma)
df_en["pos"] = df_en.doc.apply(get_pos)
df_en["proper_nouns"] = df_en.doc.apply(extract_proper_nouns)


def extract_stopwords_en(doc):
    return [token.text for token in doc if token.text not in nlp_eng.Defaults.stop_words]

df_en['Tokens_NoStops'] = df_en.doc.apply(extract_stopwords_en)
df_en['Text_NoStops'] = [' '.join(map(str, l)) for l in df_en['Tokens_NoStops']]
df_en['Doc_NoStops'] = df_en['Text_NoStops'].apply(process_ru)

df_en['chunks'] = df_en.doc.apply(extract_noun_phrases)
df_en["named_entities"] = df_en.doc.apply(extract_named_entities_labels)
df_en['NE_Words'] = df_en['doc'].apply(extract_named_entities)

In [99]:
riga_en["named_entities_type"] = df_en.named_entities
riga_en["named_entities"] = df_en.NE_Words
riga_en["noun_phrases"] = df_en.chunks
riga_en.loc[0]

url                    https://www.riga.lv/en/article/residents-and-v...
image_url              https://www.riga.lv/sites/riga/files/styles/ar...
title                  Residents and visitors of the capital are invi...
date                                                    00:00 17.12.2025
author                 Riga Municipality's External Communications Di...
topics                 ['Press releases', 'Leisure', 'Culture and Ent...
text                   Residents and visitors of the capital are invi...
matching_article_id                                                  4.0
keywords                                                             NaN
named_entities_type    [DATE, DATE, TIME, TIME, DATE, CARDINAL, FAC, ...
named_entities         [(the, year, 2026), (31,  , December), (09.00,...
noun_phrases           [Residents, visitors, the capital, the year, a...
Name: 0, dtype: object

In [102]:
riga_en["adjectives"] = df_en.doc.apply(extract_adjs)
riga_en.loc[0]

url                    https://www.riga.lv/en/article/residents-and-v...
image_url              https://www.riga.lv/sites/riga/files/styles/ar...
title                  Residents and visitors of the capital are invi...
date                                                    00:00 17.12.2025
author                 Riga Municipality's External Communications Di...
topics                 ['Press releases', 'Leisure', 'Culture and Ent...
text                   Residents and visitors of the capital are invi...
matching_article_id                                                  4.0
keywords                                                             NaN
named_entities_type    [DATE, DATE, TIME, TIME, DATE, CARDINAL, FAC, ...
named_entities         [(the, year, 2026), (31,  , December), (09.00,...
noun_phrases           [Residents, visitors, the capital, the year, a...
adjectives             [joyful, parallel, festive, popular, favourite...
Name: 0, dtype: object

In [107]:
def clean_en(row):
    new_list = []
    for word in row:
        if word in nlp_eng.Defaults.stop_words:
            continue
        if word in '!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~–—“”·':
            continue
        if word in ["\n", "\n\n", "\r", "\r\n", "\xa0", "\n\xa0", "\n\xa0\n", "\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0", "`"]:
            continue
        new_list.append(word)
    return new_list
clean_lemmas = df_en.lemmas.apply(clean_en)

In [110]:
df_en.lemmas = clean_lemmas

In [111]:
Counter(df_en.lemmas.explode().to_list())

Counter({'Riga': 351,
         'concert': 126,
         'event': 108,
         'year': 86,
         'place': 81,
         'city': 68,
         'City': 59,
         'Latvia': 57,
         'Christmas': 57,
         'latvian': 55,
         'Square': 53,
         'visitor': 51,
         'invite': 51,
         'cultural': 51,
         'p.m.': 50,
         'light': 50,
         'Council': 49,
         'art': 48,
         'Culture': 48,
         'workshop': 46,
         'child': 45,
         'artist': 45,
         'feature': 45,
         'Art': 44,
         'time': 44,
         'night': 44,
         'perform': 43,
         'resident': 42,
         'Rīga': 41,
         'August': 40,
         'free': 39,
         'Hall': 38,
         'music': 38,
         'Centre': 38,
         'work': 37,
         'host': 36,
         'evening': 36,
         'programme': 36,
         'group': 36,
         'May': 36,
         'December': 35,
         'create': 35,
         'dance': 35,
         'available': 35,
         'Department': 35,
         'Park': 34,
         'band': 33,
         'Palace': 33,
         'performance': 32,
         'prepare': 32,
         'project': 32,
         'Street': 31,
         'Communication': 31,
         'exhibition': 31,
         'Light': 30,
         'new': 30,
         'e': 29,
         'mail': 29,
         'Easter': 29,
         'world': 28,
         'include': 28,
         'Museum': 27,
         'External': 26,
         'creative': 26,
         'family': 26,
         'international': 26,
         'festival': 25,
         'festive': 25,
         'choir': 25,
         'birthday': 25,
         'Town': 24,
         'offer': 24,
         'guest': 24,
         'Information': 24,
         'participate': 24,
         'day': 24,
         'film': 24,
         'musical': 23,
         'experience': 23,
         'Advent': 23,
         'musician': 23,
         'song': 23,
         'park': 23,
         'Midsummer': 23,
         'open': 22,
         'audience': 22,
         'Project': 22,
         'traditional': 22,
         'contemporary': 22,
         'water': 22,
         'celebrate': 22,
         'Latvian': 22,
         'marathon': 22,
         'life': 21,
         'follow': 21,
         'Coordinator': 21,
         'Division': 21,
         'folk': 21,
         'Garden': 21,
         'special': 21,
         'object': 21,
         'stage': 21,
         'Week': 21,
         'street': 20,
         'November': 20,
         'DJ': 20,
         'information': 20,
         'Ineta': 20,
         'Miglāne': 20,
         'Communications': 20,
         'ineta.miglane@riga.lv': 20,
         'museum': 20,
         'Choir': 20,
         'area': 20,
         'fountain': 20,
         'find': 19,
         'medium': 19,
         'able': 19,
         'opportunity': 19,
         'activity': 19,
         'installation': 19,
         'celebration': 18,
         'enjoy': 18,
         '10': 18,
         'generation': 18,
         'hold': 18,
         'Music': 18,
         '19.00': 18,
         'local': 18,
         'neighbourhood': 18,
         'story': 17,
         'website': 17,
         'social': 17,
         'National': 17,
         '\xa0\n': 17,
         'June': 17,
         '21.10': 17,
         'Ave': 16,
         'Sol': 16,
         'folklore': 16,
         'people': 16,
         'game': 16,
         '2025': 16,
         'market': 16,
         'ensemble': 16,
         'record': 16,
         'national': 16,
         'italian': 16,
         'April': 16,
         'capital': 15,
         'welcome': 15,
         'bring': 15,
         '18': 15,
         '20': 15,
         'ticket': 15,
         'lead': 15,
         '15': 15,
         'Festival': 15,
         '15.00': 15,
         'good': 15,
         'start': 15,
         '2024': 15,
         'km': 15,
         'Old': 14,
         'provide': 14,
         'municipality': 14,
         'program': 14,
         'youth': 14,
         'use': 14,
         'soloist': 14,
         'young': 14,
         'run': 14,
         'support': 14,
         'public': 14,
         'know': 14,
         'build': 14,
         'Marathon': 14,
         '17.10': 14,
         'set': 13,
         'highlight': 13,
         'come': 13,
         '\xa0\xa0\xa0\xa0\xa0\xa0 ': 13,
         'participation': 13,
         'Saturday': 13,
         'tree': 13,
         '21': 13,
         'Republic': 13,
         'country': 13,
         'Vērmanes': 13,
         'character': 13,
         'cinema': 13,
         'Freedom': 13,
         'Staro': 13,
         'wide': 13,
         'Italy': 13,
         'culture': 13,
         'Gallery': 13,
         '11': 12,
         'hour': 12,
         '12.00': 12,
         'Ziemeļblāzma': 12,
         'entrance': 12,
         'winter': 12,
         'office': 12,
         'Municipality': 12,
         'Church': 12,
         'collection': 12,
         'european': 12,
         'Sweden': 12,
         'rink': 12,
         'environment': 12,
         'plan': 12,
         'Uzvaras': 12,
         'large': 12,
         'Night': 12,
         'development': 12,
         'elite': 12,
         'mood': 11,
         'design': 11,
         'page': 11,
         'rīgā': 11,
         'notiek': 11,
         '+371': 11,
         'hall': 11,
         '17': 11,
         'Chamber': 11,
         'route': 11,
         'season': 11,
         'Concert': 11,
         'School': 11,
         'Small': 11,
         'Guild': 11,
         'Europe': 11,
         'ice': 11,
         'present': 11,
         'history': 11,
         'significant': 11,
         'tourist': 11,
         'forum': 11,
         'White': 11,
         '16': 11,
         'summer': 11,
         'illusionist': 11,
         'near': 10,
         'visual': 10,
         'foreign': 10,
         'especially': 10,
         'different': 10,
         'Doma': 10,
         'share': 10,
         'VEF': 10,
         'EUR': 10,
         'centre': 10,
         'Imanta': 10,
         'Biļešu': 10,
         'paradīze': 10,
         'allow': 10,
         'Quarter': 10,
         'Orchestra': 10,
         'charge': 10,
         'inspire': 10,
         '12': 10,
         'composer': 10,
         'series': 10,
         'total': 10,
         'result': 10,
         'Director': 10,
         'second': 10,
         'theatre': 10,
         'skating': 10,
         'I': 10,
         'urban': 10,
         'co': 10,
         'Circle': 10,
         'anniversary': 10,
         'singer': 10,
         'compete': 10,
         'Summer': 10,
         'Līgo': 10,
         '2023': 10,
         'runner': 10,
         'Skanste': 10,
         'unique': 9,
         'diverse': 9,
         'phone': 9,
         'woman': 9,
         'entry': 9,
         'invitation': 9,
         'old': 9,
         '\xa0 ': 9,
         'craft': 9,
         'Iļģuciems': 9,
         'European': 9,
         'receive': 9,
         'strong': 9,
         'middle': 9,
         'personal': 9,
         'increase': 9,
         'big': 9,
         'Friday': 9,
         'animated': 9,
         'Canada': 9,
         'participant': 9,
         'space': 9,
         'live': 9,
         'final': 9,
         'heritage': 9,
         'Jānis': 9,
         'magic': 9,
         'government': 9,
         'conference': 9,
         'half': 9,
         'champion': 9,
         'tap': 9,
         'territory': 9,
         'Līvu': 8,
         'popular': 8,
         'real': 8,
         'diversity': 8,
         'week': 8,
         '07:00': 8,
         'mixed': 8,
         'hear': 8,
         '19': 8,
         'box': 8,
         'advance': 8,
         'learn': 8,
         'decorate': 8,
         'play': 8,
         'little': 8,
         'feeling': 8,
         'organise': 8,
         'Miera': 8,
         'Folk': 8,
         'campaign': 8,
         '6': 8,
         'dedicate': 8,
         'century': 8,
         'Sunday': 8,
         '16.00': 8,
         'Academy': 8,
         'theme': 8,
         'tourism': 8,
         'attract': 8,
         'number': 8,
         'Germany': 8,
         'join': 8,
         'Esplanade': 8,
         'break': 8,
         'restaurant': 8,
         'promote': 8,
         'begin': 8,
         'visit': 8,
         'cat': 8,
         'environmental': 8,
         'France': 8,
         'atmosphere': 8,
         'rich': 8,
         'attend': 8,
         'cooperation': 8,
         '14': 8,
         'field': 8,
         'athlete': 8,
         'distance': 8,
         'race': 8,
         'Uffizi': 8,
         'January': 7,
         'dj': 7,
         'VJ': 7,
         'screen': 7,
         'rhythm': 7,
         'party': 7,
         'Market': 7,
         'continue': 7,
         'delight': 7,
         'entertain': 7,
         '5': 7,
         'venue': 7,
         'New': 7,
         'Year': 7,
         'Eve': 7,
         'www.kultura.riga.lv': 7,
         'vocal': 7,
         'jazz': 7,
         'Porcelain': 7,
         'porcelain': 7,
         'decoration': 7,
         'book': 7,
         'tradition': 7,
         '24': 7,
         'warm': 7,
         'conductor': 7,
         'Valdis': 7,
         'historical': 7,
         'outstanding': 7,
         '13.30': 7,
         '17.00': 7,
         'Mārtiņš': 7,
         'high': 7,
         'More': 7,
         'modern': 7,
         'accompany': 7,
         'guitar': 7,
         'piano': 7,
         'opening': 7,
         'Restaurant': 7,
         'organiser': 7,
         'main': 7,
         'flow': 7,
         'Splendid': 7,
         'Mežaparks': 7,
         'range': 7,
         'sculpture': 7,
         'award': 7,
         'point': 7,
         'serve': 7,
         'locate': 7,
         'nature': 7,
         'expect': 7,
         'appreciate': 7,
         'long': 7,
         'professional': 7,
         'Rīgas': 7,
         'motto': 7,
         'Berlin': 7,
         'holiday': 7,
         'Rimi': 7,
         'mile': 7,
         'network': 7,
         'swing': 7,
         'egg': 7,
         '1': 6,
         'square': 6,
         'favourite': 6,
         'Krauze': 6,
         'building': 6,
         'address': 6,
         'help': 6,
         'mask': 6,
         'procession': 6,
         'person': 6,
         'Nouveau': 6,
         '04:00': 6,
         'collective': 6,
         'photo': 6,
         'Bastejkalns': 6,
         '9': 6,
         'community': 6,
         'Mazā': 6,
         'end': 6,
         '23': 6,
         'early': 6,
         'outlet': 6,
         '13': 6,
         '18.00': 6,
         'Andris': 6,
         'Ieva': 6,
         'strengthen': 6,
         'competition': 6,
         'travel': 6,
         'reach': 6,
         'destination': 6,
         'internationally': 6,
         'Cathedral': 6,
         '7': 6,
         'equipment': 6,
         'skate': 6,
         'issue': 6,
         'association': 6,
         'select': 6,
         'autumn': 6,
         'level': 6,
         'quality': 6,
         'food': 6,
         'ensure': 6,
         'identity': 6,
         'way': 6,
         'discover': 6,
         'moment': 6,
         'actor': 6,
         'illuminate': 6,
         'spring': 6,
         'month': 6,
         'honour': 6,
         'flower': 6,
         'human': 6,
         'famous': 6,
         'bronze': 6,
         'quiet': 6,
         'connection': 6,
         'dawn': 6,
         'reveal': 6,
         'author': 6,
         'scale': 6,
         'turn': 6,
         'Monument': 6,
         'active': 6,
         'Juris': 6,
         '20.00': 6,
         'Opera': 6,
         'original': 6,
         'central': 6,
         'late': 6,
         'sport': 6,
         'exciting': 6,
         'canal': 6,
         'Dzegužkalns': 6,
         'great': 6,
         'period': 6,
         'Agnese': 6,
         'Circus': 6,
         'slogan': 6,
         'image': 6,
         'ethno': 6,
         'company': 6,
         'Development': 6,
         'growth': 6,
         'course': 6,
         'Kenya': 6,
         'Slovakia': 6,
         'mayor': 6,
         '13.10': 6,
         'system': 6,
         'financing': 6,
         'a.m.': 5,
         'fill': 5,
         'spirit': 5,
         'projection': 5,
         'electronic': 5,
         'journey': 5,
         'combine': 5,
         '10.00': 5,
         'studio': 5,
         'lecture': 5,
         'lighting': 5,
         'solstice': 5,
         '12:00': 5,
         'senior': 5,
         'Tuesday': 5,
         '11:00': 5,
         'sing': 5,
         'age': 5,
         'symbolise': 5,
         'melody': 5,
         'ornament': 5,
         'conclude': 5,
         'Mixed': 5,
         '22': 5,
         'ģilde': 5,
         'bilesuparadize.lv': 5,
         'Star': 5,
         'pianist': 5,
         'Rihards': 5,
         'Torņakalns': 5,
         'Kārlis': 5,
         'artistic': 5,
         'Kalniņš': 5,
         'achieve': 5,
         'Best': 5,
         '3rd': 5,
         'vote': 5,
         'attractive': 5,
         'Finland': 5,
         'Investment': 5,
         'Tourism': 5,
         'title': 5,
         'Kalnciema': 5,
         'pop': 5,
         'joy': 5,
         'representative': 5,
         'collaboration': 5,
         'particularly': 5,
         'communication': 5,
         'broad': 5,
         'choose': 5,
         'platform': 5,
         'future': 5,
         'Rātslaukums': 5,
         'location': 5,
         'industry': 5,
         'Association': 5,
         'reflect': 5,
         'display': 5,
         'herald': 5,
         'balance': 5,
         '17:00': 5,
         'consist': 5,
         'Library': 5,
         'important': 5,
         'Edgars': 5,
         'drum': 5,
         '\xa0 \n': 5,
         'improve': 5,
         'walk': 5,
         'poetry': 5,
         'variety': 5,
         'Katrīna': 5,
         'tournament': 5,
         'look': 5,
         'unite': 5,
         'map': 5,
         'Grīziņkalns': 5,
         'lifestyle': 5,
         'post': 5,
         'Club': 5,
         'Zeidi': 5,
         'plant': 5,
         'booking': 5,
         'enrich': 5,
         'Day': 5,
         'congress': 5,
         'today': 5,
         'class': 5,
         'management': 5,
         'bus': 5,
         'direction': 5,
         'implement': 5,
         'championship': 5,
         'finisher': 5,
         'Slovenia': 5,
         'Austria': 5,
         'state': 5,
         'operation': 5,
         'instal': 5,
         'revitalisation': 5,
         'Madame': 5,
         'Palazzo': 5,
         '2026': 4,
         '31': 4,
         'Embankment': 4,
         'dancing': 4,
         'Ozols': 4,
         'MC': 4,
         'Valters': 4,
         'care': 4,
         'house': 4,
         'wall': 4,
         'dynamic': 4,
         'base': 4,
         'love': 4,
         'varied': 4,
         'inhabitant': 4,
         'log': 4,
         '06:00': 4,
         'mobility': 4,
         '26406354': 4,
         'require': 4,
         'jugendstils@riga.lv': 4,
         '67181465': 4,
         'Winter': 4,
         'quarter': 4,
         'suitable': 4,
         '25': 4,
         'Luther': 4,
         'need': 4,
         'gift': 4,
         'remind': 4,
         'courtyard': 4,
         'close': 4,
         'beloved': 4,
         'Congress': 4,
         'interested': 4,
         'view': 4,
         'school': 4,
         'annual': 4,
         'performer': 4,
         'sound': 4,
         '1st': 4,
         'garden': 4,
         'Emīls': 4,
         'director': 4,
         'chamber': 4,
         'John': 4,
         'bass': 4,
         'Artūrs': 4,
         'composition': 4,
         'Monday': 4,
         '28': 4,
         '4': 4,
         'historic': 4,
         'accord': 4,
         'United': 4,
         'Kingdom': 4,
         'priority': 4,
         'Fredis': 4,
         'Bikovs': 4,
         'Agency': 4,
         'Second': 4,
         'dialogue': 4,
         '15:00': 4,
         'listener': 4,
         'classic': 4,
         'arrangement': 4,
         'interpretation': 4,
         'voice': 4,
         'March': 4,
         'change': 4,
         'key': 4,
         'offering': 4,
         'truly': 4,
         'team': 4,
         'success': 4,
         'influencer': 4,
         'entertaining': 4,
         'marketing': 4,
         'digital': 4,
         'Chairman': 4,
         'US': 4,
         'Award': 4,
         'currently': 4,
         'like': 4,
         'Flow': 4,
         'screening': 4,
         'far': 4,
         'RIGA': 4,
         'unprecedented': 4,
         'Film': 4,
         'rest': 4,
         'curator': 4,
         'involve': 4,
         'paint': 4,
         'illuminated': 4,
         'style': 4,
         'form': 4,
         'man': 4,
         'float': 4,
         'star': 4,
         'touch': 4,
         'dark': 4,
         'hope': 4,
         'landscape': 4,
         'quantum': 4,
         'exist': 4,
         'darkness': 4,
         'stay': 4,
         'feel': 4,
         'symbol': 4,
         'Ance': 4,
         'son': 4,
         'Kaukulis': 4,
         'Kaspars': 4,
         'Sound': 4,
         'Modern': 4,
         'Inga': 4,
         'ancient': 4,
         'approximately': 4,
         'accessible': 4,
         'engage': 4,
         'Dome': 4,
         'weave': 4,
         'Dimanta': 4,
         'simultaneously': 4,
         'alternative': 4,
         'current': 4,
         'Championship': 4,
         'Dauderi': 4,
         'Program': 4,
         'RakstuRīga': 4,
         'characteristic': 4,
         'Tatjana': 4,
         'Smirnova': 4,
         'tsmirnova11@riga.lv': 4,
         'debut': 4,
         'album': 4,
         '30': 4,
         'green': 4,
         'Thursday': 4,
         'midnight': 4,
         'usual': 4,
         'Dance': 4,
         'gather': 4,
         'wreath': 4,
         'Jāņa': 4,
         'www.bilesuparadize.lv': 4,
         'researcher': 4,
         'Mystero': 4,
         'announce': 4,
         'press': 4,
         'Vilnis': 4,
         'Ķirsis': 4,
         'illusionism': 4,
         'poster': 4,
         'Embassy': 4,
         'sector': 4,
         'structure': 4,
         'safety': 4,
         'outdoor': 4,
         'compare': 4,
         'previous': 4,
         'target': 4,
         'sustainable': 4,
         'Prokopcuka': 4,
         'Half': 4,
         'line': 4,
         'Ethiopia': 4,
         '2022': 4,
         'finish': 4,
         '4th': 4,
         'medalist': 4,
         'Uģis': 4,
         '5.7': 4,
         'coordinator': 4,
         'costume': 4,
         'restoration': 4,
         'access': 4,
         'drinking': 4,
         'gradually': 4,
         'supply': 4,
         'decorative': 4,
         'neighborhood': 4,
         'ambitious': 4,
         'Florence': 4,
         'Fattori': 4,
         'Morandi': 4,
         'Madama': 4,
         'Pitti': 4,
         'joyful': 3,
         '02.00': 3,
         'parallel': 3,
         'Vaļņu': 3,
         'Linda': 3,
         'Samsonova': 3,
         'audiovisual': 3,
         'multimedia': 3,
         'led': 3,
         'positive': 3,
         'colour': 3,
         'hip': 3,
         'hop': 3,
         'element': 3,
         'test': 3,
         'format': 3,
         '40': 3,
         'specific': 3,
         'heart': 3,
         '11.00': 3,
         'hot': 3,
         '29363334': 3,
         'masquerade': 3,
         'palace': 3,
         'un': 3,
         'bonfire': 3,
         'ritual': 3,
         'region': 3,
         'Tree': 3,
         '03:00': 3,
         'thematic': 3,
         'reduce': 3,
         'valid': 3,
         'write': 3,
         'orchestra': 3,
         '12:45': 3,
         'Tornakalns': 3,
         'Foundation': 3,
         'Tallinas': 3,
         'Groove': 3,
         'Dixie': 3,
         'elf': 3,
         'cone': 3,
         'Chikki': 3,
         'home': 3,
         'miracle': 3,
         'Budēļi': 3,
         'authentic': 3,
         'Zāle': 3,
         'quartet': 3,
         'charity': 3,
         'donation': 3,
         'Sigma': 3,
         'Balsis': 3,
         'Butāns': 3,
         '2': 3,
         '20th': 3,
         'premise': 3,
         'student': 3,
         'alongside': 3,
         'enhance': 3,
         'Jāzeps': 3,
         'Boys': 3,

In [112]:
names_en = riga_en.named_entities.explode().tolist()

sum_ent_en = 0
entities_en = {}
for n in set(names_en):
    if n.text not in entities_en:
        entities_en[n.text] = 0
    entities_en[n.text] += 1
    sum_ent_en += 1
sum_ent_en

2965

In [114]:
"""
CARDINAL : Numerals that do not fall under another type
DATE : Absolute or relative dates or periods
EVENT : Named hurricanes, battles, wars, sports events, etc.
FAC : Buildings, airports, highways, bridges, etc.
GPE : Countries, cities, states
LANGUAGE : Any named language
LAW : Named documents made into laws.
LOC : Non-GPE locations, mountain ranges, bodies of water
MONEY : Monetary values, including unit
NORP : Nationalities or religious or political groups
ORDINAL : "first", "second", etc.
ORG : Companies, agencies, institutions, etc.
PERCENT : Percentage, including "%"
PERSON : People, including fictional
PRODUCT : Objects, vehicles, foods, etc. (not services)
QUANTITY : Measurements, as of weight or distance
TIME : Times smaller than a day
WORK_OF_ART : Titles of books, songs, etc.
"""

'\nCARDINAL : Numerals that do not fall under another type\nDATE : Absolute or relative dates or periods\nEVENT : Named hurricanes, battles, wars, sports events, etc.\nFAC : Buildings, airports, highways, bridges, etc.\nGPE : Countries, cities, states\nLANGUAGE : Any named language\nLAW : Named documents made into laws.\nLOC : Non-GPE locations, mountain ranges, bodies of water\nMONEY : Monetary values, including unit\nNORP : Nationalities or religious or political groups\nORDINAL : "first", "second", etc.\nORG : Companies, agencies, institutions, etc.\nPERCENT : Percentage, including "%"\nPERSON : People, including fictional\nPRODUCT : Objects, vehicles, foods, etc. (not services)\nQUANTITY : Measurements, as of weight or distance\nTIME : Times smaller than a day\nWORK_OF_ART : Titles of books, songs, etc.\n'

In [116]:
entities_en = []
personal_en = []
for typ, name in zip(riga_en.named_entities_type.explode(), riga_en.named_entities.explode()):
    if typ in "PERSON":
        personal_en.append(name.text)
    if typ in ["EVENT", "GPE", "LANGUAGE", "FAC", "MONEY", "LOC", "NORP", "ORG", "WORK_OF_ART"]:
        entities_en.append(name.text)
    

Counter(personal_en)

Counter({'Ineta Miglāne': 20,
         'Mazā': 4,
         'Fredis Bikovs': 4,
         'Rātslaukums': 4,
         'Ance Krauze': 4,
         'Juris Kaukulis': 4,
         'Tatjana Smirnova': 4,
         'Fattori': 4,
         'Linda Samsonova': 3,
         'Valdis Butāns': 3,
         'Doma': 3,
         'Katrīna Dimanta': 3,
         'DJ Gustavito': 2,
         'Valters Krauze': 2,
         'Aija Vītoliņa': 2,
         'Normunds Rutulis': 2,
         'Ilona Bagele': 2,
         'Intars Busulis': 2,
         'Andris Veismanis': 2,
         'Valdis Zilveris': 2,
         'Viesturs Kleinbergs': 2,
         'Kaspars Zemītis': 2,
         'Tavi': 2,
         'Ieva Sutugova': 2,
         'Valters Pūce': 2,
         'Dainis Tenis': 2,
         'Kopā Reti Esošu Draugu Organizācija': 2,
         'Shipsea': 2,
         'Iļģi': 2,
         'Jānis': 2,
         'Līgo': 2,
         'Skandinieki': 2,
         'Dace': 2,
         'Enrico Pezolli': 2,
         'Vilnis Ķirsis': 2,
         'Harry Houdini': 2,
         'Jelena Prokopcuka’s': 2,
         'Uģis Jocis': 2,
         'Kristers Kudlis': 2,
         'Sibilla Vanadziņa': 2,
         'Marlēna Keine': 2,
         'Mirdza Lukaža': 2,
         'Morandi': 2,
         'VJ Slavpapii': 1,
         'VJ Mersedes Margoit': 1,
         'VJ Arsenijs Rozenbahs': 1,
         'VJ Wickiss': 1,
         'Wolf': 1,
         'Toms Grēviņš': 1,
         'Jazz Sextet': 1,
         'Emma Sofija': 1,
         'Šī jausma': 1,
         'savādā': 1,
         'Annika Lanka': 1,
         'Rihards Plešanovs': 1,
         'Tamara Čudnovska': 1,
         'Māra Muižniece': 1,
         'Daniils Bulajevs': 1,
         'Kārlis Kazāks': 1,
         'Paula Saija': 1,
         'Renāte Zviedre': 1,
         'Annija Putniņa': 1,
         'Aleksandra Špicberga': 1,
         'Kristīne Pāže': 1,
         'Jasmīnas': 1,
         'Rihards Lapiņš': 1,
         'Jēkabs Krists Kalniņš': 1,
         'Vidus': 1,
         'Āris Ozols': 1,
         'Kārlis Lācis': 1,
         'Amadeus': 1,
         'Vigo Račevskis': 1,
         'Ernests Medenis': 1,
         'Agate Grīnhofa': 1,
         'Kristīne Freimane': 1,
         'Kamila Siliņa': 1,
         'Mārtiņš Zvīgulis': 1,
         'Artūrs Švarcbahs': 1,
         'Ieva Kerēvica': 1,
         'Gunārs Rozenbergs': 1,
         'Raimonds Pauls': 1,
         'Alvilas Altmanis': 1,
         'Madars Kalniņš': 1,
         'Rihards Lībietis': 1,
         'Gints Smukais': 1,
         'Mārtiņš Circenis': 1,
         'Vita Kalnciema': 1,
         'Rampa': 1,
         'Liāna Linde': 1,
         'Andra Biseniece': 1,
         'Marko Ojala': 1,
         'Matīss Repše': 1,
         'Ieva Gorda': 1,
         'A.\xa0Biseniece': 1,
         'Podziņas': 1,
         'Brīnumskapis': 1,
         'Tuta': 1,
         'Oskars Florencs-Vīksne': 1,
         'Kristaps Andersons': 1,
         'Donats Mockus': 1,
         'Inese Valtere': 1,
         'Gints Zilbalodis': 1,
         'Caesar': 1,
         'Ms\xa0Diāna Čivle': 1,
         'Amenda Perera': 1,
         "Auguste Rodin's": 1,
         'Rodin': 1,
         'Perera': 1,
         'Bastejkalns': 1,
         'Boris Petrovsky': 1,
         'Aljona Movko-Megi': 1,
         'Maxim Adel': 1,
         'Les Lumineoles': 1,
         'Frances Jobin': 1,
         'Markus Heckmann': 1,
         "Lina de Mola's": 1,
         'Ant Dickinson': 1,
         "Hermes Manjalardo's": 1,
         'Bille, Elza': 1,
         'Kate': 1,
         'Māris Grigalis': 1,
         'Rūta': 1,
         'Gints Grāvelis': 1,
         'Krišs': 1,
         'Anda Zemīte': 1,
         'Kārlis': 1,
         'Mārtiņš': 1,
         'Jēkabs': 1,
         'Jānis Strazds': 1,
         'Edgars Rinkēvičs': 1,
         'Mārcis Auziņš': 1,
         'Kārlis Auziņš': 1,
         'Inga Šļubovska-Kancēviča': 1,
         'Ēriks Upenieks': 1,
         'Gundars Lintiņš': 1,
         'Miķelis Vīte': 1,
         'Juris Vizbulis': 1,
         'Anna Keita Kreicšteina': 1,
         'Egīls Kupčs': 1,
         'Sonore': 1,
         'Rāte': 1,
         'Egils Melbārdis': 1,
         'Inese Krūmiņa': 1,
         'Raimonds Kalniņš': 1,
         'Rūdolfs Ozols': 1,
         'Andris Grunte': 1,
         'Andis Groza': 1,
         'Muklājs': 1,
         'Jānis Kokins': 1,
         'Erna Daugaviete': 1,
         'Strazdumuiža': 1,
         'Jāzeps Vītols': 1,
         'Dawn': 1,
         'Āgenskalns': 1,
         'Sarkandaugava': 1,
         'Luke Jerram': 1,
         'kim': 1,
         'The White Night': 1,
         'Citu dziesmu': 1,
         'Rolands Če': 1,
         'Rīgas': 1,
         'Dubra': 1,
         'Magnus Eriņš': 1,
         'Inga Ulmane': 1,
         'Mārtiņš Kanters': 1,
         'Dagamba': 1,
         'Henri Laķis': 1,
         'Gunārs Kalniņš': 1,
         'Brigita Reisone': 1,
         'Mihails Čuļpajevs': 1,
         'Gaetano Donizetti': 1,
         'Vincenzo Bellini': 1,
         'Giacomo Puccini': 1,
         'Pietro Mascagni': 1,
         'Ruggero Leoncavallo': 1,
         'Fryderyk Chopin': 1,
         'Valdis Skujiņš': 1,
         'Daži racionāli': 1,
         'Inga Pizāne': 1,
         'Elvīra Bloma': 1,
         'Inga Gaile': 1,
         'Agnese Krivade': 1,
         'Agnese Rutkēviča': 1,
         'Marija Luīze Meļķe': 1,
         'Edgars Mākens': 1,
         'Agnese Budovska': 1,
         'Edgars Rubenis': 1,
         'Paula Kronentāle': 1,
         'Emīls Dreiblats': 1,
         'Klāvs Lauls': 1,
         'Miķelis Putniņš': 1,
         'Rūdolfs Dankfelds': 1,
         'Kārlis Josts': 1,
         'Una Daniela': 1,
         'Siltā': 1,
         'Lielās': 1,
         'Ella Mežule': 1,
         'Olga Rajecka': 1,
         'Bel Tempo': 1,
         'Kaut kaili': 1,
         'Chris Noah': 1,
         'Laima Rācenāja': 1,
         'Mana Rīga': 1,
         'Juris Kulakovs': 1,
         'Vasara': 1,
         'Vasara kopā”': 1,
         'Summer Together': 1,
         'Dullais': 1,
         'Andrejs Ķiģelis': 1,
         'Svini': 1,
         'Ingus Ulmanis': 1,
         'Antra Stafecka': 1,
         'Mārtiņš Ruskis': 1,
         'Katram sava Rīga': 1,
         'Krastu': 1,
         'Kokle': 1,
         'Rikši': 1,
         'Zeltrači': 1,
         'Kaspars Zaviļeiski': 1,
         'Artūrs Krūzkops': 1,
         'Zoja Heimrāte': 1,
         'Edgars Lipors': 1,
         'Jauno Jāņu Orķestris': 1,
         'Ainars Bumbiers': 1,
         'Liepāja': 1,
         'Andris Ērglis': 1,
         'Fēlikss Ķiģelis': 1,
         'Strazds': 1,
         'Dzelzs': 1,
         'Ieva Aniņa': 1,
         'Daiļrade': 1,
         'Zane Burnicka': 1,
         'Andris Kapusta': 1,
         'R. Pauls': 1,
         'Labvēlīgais': 1,
         'Dejotprieks': 1,
         'Zāle': 1,
         'Zemgaļi': 1,
         'Ceidari': 1,
         'Jānis Purviņš': 1,
         'Dace Pezolli': 1,
         'Sergio Bonelli Editore': 1,
         "Aurelio Paviato's": 1,
         'Caljostro': 1,
         'Lolita Lipinska': 1,
         'Nadja Clarus': 1,
         'Mārtiņš Eņģelis': 1,
         'Sabīne Solovjeva': 1,
         'Victor Kipchirchir': 1,
         'Abera Mamo': 1,
         'Ezekiel Mutai': 1,
         'Sebastian Sawe': 1,
         'Judy Jelagat Kemboi': 1,
         'Birho Gidey': 1,
         'Mekides Shimeles': 1,
         'Hanne Verbruggen': 1,
         'Veronica Inglese': 1,
         'Edgars Šumskis': 1,
         'Kristaps Vējs-Āboliņš': 1,
         'Vadims Marinecs': 1,
         'Rimi Riga Marathon': 1,
         'Nguse Amlosom': 1,
         'Wisley Kimeli': 1,
         'James Kiplagat': 1,
         'Ayantu Kumela': 1,
         'Bone Cheluke': 1,
         'Jane Jelagat Seurey': 1,
         'Andualem Belay Shiferaw': 1,
         'Birke Debele Beyene': 1,
         'Jelena Prokopcuka': 1,
         'Prokopcuka': 1,
         'Anita Siliņa': 1,
         'Anna Klučņika': 1,
         'Renārs Roze': 1,
         'Kristaps Bērziņš': 1,
         'Alfrēds Apinis': 1,
         'Sandra Grosberga': 1,
         'Emīls Matiass Reinfelds': 1,
         'Salvis Gruševs': 1,
         'Lauris Grīniņš': 1,
         'Marta Luīze Pētersone': 1,
         'Giovanni Filippi': 1,
         'Ben Claridge': 1,
         'George Manangoi': 1,
         'Melanie Bovy': 1,
         'Emily Junginger': 1,
         'Ņikita Bogdanovs': 1,
         'Roberts Glazers': 1,
         'Elīna Gumarova': 1,
         'Alise Petrova': 1,
         'Zeidi': 1,
         'Dināra Rudāne': 1,
         'Jānis Aišpurs': 1,
         'Aurum': 1,
         'Vivere': 1,
         'Ritvars Logins': 1,
         'Rūta Dūduma-Ķirse': 1,
         'Lauris Amantovs’': 1,
         'Sōla': 1,
         'Ieva Parša': 1,
         'Emīls Klaužs': 1,
         'Armands Siliņš': 1,
         'Kaspars Ādamsons': 1,
         'Ārijs Šķepasts': 1,
         'Agnese Egliņa': 1,
         'Jānis Kurševs': 1,
         'Lidija Pupure': 1,
         'Jānis Peters': 1,
         'Balsis': 1,
         'Zigfrīds Muktupāvels': 1,
         'Uģis Tirzītis': 1,
         'Jēkabs Jančevskis': 1,
         'Georgs Zujevs': 1,
         'Viesturs Zeps': 1,
         'Mazā Vējzaķsala': 1,
         'Nympha': 1,
         'Augusts Folcs': 1,
         'Viesturdārzas': 1,
         'Mārtiņš Vilemsons': 1,
         'Skanste': 1,
         'Zirņu': 1,
         'Jāņa Dikmaņa': 1,
         'Jāņa Krūmiņa': 1,
         'Zahars Purvišķis': 1,
         'Mūsmājas': 1,
         'Zemīši': 1,
         'Zemītis': 1,
         'Riga Chamber': 1,
         'Aivars Smuidris': 1,
         'Stabat Mater': 1,
         'Uģis Prauliņš': 1,
         'Baiba Ērgle': 1,
         'Pārdaugava': 1,
         'Knuts Skujenieks': 1,
         'Goran Gora': 1,
         'Madara': 1,
         'Madara Fogelmane': 1,
         'Jauno Jāņu': 1,
         'Ilze Ozoliņa': 1,
         'Kalvis Kalniņš': 1,
         'Katrīna Feldmane': 1,
         'Edžus Kauke': 1,
         "George Frideric Handel's": 1,
         'Andris Veismans': 1,
         'Dāvis Stalts': 1,
         'Elīna Drāke': 1,
         'Agnese Cimuška-Rekke': 1,
         'Māra Lāce': 1,
         'Giovanni Carlo Federico Villa': 1,
         'Uffizi': 1,
         'Guicciardo Maria Sassoli': 1,
         'Vanessa Gavioli': 1,
         'Elena Marconi': 1,
         'Guicciardo Sassoli': 1,
         'Artūrs Analts': 1,
         'Boris': 1,
         'Daiga Upeniece': 1,
         'Elisabetta Rabajoli': 1,
         'Reinis Suhanovs': 1,
         'Silvija Grosa': 1})

In [117]:
Counter(entities_en)

Counter({'Riga': 188,
         'Latvian': 52,
         'Latvia': 38,
         'the Riga City Council': 33,
         'External Communication Division': 19,
         'the Communications Department': 19,
         'Project Coordinator': 16,
         'Italian': 16,
         'Rīga': 14,
         'Easter': 14,
         'European': 13,
         'Italy': 13,
         'Sweden': 12,
         'Rīgā': 11,
         'Town Hall Square': 10,
         'Biļešu': 10,
         'Europe': 10,
         'Vērmanes Garden': 10,
         'Canada': 9,
         'Skanste': 9,
         'Germany': 8,
         'Uzvaras Park': 8,
         'France': 8,
         'Līvu Square': 7,
         'the Town Hall Square': 7,
         'the Riga City Council’s': 7,
         'Riga Art Week': 7,
         'the Uffizi Gallery': 7,
         'Imanta': 6,
         'Kenya': 6,
         'Slovakia': 6,
         'the Latvian National Museum of Art': 6,
         'Doma Square': 5,
         'the Riga Porcelain Museum': 5,
         'Finland': 5,
         'the Second Advent': 5,
         'Miera Street': 5,
         'White Night': 5,
         'the Communication Department': 5,
         'Dzegužkalns': 5,
         'Berlin': 5,
         'congress': 5,
         'Riga Music Week': 5,
         'Slovenia': 5,
         'Austria': 5,
         'New Year’s Eve': 4,
         'Ziemeļblāzma': 4,
         'Riga Art Nouveau Centre': 4,
         'the United Kingdom': 4,
         'Flow': 4,
         'Baltic': 4,
         'the Republic of Latvia': 4,
         'the Freedom Monument': 4,
         'Dauderi Park': 4,
         'RakstuRīga': 4,
         'Riga Summer': 4,
         'Project Coordinator of the Department of External Communication': 4,
         'the Riga Dance Club': 4,
         'Zeidi': 4,
         'www.bilesuparadize.lv': 4,
         'Ethiopia': 4,
         'Florence': 4,
         'Palazzo Madama': 4,
         'Tornakalns': 3,
         'Chikki': 3,
         'Sigma': 3,
         'the Riga Congress Centre': 3,
         'the Culture Palace': 3,
         'Iļģuciems Culture Centre': 3,
         'Baltics': 3,
         'Paris': 3,
         'the Riga Investment and Tourism Agency': 3,
         'Esplanade': 3,
         'Riga Restaurant Week': 3,
         'Restaurant Week': 3,
         'Riga City Council': 3,
         'Mežaparks': 3,
         'RIGA': 3,
         'the "Staro Rīga" Light Festival': 3,
         'the Latvian National Opera': 3,
         'Old Riga': 3,
         'Summer Program': 3,
         'Nordeķi Park': 3,
         'Jaunība': 3,
         'the Riga Municipality': 3,
         'Grīziņkalns': 3,
         'Hive': 3,
         'USA': 3,
         'Riga Circus': 3,
         'Splendid Palace': 3,
         'the University of Latvia Library': 3,
         'Tallinn': 3,
         'Norway': 3,
         'Rimi Riga Marathon': 3,
         'Belgium': 3,
         'Switzerland': 3,
         'Czech Republic': 3,
         'Pils Square': 2,
         'the Powder Tower': 2,
         'Kaļķu Street': 2,
         'Vaļņu Street': 2,
         'Aspazijas Boulevard': 2,
         'Knīpas un Knauķi': 2,
         'Christmas Tree Decoration': 2,
         'the Chamber Hall of VEF Culture Palace': 2,
         'the Christmas Garden': 2,
         'the Tallinas Street Quarter': 2,
         'Sunny Groove Dixie': 2,
         'Čiekurs Čikijs': 2,
         'Budēļi': 2,
         'Balsis': 2,
         'Come Alongside for Christmas': 2,
         'Torņakalns': 2,
         'Ave Sol Concert Hall': 2,
         'Jāzeps Mediņš': 2,
         'the Riga Luther Church': 2,
         'the Culture Centre': 2,
         'the "Colours of the Seasons 2025': 2,
         'Winter"': 2,
         'Mirage Jazz Orchestra': 2,
         'KTMC': 2,
         'the "Small Guild': 2,
         'Old Town Christmas Market': 2,
         'Vienna': 2,
         'Madrid': 2,
         'Romanian': 2,
         'Riga Cathedral': 2,
         'the VEF Culture Palace': 2,
         'Latve': 2,
         'Muklājs': 2,
         'Iļģuciems': 2,
         'Ainārs Ančevskis': 2,
         'the Cathedral Square': 2,
         'the US Academy Award': 2,
         'Oscar': 2,
         'the Freedom Square': 2,
         'Portugal': 2,
         'Macedonia': 2,
         'Netherlands': 2,
         'Romania': 2,
         'Portuguese': 2,
         'Human': 2,
         'Herder Square': 2,
         'British': 2,
         '2025 Light Festival': 2,
         'Circles of Light': 2,
         'the National Library of Latvia': 2,
         'the Old Riga Light Circle': 2,
         'the Riga City Centre Park Light Circle': 2,
         'the Miera Street Light Circle': 2,
         'Freedom Square': 2,
         'VEF Culture Palace': 2,
         'the Culture Centre Iļģuciems': 2,
         'the Culture Centre Imanta': 2,
         'Vilkači': 2,
         'Live Rīga': 2,
         'the White Night': 2,
         'Kvadrifrons': 2,
         'Artis Robežnieks': 2,
         'Alternative Riga': 2,
         'BMX': 2,
         'the Riga Football Festival': 2,
         'the Riga District Championship': 2,
         'the Star Cup': 2,
         'Riga Municipality': 2,
         'Credo': 2,
         'Kalnciema Quarter': 2,
         'Brīnies, Rīga!': 2,
         'Vērmane Garden': 2,
         'Grīziņkalns Park': 2,
         'City Hall Square': 2,
         'Līgo.': 2,
         'the Ethnographic Open-Air Museum': 2,
         'the Great Day': 2,
         'Vilnius': 2,
         'Poland': 2,
         'Denmark': 2,
         'UK': 2,
         'Estonia': 2,
         'the City Hall': 2,
         'the Mežaparks Grand Stage': 2,
         'Opera Square': 2,
         'State': 2,
         'Bastejkalns': 2,
         'the Kokari Hall': 2,
         'EUR': 2,
         'the Madame Palace Museum': 2,
         'Turin': 2,
         'Morandi': 2,
         'the Italian Republic': 2,
         'Old Town': 1,
         'DJ': 1,
         'VJ': 1,
         'Afro': 1,
         'Latino': 1,
         'VJ DIGIDIVA': 1,
         'DnB': 1,
         'EDM': 1,
         'VJ Bear From Void': 1,
         'The Old Town Christmas Market': 1,
         'Focus 5': 1,
         'New Year': 1,
         'Advent city’s': 1,
         'Satikšanās': 1,
         'Sonante': 1,
         'Kazlēni un': 1,
         'Chamber Hall of VEF Culture Palace': 1,
         'Ritums': 1,
         'Jazz and Christmas': 1,
         'Santa Schiller’s': 1,
         'Vecrīga': 1,
         'Riga Porcelain Museum': 1,
         'A Tale of Christmas': 1,
         'Colors of the Season 2025': 1,
         'Winter Sparkles': 1,
         'Winter Solstice': 1,
         'the Tallinna Street quarter': 1,
         'Brička': 1,
         'Kekava': 1,
         'Snow Rose': 1,
         'Sadko': 1,
         'Riga Luther Church': 1,
         'Foundation Choir': 1,
         'the Angāra Concert Hall': 1,
         'Bastejkalns Park': 1,
         'Dixieland': 1,
         'the M/Workshop': 1,
         'Kalmes': 1,
         'the Miera Street Republic': 1,
         'Zāle': 1,
         'Laudate': 1,
         'Pirms Ziemassvētkiem': 1,
         'Ziemassvētku noskaņa': 1,
         'the Fourth Advent Concert': 1,
         'the Folk Art Centre': 1,
         'Angels': 1,
         'Star FM': 1,
         'Anglican Church of St Saviour': 1,
         'Ziemas bolero': 1,
         'the Riga Porcelain Museum’s': 1,
         'Christmas Tree Decorations': 1,
         'the Riga Art Nouveau Centre Museum': 1,
         'A Christmas Fairy Tale': 1,
         'the Riga Municipality Music': 1,
         'Riga Bolderaja School of Music': 1,
         'Riga Kengarags School of Music': 1,
         'Riga Pardaugava School of Music': 1,
         'Riga School of Art': 1,
         'Advent': 1,
         'Riga Luther Torņakalns Church': 1,
         'Come Alongside': 1,
         'the "Come Alongside!': 1,
         'Rihards Zaļupe': 1,
         'Sudden Lights': 1,
         "Music School Boys'": 1,
         'Silence and Light': 1,
         'the Torņakalns Church': 1,
         'Light': 1,
         'the Emīls Dārziņš Mixed Choir': 1,
         'the Third Advent': 1,
         'In the Brightness of Light Thoughts': 1,
         'Christmas Cantata': 1,
         '"Silent Transmission': 1,
         'the Hangar Concert Hall': 1,
         'Cone Chikie': 1,
         'The Language of the Heart on a Winter Evening': 1,
         'Biruta Ozoliņa': 1,
         'Christmas Oratorio': 1,
         'the Riga Chamber Choir': 1,
         'With a Snowclad Wing': 1,
         'the “Ave Sol” Concert Hall': 1,
         'the “Assembly Singers': 1,
         'Salve': 1,
         'the Art Academy of Latvia': 1,
         'Senais': 1,
         'the Palace of Culture': 1,
         'Norise': 1,
         "The Old Man's Mitten": 1,
         'European Best Christmas Markets 2025–2026': 1,
         'European Best Christmas Markets': 1,
         'more than 8 million': 1,
         'Forbes, Condé Nast Traveler': 1,
         'National Geographic': 1,
         'Edinburgh': 1,
         'Zurich': 1,
         'Craiova': 1,
         'Lithuania': 1,
         'Best Christmas Lights': 1,
         'Riga Local Government': 1,
         'Riga City Hall': 1,
         'the Small Guild Hall': 1,
         'the Riga Cathedral': 1,
         'Advent Dialogues': 1,
         "the Riga Cathedral Girls'": 1,
         'Tiara': 1,
         'Ticket Paradise': 1,
         'the VEF Culture Palace Mixed': 1,
         '5': 1,
         'Star': 1,
         'Colours of the Seasons 2025': 1,
         "the Riga Women's Chamber Choir": 1,
         "the Riga Pupils Palace Girls' Choir": 1,
         'Ildzēni': 1,
         'Piektais Tramvajs': 1,
         'Tallinas Street Quarter': 1,
         'Hangar Concert Hall': 1,
         'the Union of the Deaf of Latvia': 1,
         'Light a Bright Fire': 1,
         'Ave Sol concert hall': 1,
         'Cantus': 1,
         'Cantata': 1,
         'Christmas Stories': 1,
         'Juuk': 1,
         'the Culture and Folk Art Centre "Small Guild': 1,
         '12 Holy Nights': 1,
         "New Year's Eve": 1,
         'the association of persons': 1,
         'LeDome': 1,
         'the Restaurant Week': 1,
         'Whitehouse': 1,
         'Kotiņi': 1,
         'Flo': 1,
         'The Riga Investment and Tourism Agency': 1,
         'Fox': 1,
         'Tutas': 1,
         'the Culture and Folk Art Centre': 1,
         'John’s Church': 1,
         'The Christmas Garden': 1,
         'Svētās': 1,
         'Lutheran Church': 1,
         'the Splendid Palace': 1,
         'The Urban Art and Design Division': 1,
         'the Department of Education, Culture and Sport': 1,
         'Mūkusalas Street': 1,
         'cinema “Splendid Palace': 1,
         'Lithuanian': 1,
         'Riga Resident of the Year': 1,
         'Best Animated Feature Film': 1,
         'The Academy Awards': 1,
         'the European Film Academy Award': 1,
         'US Golden Globe Award': 1,
         'Annie Awards': 1,
         'the International Animated Film Association': 1,
         'Hollywood': 1,
         'US': 1,
         'French': 1,
         'Staro Rīga': 1,
         'Petals of Future Memories': 1,
         'Australian': 1,
         'Floating Stars': 1,
         'Macedonian': 1,
         'Touch a Star': 1,
         'Pixel Garden': 1,
         'The Eternal Living Room': 1,
         'Estonian': 1,
         'the Light Festival': 1,
         'Field of Fireflies': 1,
         'Porté': 1,
         'le Vent': 1,
         'the Old St. Gertrude Church': 1,
         'Canadian': 1,
         'German': 1,
         'Swedish': 1,
         'Lost and Found': 1,
         'the Latvian Academy of Culture quarter': 1,
         'Oculucis': 1,
         'Heritage': 1,
         'Mārcis': 1,
         'Kristers': 1,
         'Ralfs': 1,
         'the Latvian National Anthem': 1,
         'Latvian Sound Patterns': 1,
         'Latvian Classics': 1,
         'Modern Times': 1,
         'Rihards Mačanovskis': 1,
         'Rock Symphony': 1,
         'the Palace of Culture Ziemeļblāzma': 1,
         'the Culture and Folk Art Centre Mazā': 1,
         'the Kuldīga Culture Centre': 1,
         'Latvian National Theatre': 1,
         'the Pardaugava Culture Association': 1,
         'Ziemeļblāzma Culture Palace': 1,
         'Imanta Culture Centre': 1,
         'Music for Latvia': 1,
         'Latvian Academy of Music': 1,
         'Concert Hall Ave Sol': 1,
         'Light Festival': 1,
         'Heralds of the Dawn': 1,
         'Staro Rīga" Light Festival': 1,
         'Clear Springs': 1,
         "the White Night's": 1,
         'Avoti': 1,
         'Museum of the Moon': 1,
         'Videography': 1,
         'Sound Forest': 1,
         'Survival Kit': 1,
         "Contemporary Art Centre's": 1,
         'White Nights': 1,
         'Brussels': 1,
         'Rome': 1,
         'the Education, Culture': 1,
         'Sports Department': 1,
         'www.baltanakts.lv': 1,
         'Facebook': 1,
         '824th': 1,
         'Dome Square': 1,
         'Ukraine': 1,
         'Zeltrači"': 1,
         'Musiqq"': 1,
         '"Other Song Celebration': 1,
         'Brown Cheese': 1,
         'Pecolli': 1,
         'Antras Stafecka': 1,
         'the MC Orchestra': 1,
         'the AHHAA Science Centre': 1,
         'Esplanade Square': 1,
         'Serenade': 1,
         'Serenāde Rīgai': 1,
         'Dzegužkalns Park': 1,
         'Kautkaili': 1,
         'Pop Goes Classical': 1,
         'Kalnciems Quarter': 1,
         'Skani, Rīga': 1,
         'Mana Rīga': 1,
         'the Latvian National Opera and Ballet': 1,
         'Brigita Reisone': 1,
         'Mazurkas': 1,
         'K.R.E.D.O.': 1,
         'Some Rational Considerations': 1,
         'Henriks Eliass Zēgners': 1,
         'Alise Zariņa': 1,
         'Shipsea or Jānis Šipkēvics': 1,
         'Apgaismo': 1,
         'Dunka': 1,
         'Riga Circus School': 1,
         'Border Guard': 1,
         'Futurimo': 1,
         'Andžejs Grauds’': 1,
         'Katō': 1,
         'the Riga Circus School': 1,
         'Riga Summer Program': 1,
         'Skani': 1,
         'the Riga Dome Choir School': 1,
         'Autobuss': 1,
         'the Mirage Jazz Orchestra': 1,
         'Grezno': 1,
         'Ziepniekkalns Ēbelmuiža Park': 1,
         'Sporto, Rīga': 1,
         'Dreiliņkalns Park': 1,
         'the Baltic Sea': 1,
         'Vakarbuļļi Beach': 1,
         'the Kalnciema Quarter': 1,
         'Summer Outdoors': 1,
         'Čipsis': 1,
         'the Kalnciema Quarter Gallery': 1,
         '11 November Street': 1,
         'MC Orchestra': 1,
         'AHHAA': 1,
         'Esplanāde': 1,
         'Coastal Match': 1,
         'the External Communication Division': 1,
         'From Sun to Sun': 1,
         'DeLight': 1,
         'Ilga Reizniece': 1,
         'Ogas': 1,
         'Rahu': 1,
         'the New Folklore Group': 1,
         'The Green Theatre of Mežaparks': 1,
         'Zaļumballes': 1,
         'Crazy Dolls': 1,
         'the Herbal Eve': 1,
         'Facebook @RigaArtNouveau': 1,
         'Solstice': 1,
         'Victory Park': 1,
         'Mid-Summer': 1,
         'Daiļrades': 1,
         'the Cultural Palace': 1,
         'Celebrating Midsummer': 1,
         'Dejotāju Saime': 1,
         'the Culture Centre "Small Guild': 1,
         'the Riga Orchestra': 1,
         'Jāņa': 1,
         'the Uzvaras Park': 1,
         'Imantieši': 1,
         'the Ēbelmuiža Park': 1,
         'Ziepniekkalns': 1,
         'Bolderāja': 1,
         'the Ķengarags Music and Art School': 1,
         'Great Day': 1,
         'Līgo" and the middle generation dance collective "': 1,
         'Līgo"': 1,
         'Vilcenes': 1,
         'Savieši': 1,
         "Ēdol's Ķists": 1,
         'the Doms Square': 1,
         'The European Magic History Conference': 1,
         'the Baltic States': 1,
         'London': 1,
         'the Magic History Conference': 1,
         'www.mystero.lv': 1,
         'the Northern Europe': 1,
         'Illusionists in the History of the Riga Circus 1888–1916': 1,
         'Dreamers': 1,
         'Mystero': 1,
         'Magic Art in Cinema': 1,
         'Terror Island': 1,
         'Secrets of the History of Illusionism': 1,
         'Pārdaugava': 1,
         'Rūpniecības Street': 1,
         'the Riga Municipality Department of Education, Culture and Sports': 1,
         'the Italian Embassy': 1,
         "the International Women's Club": 1,
         'Polish': 1,
         'the Retro Auto Museum': 1,
         'Budimex': 1,
         'On the Way to the Balance': 1,
         'Splendid palace': 1,
         'the Berlin Ministry for Economic Affairs': 1,
         'Energy and Entrepreneurship': 1,
         '2nite': 1,
         'the Riga Municipality City Development Department Strategic Management Board': 1,
         'Mežciems': 1,
         'Project Coordinator for External Communications Department': 1,
         'Scandinavia': 1,
         'Vilnis Ķirsis': 1,
         'No Heat Waves': 1,
         'Just Sea Waves': 1,
         'airBaltic': 1,
         'British Airways': 1,
         'Forbes': 1,
         'UK Post Office': 1,
         'the Riga Contemporary Art Fair': 1,
         'the Rimi Riga Marathon': 1,
         'Agate Caune’s': 1,
         'the Rimi Riga Half Marathon': 1,
         'Padua Half Marathon': 1,
         'the Lille International Half Marathon': 1,
         'Uganda': 1,
         'World Running Champion': 1,
         'Bosena Mulatie': 1,
         'The Hague Half Marathon': 1,
         'Eritrea': 1,
         'Riyadh Marathon': 1,
         'Barcelona': 1,
         'Hamburg': 1,
         'Geneva': 1,
         'Singapore': 1,
         'São Paulo': 1,
         'the Latvian Marathon Championship': 1,
         'Agate Caune': 1,
         'U23': 1,
         '31:33': 1,
         'Manchester': 1,
         'Kitija Valtere': 1,
         'World Orienteering Championship': 1,
         'European Running Championships': 1,
         'World Running Championships': 1,
         'PB': 1,
         '1500m PB': 1,
         'Latvians': 1,
         '5:24.74': 1,
         'The Rimi Riga Marathon': 1,
         'LTV': 1,
         'Museum night': 1,
         'the City Council Chamber, Portrait': 1,
         'the City Council': 1,
         'The European Museum': 1,
         'Riga Centre': 1,
         'Centre – Teika – Jugla – Mežciems': 1,
         'Āgenskalns': 1,
         'Zolitūde': 1,
         'Centre – Purvciems': 1,
         'Pļavnieki': 1,
         'SIA': 1,
         'The Dome Square': 1,
         'the Restoration of the Independence of the Republic of Latvia': 1,
         'The Riga Municipality': 1,
         'Latvia of Flowers': 1,
         'Ziedu Latvija': 1,
         'BigGames': 1,
         'Kokle': 1,
         'Grodi': 1,
         'Skandinieki': 1,
         'the Independence Day': 1,
         'Roots That Bind': 1,
         'Igo': 1,
         'Aura': 1,
         'Rikši': 1,
         'The Splendid Palace': 1,
         'Latvian Film Marathon': 1,
         'The Culture Centre Iļģuciems': 1,
         'Improvisation on Folk Songs': 1,
         'the youth chamber choir': 1,
         'May You Live Forever': 1,
         'the Culture Palace Ziemeļblāzma': 1,
         'National Guard': 1,
         'the Latvian Academy of Culture': 1,
         'Words of Power for Latvia': 1,
         'the Convent Yard': 1,
         'the Independence of the Republic of Latvia': 1,
         'the Popular Front of Latvia': 1,
         'Supreme Council': 1,
         'We Are Composed': 1,
         'the Kokaru Hall': 1,
         'the Latvian National Awakening': 1,
         'Music School Boys’ Choir': 1,
         'the Riga Dome Boys’ Choir': 1,
         'Juventus': 1,
         'Romāns Vanags': 1,
         'Ints Teterovskis': 1,
         'Valdis Tomsons': 1,
         'Artūrs Mitrevics': 1,
         'the Housing and Environment Committee': 1,
         'the Park Uzvara': 1,
         'the Park Ziemeļblāzma': 1,
         'the Old Riga': 1,
         'LLC': 1,
         '9th Transverse Line': 1,
         'the Riga Municipality Housing and Environment Department': 1,
         'the Congress House': 1,
         'the Esplanade square': 1,
         'Seasons': 1,

In [118]:
en_chunks_counted = dict(Counter(df_en.chunks.explode().tolist()))

big_chunks_en = {}
for k, v in en_chunks_counted.items():
    if " " in k:
        if k not in big_chunks_en:
            big_chunks_en[k] = 0
        big_chunks_en[k] += v

sorted(big_chunks_en.items(), key=lambda item: item[1], reverse=True)

[('the Riga City Council', 29),
 ('the concert', 28),
 ('the city', 24),
 ('the event', 22),
 ('Project Coordinator', 21),
 ('Ineta Miglāne', 20),
 ('External Communication Division', 19),
 ('the Communications Department', 19),
 ('the opportunity', 15),
 ('a concert', 14),
 ('the evening', 12),
 ('the audience', 11),
 ('the band', 11),
 ('The concert', 11),
 ('the world', 11),
 ('Town Hall Square', 9),
 ('the participation', 9),
 ('Vērmanes Garden', 9),
 ('Riga residents', 8),
 ('07:00 p.m.', 8),
 ('Free invitations', 8),
 ('The event', 8),
 ('the park', 8),
 ('the day', 8),
 ("Riga's birthday", 8),
 ('creative workshops', 8),
 ('the project', 8),
 ('Līvu Square', 7),
 ('the Town Hall Square', 7),
 ('the information', 7),
 ('the Riga City Council’s social media pages', 7),
 ('the Republic', 7),
 ('the motto', 7),
 ('the Uffizi Gallery', 7),
 ('the capital', 6),
 ('the website www.kultura.riga.lv', 6),
 ('the municipality', 6),
 ('VEF Culture Palace', 6),
 ('the museum', 6),
 ('the first time', 6),
 ('Uzvaras Park', 6),
 ('the history', 6),
 ('16 August', 6),
 ('the slogan', 6),
 ('Riga Art Week', 6),
 ('the marathon', 6),
 ('the Latvian National Museum', 6),
 ('the year', 5),
 ('Doma Square', 5),
 ('the workshop', 5),
 ('04:00 p.m.', 5),
 ('the same time', 5),
 ('the end', 5),
 ('the children', 5),
 ('More information', 5),
 ('the Second Advent', 5),
 ('the residents', 5),
 ('the ice skating-rink', 5),
 ('the Department', 5),
 ('the "Staro Rīga" Light Festival', 5),
 ('contemporary art', 5),
 ('the stage', 5),
 ('the neighbourhoods', 5),
 ('the Communication Department', 5),
 ('the art', 5),
 ('The project', 5),
 ('New Year', 4),
 ('Eve events', 4),
 ('12:00 p.m.', 4),
 ('the concert hall', 4),
 ('“Ave Sol', 4),
 ('21 December', 4),
 ('the courtyard', 4),
 ('the exhibition', 4),
 ('the Riga Porcelain Museum', 4),
 ('the United Kingdom', 4),
 ('Fredis Bikovs', 4),
 ('the area', 4),
 ('the association', 4),
 ('Riga City Council', 4),
 ('the cat', 4),
 ('a wide range', 4),
 ('the festival', 4),
 ('a programme', 4),
 ('the night', 4),
 ('the Freedom Monument', 4),
 ('Ance Krauze', 4),
 ('Juris Kaukulis', 4),
 ('the Latvian National Opera', 4),
 ('the streets', 4),
 ('the forum', 4),
 ('cultural events', 4),
 ('the market', 4),
 ('the programme', 4),
 ('Dauderi Park', 4),
 ('Riga Summer', 4),
 ('the website', 4),
 ('Tatjana Smirnova', 4),
 ('External Communication', 4),
 ('Advance booking', 4),
 ('the congress', 4),
 ('an exhibition', 4),
 ('The exhibition', 4),
 ('the development', 4),
 ('the mayor', 4),
 ('project coordinator', 4),
 ('20 April', 4),
 ('DJ Linda Samsonova', 3),
 ('the diversity', 3),
 ('06:00 p.m.', 3),
 ('03:00 p.m.', 3),
 ('reduced mobility', 3),
 ('phone +371', 3),
 ('The programme', 3),
 ('12:45 p.m.', 3),
 ('25 December', 3),
 ('special needs', 3),
 ('Christmas melodies', 3),
 ('The elves', 3),
 ('a special gift', 3),
 ('the little ones', 3),
 ('a little cone', 3),
 ('a Christmas tree ornament', 3),
 ('the warm festive feeling', 3),
 ('the miracle', 3),
 ('The evening', 3),
 ('the group', 3),
 ('the Riga Congress Centre', 3),
 ('the collection', 3),
 ('The festival', 3),
 ('Iļģuciems Culture Centre', 3),
 ('the mixed choir', 3),
 ('this concert', 3),
 ('the "Colours', 3),
 ('the Seasons 2025" series', 3),
 ('youth vocal ensemble', 3),
 ('3rd place', 3),
 ('the Baltics', 3),
 ('the Riga Investment and Tourism Agency', 3),
 ('the Esplanade', 3),
 ('Restaurant Week', 3),
 ('the future', 3),
 ('the moment', 3),
 ('the animated film "Flow', 3),
 ('light objects', 3),
 ("this year's festival", 3),
 ('the installation', 3),
 ('the water', 3),
 ('four days', 3),
 ('the light objects', 3),
 ('a wide programme', 3),
 ('the celebration', 3),
 ('the concerts', 3),
 ('the time', 3),
 ('the events', 3),
 ('sports activities', 3),
 ('street musicians', 3),
 ('Old Riga', 3),
 ('a variety', 3),
 ('the birthday', 3),
 ('a platform', 3),
 ('different generations', 3),
 ('14 August', 3),
 ("Riga's Summer Program", 3),
 ("Riga's rich cultural heritage", 3),
 ('characteristic features', 3),
 ('contemporary urban cultural life', 3),
 ('the central events', 3),
 ('birthday events', 3),
 ('the Riga City Council social media pages', 3),
 ('Further information', 3),
 ('Nordeķi Park', 3),
 ('the Riga Municipality', 3),
 ("Riga's residents", 3),
 ('a festival', 3),
 ('23 August', 3),
 ('Katrīna Dimanta', 3),
 ('the ethno company', 3),
 ('Free entry', 3),
 ('the folk dance ensemble', 3),
 ('19 June', 3),
 ('the cultural space', 3),
 ('a press conference', 3),
 ('the participants', 3),
 ('the theatre', 3),
 ('the cinema “Splendid Palace', 3),
 ('night time', 3),
 ('an opportunity', 3),
 ('the capital city', 3),
 ('this year', 3),
 ('a time', 3),
 ('half marathon', 3),
 ('the restoration', 3),
 ('the local government', 3),
 ('Riga municipality', 3),
 ('the territory', 3),
 ('The system', 3),
 ('Italian arts', 3),
 ('the support', 3),
 ('the Embassy', 3),
 ('Pils Square', 2),
 ('the square', 2),
 ('the Powder Tower', 2),
 ('the parallel street', 2),
 ('11\xa0November Embankment', 2),
 ('Poļu and Bīskapa Gāte', 2),
 ('Kaļķu Street', 2),
 ('Vaļņu Street', 2),
 ('Aspazijas Boulevard', 2),
 ('DJ Sets', 2),
 ('DJ Gustavito', 2),
 ('DJ Aspirins', 2),
 ('DJ All-Viss', 2),
 ('MC Valters Krauze', 2),
 ('a musical journey', 2),
 ('the walls', 2),
 ('the buildings', 2),
 ('the Old Town', 2),
 ('other parts', 2),
 ('the fourth week', 2),
 ('concert programmes', 2),
 ('the cultural palace', 2),
 ('a musical performance', 2),
 ('Knīpas un Knauķi', 2),
 ('the lecture', 2),
 ('the route', 2),
 ('“Biļešu paradīze” box offices', 2),
 ('one porcelain souvenir', 2),
 ('openwork decoration', 2),
 ('porcelain moulds', 2),
 ('up to 10\xa0persons', 2),
 ('20 December', 2),
 ('02:00 p.m.', 2),
 ('“Riga Art Nouveau Centre', 2),
 ('an event', 2),
 ('Christmas traditions', 2),
 ('A museum ticket', 2),
 ('especially families', 2),
 ('the Chamber Hall', 2),
 ('the Christmas Garden', 2),
 ('a market', 2),
 ('the Tallinas Street Quarter', 2),
 ('Čiekurs Čikijs', 2),
 ('08:00 p.m.', 2),
 ('05:00 p.m.', 2),
 ('the website bilesuparadize.lv', 2),
 ('conductor Valdis Butāns', 2),
 ('Latvian artists', 2),
 ('Ave Sol Concert Hall', 2),
 ('Ilona Bagele', 2),
 ('Intars Busulis', 2),
 ('young people', 2),
 ('the Riga Luther Church', 2),
 ('12 December', 2),
 ('Latvian composers', 2),
 ('the Riga Chamber Choir "Ave Sol', 2),
 ('Mirage Jazz Orchestra', 2),
 ('the concert performance', 2),
 ('the "Small Guild', 2),
 ('A total', 2),
 ('The number', 2),
 ('the title', 2),
 ('the VEF Culture Palace', 2),
 ('the Light', 2),
 ('the cultural centre', 2),
 ('the music', 2),
 ('the piano', 2),
 ('Ainārs Ančevskis', 2),
 ('the rink', 2),
 ('The ice skating-rink', 2),
 ('Opening hours', 2),
 ('The installation', 2),
 ('the city’s cultural life', 2),
 ('Riga Restaurant Week', 2),
 ('participating restaurants', 2),
 ('the campaign', 2),
 ('The audience', 2),
 ('Small Guild', 2),
 ('the Cathedral Square', 2),
 ('Doma laukums', 2),
 ('the Culture', 2),
 ('the urban environment', 2),
 ('the meantime', 2),
 ('the characters', 2),
 ('the environmental object', 2),
 ('the Freedom Square', 2),
 ('local artists', 2),
 ('the Netherlands', 2),
 ('one third', 2),
 ('the total selection', 2),
 ('the rest', 2),
 ('Herder Square', 2),
 ('a place', 2),
 ('a collaboration', 2),
 ('quantum entanglement', 2),
 ('The idea', 2),
 ('20/22\xa0Miera Street', 2),
 ('each visitor', 2),
 ('Staro Rīga" Light Festival', 2),
 ('The route', 2),
 ('the "Staro Rīga', 2),
 ('2025 Light Festival', 2),
 ('six "Circles', 2),
 ('the National Library', 2),
 ('the Old Riga Light Circle', 2),
 ('the Freedom Monument Light Circle', 2),
 ('the Riga City Centre Park Light Circle', 2),
 ('the Freedom Street Light Circle', 2),
 ('the final one', 2),
 ('the Miera Street Light Circle', 2),
 ('Full programme', 2),
 ('the website www.staroriga.lv', 2),
 ('the symbol', 2),
 ('18 November', 2),
 ('Freedom Square', 2),
 ('the Riga Orchestra', 2),
 ('the Culture Centre Iļģuciems', 2),
 ('bass guitar', 2),
 ('the Culture Centre Imanta', 2),
 ('Biļešu paradīze box offices', 2),
 ('Riga Art Nouveau Centre', 2),
 ('the joy', 2),
 ('The theme', 2),
 ('a new day', 2),
 ('a herald', 2),
 ('a total length', 2),
 ('foreign tourists', 2),
 ('White Night', 2),
 ('The goal', 2),
 ('the White Night', 2),
 ('all ages', 2),
 ('Latvian and foreign artists', 2),
 ('a craft market', 2),
 ('the epicentre', 2),
 ("Riga's birthday celebrations", 2),
 ("the city's diversity", 2),
 ('environmental installations', 2),
 ('historical stories', 2),
 ('an antique car parade', 2),
 ('poetry competitions', 2),
 ('diverse culinary experiences', 2),
 ('DJ sets', 2),
 ("Riga's stories", 2),
 ('the port', 2),
 ('the bustle', 2),
 ("the city's rich history", 2),
 ('its creative present', 2),
 ('the theme', 2),
 ('the rhythms', 2),
 ('well-known pop artists', 2),
 ('Ieva Sutugova', 2),
 ('Artis Robežnieks', 2),
 ('the Uzvaras Park', 2),
 ('their own character', 2),
 ('their own Riga', 2),
 ('Alternative Riga', 2),
 ('contemporary performances', 2),
 ('Creative communities', 2),
 ('other organizations', 2),
 ('skateboarding, roller-blading, and scooter shows', 2),
 ('the skate park', 2),
 ('the Uzvaras Park stage', 2),
 ('current, alternative and independent artists', 2),
 ('an exciting series', 2),
 ('especially young people', 2),
 ('17 August', 2),
 ('Football fans', 2),
 ('the Riga Football Festival', 2),
 ('16 and 17 August', 2),
 ("a children's and youth tournament", 2),
 ('the Riga District Championship', 2),
 ('the Star Cup', 2),
 ('well-known personalities', 2),
 ('spectator areas', 2),
 ('food outlets', 2),
 ('DJ music', 2),
 ('various interactive activities', 2),
 ('15 August', 2),
 ('the canal', 2),
 ('pianist Dainis Tenis', 2),
 ('the atmosphere', 2),
 ('the five hundredth anniversary', 2),
 ('a Latvian book', 2),
 ('My Riga', 2),
 ('Riga Municipality', 2),
 ('Brigita Reisone', 2),
 ('whose voice', 2),
 ('The second part', 2),
 ('Kopā Reti Esošu Draugu Organizācija', 2),
 ('Kalnciema Quarter', 2),
 ('a number', 2),
 ('big wooden games', 2),
 ('Vērmane Garden', 2),
 ('the bands', 2),
 ('Grīziņkalns Park', 2),
 ('the festivities', 2),
 ('The events', 2),
 ('a wide variety', 2),
 ('The park', 2),
 ('the Riga Dance Club', 2),
 ('the sunrise', 2),
 ('the musical group', 2),
 ('20 June', 2),
 ('21 June', 2),
 ('various techniques', 2),
 ('City Hall Square', 2),
 ('18 June', 2),
 ('the middle generation dance collective', 2),
 ('a wreath-making workshop', 2),
 ('the Ethnographic Open-Air Museum', 2),
 ('21 August', 2),
 ('24 August', 2),
 ('the organisers', 2),
 ('the illusionist theatre', 2),
 ('Enrico Pezolli', 2),
 ('this event', 2),
 ('Vilnis Ķirsis', 2),
 ('historical tricks', 2),
 ('the conference', 2),
 ('the History', 2),
 ('the performance', 2),
 ('the University', 2),
 ('Latvia Library', 2),
 ('the night balance', 2),
 ('the presentations', 2),
 ('night work', 2),
 ('many sectors', 2),
 ('other cities', 2),
 ('a more than 20% increase', 2),
 ('the previous year', 2),
 ('This growth', 2),
 ('overnight stays', 2),
 ('an elite athlete', 2),
 ('the 10 km race', 2),
 ('national records', 2),
 ('the 10 km', 2),
 ('the City Hall', 2),
 ('the offices', 2),
 ('the animated film “Flow', 2),
 ('the Riga municipality', 2),
 ('the 35th anniversary', 2),
 ('the Independence', 2),
 ('city guests', 2),
 ('the national costume', 2),
 ('folk costumes', 2),
 ('the independence', 2),
 ('the period', 2),
 ('the Latvian state', 2),
 ('the Mežaparks Grand Stage', 2),
 ('the leadership', 2),
 ('the arrival', 2),
 ('their operation', 2),
 ('various neighbourhoods', 2),
 ('Opera Square', 2),
 ('the management', 2),
 ('recent years', 2),
 ('the Skanste neighbourhood', 2),
 ('outdoor exercise equipment', 2),
 ('engineering networks', 2),
 ('the opening', 2),
 ('a great deal', 2),
 ('the specific support objective', 2),
 ('original songs', 2),
 ('its turn', 2),
 ('a story', 2),
 ('21 April', 2),
 ('19 April', 2),
 ('museum entrance ticket', 2),
 ('the twilight', 2),
 ('the Kokari Hall', 2),
 ('the Second Easter', 2),
 ('“Riga Music Week', 2),
 ('the potential', 2),
 ('the image', 2),
 ('an industry conference', 2),
 ('Riga Music Week', 2),
 ('The local government', 2),
 ('the total estimate', 2),
 ('the Madame Palace Museum', 2),
 ('“Italian light', 2),
 ('the 6th', 2),
 ('19th centuries', 2),
 ('Modern Art', 2),
 ('the Italian Republic', 2),
 ('Exhibition "Palazzo Madama', 2),
 ('"Italian light', 2),
 ('a joyful celebration', 1),
 ('09.00 p.m.', 1),
 ('02.00 a.m.', 1),
 ('six festival squares', 1),
 ('the section', 1),
 ('The Old Town squares', 1),
 ('festive spirit', 1),
 ('popular and favourite DJs', 1),
 ('Each square', 1),
 ('a single audiovisual performance', 1),
 ("the DJ's musical performance", 1),
 ("the VJ's visual projections", 1),
 ('the building façades', 1),
 ('a unique multimedia experience', 1),
 ('Visual art', 1),
 ('LED screens', 1),
 ('the 11\xa0November embankment', 1),
 ('positive and rhythmically diverse electronic music', 1),
 ('Afro, Latino, funk and disco vibes', 1),
 ('a world', 1),
 ('VJ DIGIDIVA', 1),
 ('the visual projections', 1),
 ("the Blackheads' House", 1),
 ('hip-hop, trap and house elements', 1),
 ('electronic dance music rhythms', 1),
 ('VJ Slavpapii', 1),
 ('these rhythms', 1),
 ('VJ Mersedes Margoit', 1),
 ('a festive mood and multimedia adventure', 1),
 ('Latvian and foreign golden hits', 1),
 ('VJ Arsenijs Rozenbahs', 1),
 ('a party', 1),
 ('electronic music', 1),
 ('tried-and-tested party hits', 1),
 ('a real party vibe', 1),
 ('the stretch', 1),
 ('an energetic open format', 1),
 ('Top 40 remixes', 1),
 ('one dynamic stream', 1),
 ('VJ Wickiss', 1),
 ('the visual design', 1),
 ('The street', 1),
 ('a free, multi-coloured set', 1),
 ('this evening', 1),
 ('a specific genre', 1),
 ('his love', 1),
 ('different musical moods', 1),
 ('VJ Bear', 1),
 ('colourful and varied visuals', 1),
 ('the LED screens', 1),
 ('The Old Town Christmas Market', 1),
 ('the heart', 1),
 ('DJ Wolf', 1),
 ('p.m.-11.00 p.m.', 1),
 ('the Market', 1),
 ('10.00 a.m.', 1),
 ('08.00 p.m.', 1),
 ('each venue', 1),
 ('a moderator', 1),
 ('the festive spirit', 1),
 ('New Year celebrations', 1),
 ('the highlights', 1),
 ('the past year', 1),
 ('Hot drinks', 1),
 ('the event venues', 1),
 ('Advent city’s inhabitants', 1),
 ('various concerts', 1),
 ('mask workshops', 1),
 ('a traditional log', 1),
 ('evening and masquerade procession', 1),
 ('concert halls', 1),
 ('several concerts', 1),
 ('city’s inhabitants', 1),
 ('the concert hall “Ave Sol', 1),
 ('the mixed choir “Sonante', 1),
 ('“Kazlēni un vilks', 1),
 ('the children’s vocal studio', 1),
 ('Chamber Hall', 1),
 ('the women’s choir “Dzintars', 1),
 ('the Christmas concert', 1),
 ('Entrance fee EUR', 1),
 ('Riga’s inhabitants', 1),
 ('traditional mask making', 1),
 ('the Culture and folk art centre “Ritums', 1),
 ('Entry fee EUR', 1),
 ('19 December', 1),
 ('08:30 p.m.', 1),
 ('the traditional log', 1),
 ('evening masquerade procession', 1),
 ('Rātslaukums)-Skārņu Street-Audēju Street-Vaļņu Street-Kalķu Street-Līvu Square-Zirgu Street-Doma Square-Town Hall Square',
  1),
 ('Bonfire lighting', 1),
 ('traditional winter solstice rituals', 1),
 ('Folklore groups', 1),
 ('the regions', 1),
 ('the Culture centre “Imanta', 1),
 ('the concert program', 1),
 ('Santa Schiller’s Jazz Sextet', 1),
 ('the youth choir', 1),
 ('The festive creative workshops', 1),
 ('Christmas Tree Decoration', 1),
 ('01:30 p.m.', 1),
 ('Riga Porcelain Museum', 1),
 ('The thematic creative workshop', 1),
 ('11:00 a.m.', 1),
 ('“A Tale', 1),
 ('the tree', 1),
 ('Advance registration', 1),
 ('the e-mail address jugendstils@riga.lv', 1),
 ('the museum’s working hours', 1),
 ('the last concert', 1),
 ('the cycle', 1),
 ('the Season', 1),
 ('” “Winter Sparkles', 1),
 ('the solstice celebration', 1),
 ('“Winter Solstice', 1),
 ('the Tallinna Street quarter', 1),
 ('the folklore group “Brička', 1),
 ('a musical collective', 1),
 ('the Kekava (Ķekava) Municipality', 1),
 ('traditional games', 1),
 ('traditional dances', 1),
 ('a folklore group', 1),
 ('all generations', 1),
 ('"Snow Rose', 1),
 ('the folk instrument orchestra “Sadko', 1),
 ('01:00 p.m.', 1),
 ('03:30 p.m.', 1),
 ('26 December', 1),
 ('Riga Luther Church', 1),
 ('creative workshop', 1),
 ('photo corner', 1),
 ('a reflection path', 1),
 ('the church', 1),
 ('the “Nāc līdzās” Foundation Choir', 1),
 ('the Angāra Concert Hall', 1),
 ('Bastejkalns Park', 1),
 ('24 December', 1),
 ('“Sunny Groove Dixie” Dixieland band', 1),
 (', 21 December', 1),
 ('the M/Workshop', 1),
 ('a carnival', 1),
 ('an authentic Budēļi mask-making workshop', 1),
 ('textile artist', 1),
 ('Emma Sofija', 1),
 ('Solstice feast', 1),
 ('the vocal ensemble', 1),
 ('a log', 1),
 ('a community masked procession', 1),
 ('the craft beer bar “Labietis', 1),
 ('the Miera Street Republic community', 1),
 ('the sacred fire', 1),
 ('the log', 1),
 ('06:30 p.m.', 1),
 ('the band “Zāle', 1),
 ('the mask workshop', 1),
 ('the “Ave Sol” Mixed Choir “Laudate', 1),
 ('a string quartet', 1),
 ('22 December', 1),
 ('“Pirms Ziemassvētkiem', 1),
 ('the Riga Chamber Choir “Ave Sol', 1),
 ('Annika Lanka', 1),
 ('the Fourth Advent Concert', 1),
 ('the Folk Art Centre “Mazā ģilde', 1),
 ('the “Mazā ģilde', 1),
 ('07:30 p.m.', 1),
 ('10:30 p.m.', 1),
 ('the charity campaign', 1),
 ('beloved Latvian musicians', 1),
 ('a mobile studio', 1),
 ('radio “Star FM', 1),
 ('a donation booth', 1),
 ('festive treats', 1),
 ('11:00 p.m.', 1),
 ('Anglican Church', 1),
 ('St Saviour', 1),
 ('the youth choir “Balsis', 1),
 ('“Ziemas bolero', 1),
 ('the Orchestra “Rīga', 1),
 ('Aija Vītoliņa', 1),
 ('Normunds Rutulis', 1),
 ('pianist Rihards Plešanovs', 1),
 ('the “Biļešu paradīze” box office', 1),
 ('15 December', 1),
 ('6 January', 1),
 ('the Riga Porcelain Museum’s workshop', 1),
 ('a festive exhibition “Christmas Tree Decorations', 1),
 ('Christmas tree decorations', 1),
 ('2 December', 1),
 ('the Riga Art Nouveau Centre Museum', 1),
 ('“A Christmas Fairy Tale', 1),
 ('the early 20th century', 1),
 ('historical trinkets', 1),
 ('interior objects', 1),
 ('the festive mood', 1),
 ('the museum’s premises', 1),
 ('both the museum’s collection', 1),
 ('Christmas decorations', 1),
 ('artist Tamara Čudnovska', 1),
 ('Entrance ticket', 1),
 ('9 December', 1),
 ('29 January', 1),
 ('the exhibition halls', 1),
 ('the Culture Palace “Ziemeļblāzma', 1),
 ('the Riga Municipality Music and Art School Winter Festival “Christmas Stars',
  1),
 ('Riga art schools', 1),
 ('Riga Bolderaja School', 1),
 ('Riga Kengarags School', 1),
 ('Riga Pardaugava School', 1),
 ('Māra Muižniece’s Riga School', 1),
 ('the third week', 1),
 ('a charity concert', 1),
 ('your own Christmas tree ornament', 1),
 ('a creative workshop', 1),
 ('11 December', 1),
 ('The annual charity concert', 1),
 ('Riga Luther Torņakalns Church', 1),
 ('the integrative arts festival', 1),
 ('the "Come', 1),
 ('outstanding Latvian stage artists', 1),
 ('Daniils Bulajevs', 1),
 ('Rihards Zaļupe', 1),
 ('Kārlis Kazāks', 1),
 ('Paula Saija', 1),
 ('Renāte Zviedre', 1),
 ('Annija Putniņa', 1),
 ('Aleksandra Špicberga', 1),
 ('Kristīne Pāže', 1),
 ('"Sudden Lights', 1),
 ('The musical sound', 1),
 ("the Jāzeps Mediņš Riga 1st Music School Boys' Choir", 1),
 ('a Christmas Charity Market', 1),
 ('Christmas gifts', 1),
 ('a donation', 1),
 ('the outlets', 1),
 ('‘Biļešu paradīze', 1),
 ('every Sunday', 1),
 ('the Third Sunday', 1),
 ('a Christmas garden', 1),
 ('the Torņakalns Church', 1),
 ('the VEF Culture Palace Choir "Jasmīnas', 1),
 ('the festive workshop', 1),
 ('"Christmas Tree Decoration', 1),
 ('The workshop', 1),
 ('The finished work', 1),
 ("two weeks' time", 1),
 ('13 December', 1),
 ('the Emīls Dārziņš Mixed Choir', 1),
 ('artistic director Rihards Lapiņš', 1),
 ('conductor Jēkabs Krists Kalniņš', 1),
 ('Folk music lovers', 1),
 ('‘Wooden Rīga', 1),
 ('12\xa0Krāsotāju Street', 1),
 ('the Third Advent', 1),

Riga EN. По номерам файлов, не в датасете

- празднования/кульутрные программы (с концертами, мастер-классами, маскарадами и т.д.)
 - 1, 2, 3, 4, 5, 8, 11, 14, 15, 16, 17, 18, 25, 26, 28, 30
- фестиваль - 10, 12
- форум (включающий лекции, искусство, концерты) - 13, 19, 20
- выставка - 23, 31
- физ. активности - 6
- кулинария - 7
- кино - 9
- туризм - 21
- марафон - 22
- спорт -  24
- проект (парк) - 27
- статуи - 29

Подсчёт:

- празднования/кульутрные программы (с концертами, мастер-классами, маскарадами и т.д.) - 16
- форум (включающий лекции, искусство, концерты) - 3
- фестиваль - 2
- выставка - 2
- физические активности - 1
- марафон - 1
- спортивные трансляции - 1

In [119]:
countries = []

for typ, name in zip(riga_en.named_entities_type.explode(), riga_en.named_entities.explode()):
    if typ in ["GPE", "LANGUAGE", "NORP"]:
        countries.append(name.text)
    
Counter(countries)

Counter({'Riga': 188,
         'Latvian': 52,
         'Latvia': 38,
         'Italian': 16,
         'European': 13,
         'Italy': 13,
         'Sweden': 12,
         'Canada': 9,
         'Germany': 8,
         'France': 8,
         'Kenya': 6,
         'Slovakia': 6,
         'Finland': 5,
         'Berlin': 5,
         'Slovenia': 5,
         'Austria': 5,
         'Easter': 5,
         'Ziemeļblāzma': 4,
         'the United Kingdom': 4,
         'Uzvaras Park': 4,
         'Baltic': 4,
         'the Republic of Latvia': 4,
         'www.bilesuparadize.lv': 4,
         'Ethiopia': 4,
         'Florence': 4,
         'Paris': 3,
         'RIGA': 3,
         'Old Riga': 3,
         'Nordeķi Park': 3,
         'the Riga Municipality': 3,
         'USA': 3,
         'Tallinn': 3,
         'Norway': 3,
         'Belgium': 3,
         'Switzerland': 3,
         'Czech Republic': 3,
         'Vienna': 2,
         'Madrid': 2,
         'Romanian': 2,
         'Iļģuciems': 2,
         'Tornakalns': 2,
         'Portugal': 2,
         'Macedonia': 2,
         'Netherlands': 2,
         'Romania': 2,
         'Portuguese': 2,
         'British': 2,
         'Vilkači': 2,
         'BMX': 2,
         'Riga Municipality': 2,
         'Rīga': 2,
         'Vilnius': 2,
         'Poland': 2,
         'Denmark': 2,
         'UK': 2,
         'Estonia': 2,
         'Bastejkalns': 2,
         'EUR': 2,
         'Turin': 2,
         'the Italian Republic': 2,
         'Afro': 1,
         'Latino': 1,
         'Advent city’s': 1,
         'Imanta': 1,
         'Brička': 1,
         'Advent': 1,
         'Edinburgh': 1,
         'Zurich': 1,
         'Craiova': 1,
         'Lithuania': 1,
         'Tutas': 1,
         'Lithuanian': 1,
         'Hollywood': 1,
         'US': 1,
         'French': 1,
         'Australian': 1,
         'Macedonian': 1,
         'Estonian': 1,
         'Canadian': 1,
         'German': 1,
         'Swedish': 1,
         'Mārcis': 1,
         'Avoti': 1,
         'Brussels': 1,
         'Rome': 1,
         'www.baltanakts.lv': 1,
         '824th': 1,
         'Ukraine': 1,
         'Dzegužkalns': 1,
         'Futurimo': 1,
         'Skani': 1,
         'Grezno': 1,
         'Ziepniekkalns Ēbelmuiža Park': 1,
         'Vakarbuļļi Beach': 1,
         'Čipsis': 1,
         'Esplanāde': 1,
         'Grīziņkalns Park': 1,
         'Zaļumballes': 1,
         'Victory Park': 1,
         'the Ēbelmuiža Park': 1,
         'Ziepniekkalns': 1,
         'Bolderāja': 1,
         'Vilcenes': 1,
         'the Baltic States': 1,
         'London': 1,
         'www.mystero.lv': 1,
         'Pārdaugava': 1,
         'Polish': 1,
         'Budimex': 1,
         'the Riga Municipality City Development Department Strategic Management Board': 1,
         'airBaltic': 1,
         'Uganda': 1,
         'Eritrea': 1,
         'Barcelona': 1,
         'Hamburg': 1,
         'Geneva': 1,
         'Singapore': 1,
         'São Paulo': 1,
         'U23': 1,
         'Manchester': 1,
         'Latvians': 1,
         'Āgenskalns': 1,
         'Zolitūde': 1,
         'The Riga Municipality': 1,
         'Kokle': 1,
         'Grodi': 1,
         'Skandinieki': 1,
         'the Park Ziemeļblāzma': 1,
         'Grīziņkalns': 1,
         'Vardītes': 1,
         'the City Canal': 1,
         'Lapeņu': 1,
         'Riga City': 1,
         'Galleria': 1,
         'Palazzo Pitti': 1,
         'Pitti': 1})

In [120]:
len(countries)

583